### ISSUE TITLE
Running WebTools behind reverse proxy

### ISSUE THREAD

**Issue by mescon** [ukdtom/WebTools.bundle#123]
Hey!

I'm trying to run WebTools through an nginx reverse proxy where I handle SSL and authentication.

I have all of my services running on https://my.server.com/glances and what not, but I have not yet been able to get WebTools to function properly in this setup.

```
location /webtools/ {
        proxy_pass      http://10.9.0.3:33400/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
}
```

... should do the trick, however, it only redirects me to `https://my.server.com/login?next=%2F`.

I had the same problem with Glances which was fixed by doing:

```
location /glances/ {
        proxy_pass http://10.9.0.4:61208/;
        proxy_buffering  off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect /glances/ http://10.9.0.4:61208/;
}

location / {
        if ($http_referer ~ "^https?://[^/]+/glances") {
                rewrite ^/(.*) /glances/$1 redirect;
        }
```

This approach didn not work with WebTools however.

Has anyone got this running properly?

**Comment by ukdtom** [comment]
Sadly clueless here, since I don't use nginx.
Suggest you try the forums instead, since only a fraction of WebTools users are on GitHub

**Comment by mescon** [comment]
Will do, thanks!

**Comment by fenichelar** [comment]
@mescon Did you ever find a solution?

**Comment by mescon** [comment]
I didn't, no... :(

**Comment by Ninjouz** [comment]
Webtools needs to have a base_url in order to make reverse proxy possible.

The homepage should be : http://IP:33400/webtools  so we can redirect www.hostname.dom/webtools to IP:33400/webtools

**Comment by ukdtom** [comment]
@creoludifico 

Any insights here?

**Comment by ukdtom** [comment]
If base_url is set to like `/ged`, and you then browse to `IP:Port/ged`, it seems like frontend is failing.

Browsing to  `IP:Port/ged/` does however works....Note trailing slash

And Chrome debugger shows, that base_url is not picked up by the fromtend

**Comment by ukdtom** [comment]
Closing with above commit.
Fixed in backend

**Comment by ukdtom** [comment]
Darn.....

If not using a basepath, a successful login redirect fails :(

Unsure, but suspect that login.js in it's detection of the basepath failes :(

This however seems to work:
`    if ($(location).prop('pathname') == "/login"){
        basePath = "/"
        }
    else{
        try {
            basePath = "/" + $(location).prop('pathname').split('/')[1] + "/";
            }
        catch (err) {
            basePath = "/";
            }
        }
`

But will leave it up to you to decide

**Comment by creoludifico** [comment]
Already fixed. Merge with me 😉

**Comment by ukdtom** [comment]
SIGH....
