### ISSUE TITLE
Themes - v2.2 release - Default theme error

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#166]
When using the default theme (default.css) there is an error that causes the 'ALL' button on the UAS page to appear as selected. This clears if you click on the page to change focus. This can also effect other themes.

The following line in the default.css:
.btn-default:focus {background-color: #FE9B00; color: #242424;}

Should read:
.btn-default:focus {background-color: #FFFFFF; color: #242424;}

**Comment by dagalufh** [comment]
I'll look into this and see if it's even needed still.

**Comment by dagalufh** [comment]
Fix implemented for next release. Removed all highlighting.

**Comment by ukdtom** [comment]
Need STD to confirm working or not

**Comment by ukdtom** [comment]
@dagalufh Can we close this one, or?

**Comment by dagalufh** [comment]
Yeah think so
