### ISSUE TITLE
[Frontend] Error message

### ISSUE THREAD

**Issue by dagalufh** [ukdtom/WebTools.bundle#168]
Add message to provide logfiles when contacting support.

**Comment by creoludifico** [comment]
@ukdtom 
Maybe i need a better explanation of what's required with this issue?
Is it a button where you can upload your log file? And where? Contact support in web tools (where)?

**Comment by ukdtom** [comment]
WebTools/Help/Forums for the link to show people

And used when WT returns like an http error 500 etc.

**Comment by creoludifico** [comment]
Ready for test.
@ukdtom 
The message to the user about the path to the LOG file is a bit deviant.
Can you make a download log file in the backend for me?

9aa430dc841ecba0c8a62dccfcf15ef5de53e898

**Comment by ukdtom** [comment]
Well, that's a simple call you make ;-)

`Download
To download a log file, issue a get like:
/webtools2?module=logs&function=download&fileName=com.plexapp.plugins.WebTools.log.1

As with above, remember to replace space with %20
Download entire log directory as a zip
Same as Download, but without the fileName parameter
To grap the entire log directory as a zip file, issue a get like:
/webtools2?module=logs&function=download

`

**Comment by ukdtom** [comment]
And suggest that you grap everything here, meaning without a specified filename

/T

**Comment by creoludifico** [comment]
MB, i should have looked for it first, but cooool. I'll take the entire one ;)

**Comment by creoludifico** [comment]
Now b76432e6b642165a915baf4e1cd44f5766597c24

![image](https://cloud.githubusercontent.com/assets/12425208/22177782/78fa8ca8-e025-11e6-9d4b-803508032f9d.png)

**Comment by ukdtom** [comment]
Confirmed
