### ISSUE TITLE
[All] Add search function to SUB module

### ISSUE THREAD

**Issue by dagalufh** [ukdtom/WebTools.bundle#171]
Add a function that allows the frontend to search for a movie or a tv show.
Episodes are not really needed so just show name and movie title.

Prefered returnvalue would be the key of the item/items in question and let the frontend query for the rest of the information. That would make it a generic function that can be placed in pm module or something alike.

**Comment by ukdtom** [comment]
SNIFF....PAyback time I guess :-)

**Comment by ukdtom** [comment]
Duplicate of https://github.com/dagalufh/WebTools.bundle/issues/162
So guess you really want this :-P

Closing the other one

**Comment by ukdtom** [comment]
Fixed in https://github.com/dagalufh/WebTools.bundle/commit/f89ca317d240288b52f5e1fc979826905118b739

**Comment by ukdtom** [comment]
Now up to you :-)

**Comment by creoludifico** [comment]
If it's findmedia module i need the following issue to be resolved first
https://github.com/ukdtom/WebTools.bundle/issues/227

**Comment by ukdtom** [comment]
And when said, this is not related to FM, AFAIK

It's related to the SubTitle module, where one can search for a movie or show, in order to fix subs

**Comment by creoludifico** [comment]
Roger that

**Comment by creoludifico** [comment]
Search imp but only for movies for now.
I need some rework on the search func in backend for v3

**Comment by ukdtom** [comment]
Perfect
