### ISSUE TITLE
WT Update Alert

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#174]
Since WT is an on demand tool, I think we would be safe by having the frontend doing a check right after login, to check if a newer version is avail or not, and if so, show a modal box telling the user to upgrade.

**Comment by dagalufh** [comment]
Hmm, is this not dangerous based on what killed UAS V1?

**Comment by ukdtom** [comment]
Kinda yes, but the diff. here is that the old UAS did this scheduled every 12 hours.
We would only do it during a login, and kinda doubt people use it every 12 hours ;-)

**Comment by ukdtom** [comment]
And we natrually only talk about WT itself here ;-)

**Comment by dagalufh** [comment]
Included in next commit from me.

**Comment by ukdtom** [comment]
Awaits further testing here....But logs clearly indicate a check towards GitHub, so logic dictates all is good

**Comment by ukdtom** [comment]
Closing for now, regardless
