### ISSUE TITLE
UAS: Force update of Repo

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#177]
Suggest, that the GUI has a menu, that allows the user to do a forced update of the cache

Check doc for updateUASCache in the Git module

**Comment by dagalufh** [comment]
Added a button next to check for update for all installed channels.
![image](https://cloud.githubusercontent.com/assets/8938352/20942703/df0fe832-bbfc-11e6-80fa-d4d338e42145.png)

**Comment by dagalufh** [comment]
Will be in next commit.

**Comment by ukdtom** [comment]
Doc says:
If you add the optional parameter Force=true, and case sensitive, UASCache will be forced updated

You add: force=true

**Comment by ukdtom** [comment]
Fixed
