### ISSUE TITLE
[subtitles] add a download button for sidecar subtitles

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#181]
Please add the possibility to download sidecar subtitles.
Reasoning: Automatically downloaded subtitles are hidden in the obfuscated mess that is the plex data folder. For a normal user to find the right subtitle file in here is next to impossible (or at least very tedious).

If you now try to get ahold of this subtitle file to edit it or to move it beside the video file on your laptop you use in the countryside where there is not internet, you have a hard time.

Maybe, in stage 2, you could opt to move the file automatically beside the video file and, after checking it was successfully copied ;-) remove it from the Plex data folder.
Some users may prefer this method.

**Comment by ukdtom** [comment]
But if we move it, agent will re-download it again, so that part will not work, or?

**Comment by OttoKerner** [comment]
> But if we move it, agent will re-download it again, so that part will not work, or?

As I understand it, the agent will only download subtitles if the movie is refreshed. I may be wrong though.
But even if so, the first option is still very desirable.

**Comment by ukdtom** [comment]
We need to make a download button for both agent based and sidecars.
First we need to make a backend function for this :-(

**Comment by ukdtom** [comment]
Framework updated with https://github.com/dagalufh/WebTools.bundle/commit/c6d17123390fd1d89e8f0c345feb7e8f413dcd23

**Comment by creoludifico** [comment]
Ready for test.
Only sidecars subtitles are possible to download.

30478121d41ea1db3cc9c0972cc1207a1732442a

**Comment by ukdtom** [comment]
Tested okay by me.

@OttoKerner What you had in mind here?

Ohhh....and while at it, please also look into https://github.com/ukdtom/WebTools.bundle/issues/243

Download my work branch for a test
https://github.com/ukdtom/WebTools.bundle/archive/tommy-work.zip

**Comment by ukdtom** [comment]
@creoludifico Please see comments for #245 

Sorry

**Comment by creoludifico** [comment]
Now possible to download if it's agent sub

**Comment by OttoKerner** [comment]
Download is working for me. 👍 
Page navigation as well.

**Comment by ukdtom** [comment]
Thanks Otto
