### ISSUE TITLE
[subtitles] add an option to shorten the list to only items with 'unfiltered' subtitles

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#205]
If one has a library with several hundred items or more, it becomes very tedious to manage the subtitles with the current UI.
So if I decide to filter out the embedded subtitles (which is possible already by preference) I'd like to shorten the movie list to only movies with subtitles that can be managed through WebTools.

Ideally, the fact should be communicated to the user, for instance like so:
- Filtered list: only items with external/internal subtitles appear. To get the full list, select $preference. -

**Comment by ukdtom** [comment]
If so, we need a filter saying: "Show media without subs"
Otherwise, it's hard to use this for upload of a new sub

**Comment by OttoKerner** [comment]
> Otherwise, it's hard to use this for upload of a new sub

That's why the info about the active filter is so important. If user wants to upload a subtitle for a movie that has no subtitle yet, user needs of course the unfiltered list.

**Comment by creoludifico** [comment]
Last one in 2.4 is now ready for test

**Comment by ukdtom** [comment]
Perfect
