### ISSUE TITLE
RFE:  FM: Add option to include or ignore validation of PMS 'extras'

### ISSUE THREAD

**Issue by ChuckPa** [ukdtom/WebTools.bundle#211]
PMS extras   "Season 0", "Specials",  and all suffix extras "-deleted", "-trailer", etc  are ignored.

Request option to enable checking / validating these files as well.

**Comment by ukdtom** [comment]
Got a new dict value: Dict['findMedia']['IGNORE_EXTRAS'] that is boolean.
We need to expose that to the settings of FM, like we expose the setting "Ignore Hidden"

Purpose of this is that if true, then we report extras in the report as well

**Comment by creoludifico** [comment]
@ukdtom 
Default true?

**Comment by creoludifico** [comment]
Oh nvm you control it in the backend

**Comment by creoludifico** [comment]
@ukdtom Where did u commit the updates for IGNORE_EXTRAS?

**Comment by ukdtom** [comment]
Sorry, and here: https://github.com/ukdtom/WebTools.bundle/commit/bb2ff58812545944664f9273dcbbd1933f8a8077

**Comment by creoludifico** [comment]
Oh so not for 2.4?

**Comment by ukdtom** [comment]
Nope, a 3.x one only

**Comment by creoludifico** [comment]
Roger that

**Comment by OttoKerner** [comment]
Local movie extras using the 'extras subfolder method' are **not** ignored, currently.
```
Movies /
   Léon The Professional (1994) /
   Léon The Professional (1994) - 1080p.mkv
      Behind the Scenes / 
         10 Year Retrospective.mkv
         Jean Reno The Road to Léon.mkv
         Natalie Portman Starting Young.mkv
```
the 3 extras in the `Behind The Scenes` subfolder all appear as 'Missing From Plex DB'

currently used subfolder names for this Plex feature:
```
    Behind The Scenes
    Deleted Scenes
    Featurettes
    Interviews
    Scenes
    Shorts
    Trailers
```
source: https://support.plex.tv/hc/en-us/articles/200220677-Local-Media-Assets-Movies

**Comment by creoludifico** [comment]
Done?

**Comment by OttoKerner** [comment]
This particular issue with FindMedia appears to be solved.
At least here under Windows.

**Comment by ukdtom** [comment]
Thanks Otto
