### ISSUE TITLE
Alphabetical listing of channels

### ISSUE THREAD

**Issue by coder-alpha** [ukdtom/WebTools.bundle#221]
Currently the list of channels in UAS2 is sorted based on Uppercase alphabets followed by lowercase, eg. ABC... abc... instead is it possible to have them listed based on AaBbCc...

**Comment by ukdtom** [comment]
Sadly confirmed when selecting all and scrolling

Ref: https://github.com/dagalufh/WebTools.bundle/issues/95

**Comment by STEW1327** [comment]
plex movies and sports all of

**Comment by dagalufh** [comment]
Fixed in next commit.

**Comment by ukdtom** [comment]
Confirmed

**Comment by coder-alpha** [comment]
I see this issue again with the V3 translator build. Screen shot attached.

![image](https://user-images.githubusercontent.com/10291660/30405608-dfe5c844-98ba-11e7-8291-19385df0cdd2.png)

**Comment by ukdtom** [comment]
Confirmed

**Comment by ukdtom** [comment]
Brilliant
