### ISSUE TITLE
SUB: SubZero Custom Folder

### ISSUE THREAD

**Issue by acs-ferreira** [ukdtom/WebTools.bundle#223]
We can configure SubZero to use a Custom Folder to store subs instead of "Next to the file".
But when using WebTools to upload subs, they are stored next to the file, and not on custom folder.

It would be fine to use that folder.

**Comment by ukdtom** [comment]
Too much on the plate already, so sadly moving this ahead :(

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
