### ISSUE TITLE
Can't install Sonarr plugin in WebTools

### ISSUE THREAD

**Issue by dny238** [ukdtom/WebTools.bundle#225]
I think there's an issue adding the Sonarr plugin bundle via webtools. 
It's like the zip file name isn't correctly generated

Using, 
https://github.com/jamorin/Sonarr.bundle

I get, 
> #637	2016-12-16 01:26:46,332 (7fca897fa700) : DEBUG (logs:78) - Starting Logs.entry function
#638	2016-12-16 01:26:46,332 (7fca897fa700) : DEBUG (logs:81) - FrontEnd: [Core] Completed AJAX Call for URL: /webtools2?module=git&function=uasTypes&_=1481839414112
#639	2016-12-16 01:26:50,116 (7fca897fa700) : DEBUG (webSrv:307) - Recieved a get call for module: git
#640	2016-12-16 01:26:50,117 (7fca897fa700) : DEBUG (git:846) - Starting install
#641	2016-12-16 01:26:50,117 (7fca897fa700) : DEBUG (git:552) - Bundle directory name digested as: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sonarr.bundle
#642	2016-12-16 01:26:50,118 (7fca897fa700) : DEBUG (networking:166) - Requesting 'https://github.com/jamorin/Sonarr.bundle/archive/.zip'
#643	2016-12-16 01:26:50,376 (7fca897fa700) : ERROR (networking:219) - Error opening URL 'https://github.com/jamorin/Sonarr.bundle/archive/.zip'
#644	2016-12-16 01:26:50,378 (7fca897fa700) : CRITICAL (git:765) - Exception in downloadBundle2tmp while downloading from GitHub: HTTP Error 404: Not Found (most recent call last):
#645	File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Code/git.py", line 765, in downloadBundle2tmp
#646	Log.Exception('Exception happend in downloadBundle2tmp: ' + str(e))
#647	File "/usr/lib/plexmediaserver/Resources/Plug-ins-1751929/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/utilkit.py", line 50, in ZipFromURL

**Comment by ukdtom** [comment]
Version of WebTools, and platform?

**Comment by ukdtom** [comment]
Closed due to lack of response
