### ISSUE TITLE
[Feature Request] - Find Duplicates

### ISSUE THREAD

**Issue by JamminR** [ukdtom/WebTools.bundle#226]
Suggestion - Find Duplicates (in addition to find missing/unmatched modules).
Find duplicates would allow you to scan all/several libraries for the same movie or music artist, then list the file location/name of the duplicates.
I imagine some of the metadata fields for a, say, same video in two different libraries, share a part that is duplicated among both and that hopefully that duplicated metadata could be used to point out locations/file names.
Scenarios
- I have 2 'movie' libraries. One containing content I have on disc and converted to multipurpose format, one of, uh, demo/sample *cough* content for my shopping list.
I keep finding myself getting a disc from my shopping list and after converting it, forgetting to remove the poorer quality sample video/track from the other library.

- Having this for music would be great too. I've got so many music single duplicates that share different filenames, with little to no ID3 tag internally to compare, it's crazy, and even Plex has trouble sorting them all out.

**Comment by ukdtom** [comment]
Consider for V4.
V3 already got enough

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
