### ISSUE TITLE
Philips Hue Bridge detected as IP address

### ISSUE THREAD

**Issue by philhawthorne** [ukdtom/WebTools.bundle#228]
I am running Plex on a Synology NAS. The IP addresses of my NAS are set at the router level to

- 192.168.1.3
- 192.168.1.25

I also have a Philips Hue bridge on my network, which has been designated the IP address 192.168.1.2. When navigating to the Webtools page inside Plex, it prompts me to go to http://192.168.1.2 instead of 3. So it is telling me to go to the Hue Bridge.

I can access Webtools on the correct IP address, however when installing channels through the unsupported channels plugin, it says it has installed the plugin to my Plex channels, however it never installs. I am guessing Webtools is sending the install request to the incorrect IP address (ie the Hue Bridge).

Is there a way I can tell WebTools which IP address to use? I tried to find the log files which might have some extra details, but from what I can see there are no log files for the webtools app.

Thanks!

**Comment by ukdtom** [comment]
WebTools binds to all IP Addresses

Regarding it never install a plugin, could be rights related, but logs would tell us

**Comment by philhawthorne** [comment]
Thanks @ukdtom 

Which logs would you like? I looked at the Unsupported App Store logs, but couldn't see any logs of it installing plugins from within Webtools.

**Comment by ukdtom** [comment]
The WebTools logs, right after reproducing the error

**Comment by philhawthorne** [comment]
Thanks @ukdtom 

After checking the logs, and checking the output the plugin installed. Ugh so now I can't replicate. 

If I ever replicate again, I'll re-open this.

Thanks for an awesome tool!
