### ISSUE TITLE
add ability to search plugins

### ISSUE THREAD

**Issue by danielb2** [ukdtom/WebTools.bundle#230]
add ability to search plugins. I want to search all plugins that are related to anime, but I have to go through all and every page atm

**Comment by ukdtom** [comment]
Nice idea

**Comment by ukdtom** [comment]
Confirmed search is working, but as you mention in your commit, we need to update counters as well ;-)

**Comment by creoludifico** [comment]
Ready for test. (Counter and ENTER event added)
Do you want a label attached to this issue?

**Comment by creoludifico** [comment]
First part commit) https://github.com/ukdtom/WebTools.bundle/commit/156631c2a0198523b6e103c915419c60618bb611
Second part commit) https://github.com/ukdtom/WebTools.bundle/commit/8c7b36fecae17a7b07348a8e2f12c7ac473033d8

**Comment by ukdtom** [comment]
Verified as working.
Great start on this project ;-)

**Comment by danielb2** [comment]
Awesome ☺
