### ISSUE TITLE
Hardcoded strings to const/var

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#233]
Strings like "WebTools" that is used for programming purposes and not display (UI) purposes should be hold in a CONST or var.

**Comment by ukdtom** [comment]
I hate you already :-P

**Comment by ukdtom** [comment]
Fixed with https://github.com/ukdtom/WebTools.bundle/commit/04b30e2fdfc7cfba3882349a4255e980f4b1e785
