### ISSUE TITLE
New GUI for 3.x

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#236]
GUI refresh, as suggested by @creoludifico

**Comment by creoludifico** [comment]
An idea.
Lets include the users and maybe get some user input.
Whats the 3 biggest wishes from the users?

**Comment by ukdtom** [comment]
No idea here, so let's first of all ask the forum moderators (Ninja's) since they cover all forums

I'll handle that, and report back

**Comment by OttoKerner** [comment]
- bring the different functionality of Webtools more to the fore, not hidden away in a dropdown
- in the subtitle module, make paging through the movie list faster and less tedious (see https://github.com/ukdtom/WebTools.bundle/issues/146 )
- when changing into the subtitle module, show the list of libraries right in front of the user, don't direct him into a dropdown first

**Comment by ukdtom** [comment]
Thanks Otto, and FYI @creoludifico , Otto is a Plex Team member ;-)

**Comment by CoalaJoe** [comment]
IMHO it should look more like plex.

**Comment by ukdtom** [comment]
@CoalaJoe 

Nope, since then we would get too close to violating what's allowed by Plex!

**Comment by creoludifico** [comment]
@ukdtom Can we close this issue for now?

**Comment by ukdtom** [comment]
Indeed.
We'll ask beta testers to create individual ones when we get closer to an official beta
