### ISSUE TITLE
UAS main screen

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#240]
UAS main screen has a link towards Plex2CSV for a manual install

We need to change that into: https://github.com/ukdtom/ExportTools.bundle instead, since that will replace the other one, when the next version of PMS is released

**Comment by ukdtom** [comment]
And would btw. be nice, if the link was pre-populated into the input box, or?

**Comment by creoludifico** [comment]
Hmm. I don't think it would be a good idea to populate it as text, so the user has to remove it everytime they want to download something manually.
A placeholder would be fine tho

**Comment by ukdtom** [comment]
Ack, and your call ;-)

**Comment by creoludifico** [comment]
Fixed with placeholder 
Ready for test
bd8e693575a3b66fe43028ced55366421563ed10

**Comment by ukdtom** [comment]
Perfect as always, but never ever wanna be quoted on that ;-)
