### ISSUE TITLE
WebTools 3.0 backend GetBundle optimization

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#242]
It would be really nice to get a JSON list ( [] ) from the backend instead of a JSON object ( {} ) when calling getAllBundleInfo.
This shall not affect the current version 2.X. Only 3.X.

**Comment by ukdtom** [comment]
Note to self:
In order to provide backwards compatibility, we'll need a new endpoint for that though, like /webtools3/*

So if a call towards the 3 framework fails with an unknown call, we should fallback to the old 2 framework

That way, frontend can use 3 framework calls for everything

**Comment by ukdtom** [comment]
Fixed with above
