### ISSUE TITLE
SRT Module navigator broken

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#243]
When opening up a library, then at the bottom, we should have a page navigator.

Seems broken, so only first page can be reached :-(

Suspect it's based on getSectionSize or getSectionLetterList

**Comment by ukdtom** [comment]
![wt-srt_bug](https://cloud.githubusercontent.com/assets/4699449/22181926/e14072f6-e097-11e6-8dd3-56b0b101eed5.png)

Look at the bottom right, where the navigator is empty

**Comment by creoludifico** [comment]
Cannot reproduce in any version/branches

**Comment by ukdtom** [comment]
I'll get somebody else to test, to check if it's just me going waco here

**Comment by ukdtom** [comment]
Navigator came back, when merging your branch into mine....

Strange---
