### ISSUE TITLE
Editing the update window

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#244]
Edit the VERSION file content to test
![image](https://cloud.githubusercontent.com/assets/635345/22182145/04407e96-e05b-11e6-8040-9d1fb59c76ce.png)

**Comment by ukdtom** [comment]
Disregard ;-)

Info is fetched from the release page, so we change it there when we release V2.4 ;-)

https://github.com/ukdtom/WebTools.bundle/releases/latest
