### ISSUE TITLE
Make a new key for UAS to show realtime description

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#247]
Let's make a key in UAS, that is an url to a limited readme file in the individual gits that UAS points towards.

Meaning that an entry in uas could have a key like:

gitdesc : https://github.com/ukdtom/ExportTools.bundle/blob/master/README.md

Could also point elsewhere, but that's up to 3.Party.

Then, if the key is present, we could have a button in the use, named "Show Info", that would spawn a popup with the contents of above

**Comment by creoludifico** [comment]
Good idea. Shall the frontend build the url self? I mean by adding the /blob/master/README.md

Else i guess we need the value in the UAS repo, and then the frontend makes at call. If the new key is present, link to the url

**Comment by ukdtom** [comment]
I think the exact path should be left for 3.Parties, since they might even provide a special file just for this

We do however need to specify the format that should be in, like pure text, markup or siml.

**Comment by creoludifico** [comment]
Please make a key in UAS so i have something to test with :)

**Comment by ukdtom** [comment]
A key named manual has been added to ExportTools, that points towards it's wiki.

Manual is of the type URL

**Comment by creoludifico** [comment]
This should have been fixed now right?

**Comment by ukdtom** [comment]
Indeed
