### ISSUE TITLE
WebTools V3 - Removal of response header

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#252]
The following "set header" needs to be removed from every api call. (Not replaced. Just removed)
`req.set_header('Content-Type', 'application/json; charset=utf-8')`

The front end can handle alone the default response.

**Comment by ukdtom** [comment]
Fixed with above commit

**Comment by ukdtom** [comment]
Need another approach, så rolling back commit here

**Comment by ukdtom** [comment]
URL should hare a param like: noheader=True, if no header should be returned

**Comment by ukdtom** [comment]
Slated for API V3, so closing this
https://github.com/ukdtom/WebTools.bundle/issues/256
