### ISSUE TITLE
Sub Management - Delete subs on Windows

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#255]
Error while trying to delete a sub.
Probably on Windows only.

2017-01-29 22:01:39,996 (18f0) :  DEBUG (logkit:13) - Recieved a delete call for module: pms
2017-01-29 22:01:39,997 (18f0) :  DEBUG (logkit:13) - Delete subtitle requested
2017-01-29 22:01:39,997 (18f0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/1/tree'
![image](https://cloud.githubusercontent.com/assets/12425208/22407861/105ea580-e66f-11e6-8924-caa10607975b.png)

If possible fix this in v3 too.

**Comment by creoludifico** [comment]
A quick solution is to go and change the permission on the file.
This ofc require the user to do it and therefore not as viable

**Comment by ukdtom** [comment]
What do you mean about permissions on the file?
Do we not have the needed rights?

And if so, then this is a problem between the user and his OS, and not ours

**Comment by creoludifico** [comment]
Yup, then we can't do anything about it.
It's the permissions to create/read/write that is needed but not obtained through the user.
I dunno if this is a common problem from the users. If so we can create an FAQ on how to avoid the problem.

Untill we can close the issue

**Comment by ukdtom** [comment]
We can't start manage user rights, that's out of scope!

And only a common problem on Linux, where users are running PMS as a deamon with a user named plex.
In above cases, we tell them to fix their rights

Closing this ;-)
