### ISSUE TITLE
API V3

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#256]
We need to do a cleanup here, so starting on API V3

Calls are going towards PMS:Port/api/v3

**Comment by ukdtom** [comment]
Commit https://github.com/ukdtom/WebTools.bundle/commit/bd73aa6cb64e922f9d1570dda8d01cef46e6d48f

So far, module wt has been transformed, and reset function switched from post to put

**Comment by creoludifico** [comment]
If you only return a string like you are doing whetever there is an exception i need you to either remove the header(Json) or dumps it as json

**Comment by ukdtom** [comment]
There is no header?

`			req.clear()
			req.set_status(412)
			req.finish('Unknown function call')
`

**Comment by ukdtom** [comment]
At least according to PostMan ;-)

**Comment by ukdtom** [comment]
API V3 now done for all current modules
