### ISSUE TITLE
Localize frontend

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#258]
We should consider making the frontend support multiple languages.

I'm considering the following:

/version will have a key named like `Language:en` or siml, and then the whole website changes to that.

language files needs to be in a separate directory somewhere below /http, and we need a file like:
`strings.en` to serve as a template for users to translate from.

Translation will be handled by the community, so nothing we need to consider here, we only need to provide the means

**Comment by creoludifico** [comment]
We need to have a oral conversation about this issue.

**Comment by creoludifico** [comment]
Move to project :)

**Comment by creoludifico** [comment]
Closing. Moved to https://github.com/ukdtom/WebTools.bundle/projects/8
