### ISSUE TITLE
FindMedia ignores .plexignore

### ISSUE THREAD

**Issue by diligiant** [ukdtom/WebTools.bundle#262]
it would be neat if, while scanning, FindMedia used .plexignore to supplement Webtools "ignore directories" preference.

**Comment by ukdtom** [comment]
This is sadly a no-go, since the .plexignore file can be put on multiple levels in the file system, and if used by us, we would have to walk all the way up when checking every file => huge impact on time to run.

As such, we use our own prefs to exclude directories and files

**Comment by diligiant** [comment]
Thank you for your answer although I don't understand the argument ;)

I "see" numerous way to do this "effortlessly" and I might add that my own experience of a HUGE library doesn't bear the problems you envision.
