### ISSUE TITLE
Sub: No paging by letter, for TV-Shows

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#265]
Users reports, that paging is empty for Shows, since  getSectionLetterList isn't called

**Comment by creoludifico** [comment]
Fixed.. Will now get all series.

**Comment by ukdtom** [comment]
Confirmed working...

No need to fix #264 , and then I'll release

/T

**Comment by ukdtom** [comment]
Still using prefs as a max of seasons to show....

Default is 15, but if you happen to have a show with +15 seasons, it'll not show remaining

Same goes with episodes....

So guess we for shows for a quick fix should drop size param

**Comment by creoludifico** [comment]
Hmm must be some backend stuff.. I'm not calling anything with any limit value

**Comment by ukdtom** [comment]
True, and confirmed, but also confirmed, that backend returns as ordered, so guess frontend only present according to the max in the options?

**Comment by ukdtom** [comment]
STD: Set "Items per page (Max: 50. Min: 5)" to 5

/T

**Comment by creoludifico** [comment]
Oh okay i can ignore that one.
Hold on i look

**Comment by creoludifico** [comment]
Min and max removed from tv shows.

**Comment by ukdtom** [comment]
Perfect, thanks
