### ISSUE TITLE
WT Update on Windows platform

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#269]
Seen issues on Windows, where update procedure delete files not to be deleted, after downloading

**Comment by ukdtom** [comment]
Note, API call change here!

To upgrade, the method to call is named upgradeWT
See the doc for more details

**Comment by creoludifico** [comment]
Should be fixed now

**Comment by ukdtom** [comment]
This will have to wait a little while

**Comment by creoludifico** [comment]
And btw when there is a new version available the Upgrade btn will be visible in the menu

**Comment by ukdtom** [comment]
Created a new Github repo, named https://github.com/ukdtom/wtupgtst

Tested against that, since it contains a release named 3.0.0

Nothing happened?

**Comment by ukdtom** [comment]
Please pull my branch, and check the docs regarding debug....

Note, that you hard-coded front-end with the repo to check against....

Should be pulled from /version!

**Comment by ukdtom** [comment]
Backend should/must disable autoupdate for now

**Comment by ukdtom** [comment]
Working fine for me now....!!!!
BUT....FrontEnd must reload the logon page, and wait until it responds!

Do test, add this to debug file:
`"WT_URL" : "https://api.github.com/repos/ukdtom/wtupgtst/releases/latest"`

And would be nice, if frontend when calling to get the releaseinfo, would use WT_URL from version ;)

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/blob/tommy-work3-pmsV3-partial/http/static/login/login.js#L176

**Comment by ukdtom** [comment]
Seems to work now...

debug file should be like:
`"WT_URL" : "https://github.com/ukdtom/wtupgtst"`

And frontend still needs to return to logon screen after retrieving 200 from backend, and then wait for website to be online again

**Comment by creoludifico** [comment]
Works now!

I've added the timeout. I'll cross my fingers that this is the last one bef release
