### ISSUE TITLE
Subs: No view of subs?

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#271]
Missing option to view a sub

**Comment by creoludifico** [comment]
Just a temporary solution implemented.
Todo: The content of file needs to be formatted in the view

**Comment by ukdtom** [comment]
Okay so far.
Would be nice, if we also could get the same search here as we have with the logs module ;)

**Comment by creoludifico** [comment]
Return as an array like with the log files

**Comment by ukdtom** [comment]
Could be wrong here, but AFAICS, I return the same format for both logs and subs, or?

**Comment by creoludifico** [comment]
![image](https://user-images.githubusercontent.com/12425208/28311223-3d3dfae0-6baf-11e7-9ea7-f2193e5cf37c.png)

**Comment by creoludifico** [comment]
I've tried with multiple subtitles. None of them works?

**Comment by ukdtom** [comment]
Are you using the subs key?

You can get that with a call to 
`/api/v3/pms/getSubtitles/<KEY OF MEDIA>`

Cuz working fine here

**Comment by creoludifico** [comment]
Can we move it to V3.1?
It will take some time to create a view tool that is just like with logs for this.

**Comment by ukdtom** [comment]
Talked about this, and we decided not to do any fancy stuff here, so all that is missing now, is respecting the <CR> tags when presenting it to the user

**Comment by ukdtom** [comment]
![viewsub](https://user-images.githubusercontent.com/4699449/28971016-d48398dc-792a-11e7-9dbb-518b1358ca19.png)

How it looks in V2.41

**Comment by creoludifico** [comment]
I hope u like it ;)

**Comment by ukdtom** [comment]
I do ;)
