### ISSUE TITLE
API V3 PMS Search

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#273]
PMS - Search is currently a POST, which is wrong.

Needs to switch it into a GET

**Comment by creoludifico** [comment]
Is it possible for you to include optional search in every "GetList" func?

Example
API/GetList?start=0&size=20
API/GetList?start=0&size=20&search=blah

**Comment by creoludifico** [comment]
If u want to keep the /start/0/size/20. It's fine by me >.<

**Comment by ukdtom** [comment]
Fixed with above commit
