### ISSUE TITLE
API V3: GetList and filter

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#274]
Add filter to GetList

Ref: #273

**Comment by ukdtom** [comment]
@creoludifico 

Native PMS Framework search is search by titlt in a library

So please be a tad more specific here

**Comment by creoludifico** [comment]
It's just instead of having redundant code

**Comment by creoludifico** [comment]
It's just instead of having redundant code. First make a getlist then make a search call that returns exactly the same just filtered

**Comment by creoludifico** [comment]
That was an example btw. It would be neat if the getSections just had an option for search ex. instead that i had to call a second method for the filtrering

**Comment by creoludifico** [comment]
And we can talk about this tommorrow if you need some better clarification.

**Comment by creoludifico** [comment]
oh and last of all dont forget i'm the front end. I expect that if i ask for a bottle of gold i get a bottle of gold. *sarcasm*

**Comment by ukdtom** [comment]
![download](https://cloud.githubusercontent.com/assets/4699449/23145009/b83d79c6-f7cb-11e6-966e-59578f6eea9d.jpg)

**Comment by ukdtom** [comment]
Please let me know if above commit works as you want, and then reassign back to me with comments

**Comment by creoludifico** [comment]
So far looking good.. Just merged and tried some dummy calls

**Comment by ukdtom** [comment]
Check Skype ;-)

**Comment by ukdtom** [comment]
Please specify other methods where this would make sense

**Comment by creoludifico** [comment]
Where are we with this?

**Comment by ukdtom** [comment]
Awaits req. for other methods, that needs a filter

**Comment by creoludifico** [comment]
Closing.
Creating a issue if filter is needed
