### ISSUE TITLE
Logs: Search and arrows

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#275]
Search has a back button, but not a forward button?

**Comment by creoludifico** [comment]
It's default search behavior. If you click on the search button or enter it will automatically go the next line

**Comment by ukdtom** [comment]
Hmmm.....True, but not user friendly...

Could you add a forward button ?

**Comment by creoludifico** [comment]
yes ofc 😊

**Comment by creoludifico** [comment]
ready for test

**Comment by ukdtom** [comment]
Perfect
