### ISSUE TITLE
Error WebTools - v2.4.1

### ISSUE THREAD

**Issue by KingNickIII** [ukdtom/WebTools.bundle#281]
Failed updating UAS Cache. Looks like permissions are not correct, because we where denied access to create a needed directory.
If running on Linux, you might have to issue: sudo chown plex:plex ./WebTools.bundle -R

Reload the page and try again.
If the error persists please restart the server.
Contact devs on the Plex thread here if it occurs again. 

You can download the log files here

Technical details:

Requested URL: /webtools2?module=git&function=updateUASCache&_=1489349060658
Error Code/Message: 500/Internal Server Error

After trying the above command I received "chown: invalid group: 'plex:plex', using a raspberry pi 2+

**Comment by ukdtom** [comment]
Sadly, no idea about RasBy here :-(

But did you try the link that's mentioned under install in the first forum post?
[https://forums.plex.tv/discussion/comment/1368888/#Comment_1368888](url)

**Comment by KingNickIII** [comment]
Turns out I screwed up permissions and had to use "-R" on my webtools folder, thanks for the help though!
