### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by EWouters** [ukdtom/WebTools.bundle#287]
Hi,

I really like this project and have it installed on my server. I would like to host in on my server at example.com/plexwebtools

Would it be possible to add a reverse proxy feature? Possibly stored in WebTools.bundle/Contents/DefaultPrefs.json

**Comment by ukdtom** [comment]
Duplicate of #123

**Comment by EWouters** [comment]
Thanks for implementing this! (85c5003)
