### ISSUE TITLE
[REQ] UAS Category: new channels available

### ISSUE THREAD

**Issue by BenjaminHCCarr** [ukdtom/WebTools.bundle#288]
While @ukdtom's thread https://forums.plex.tv/discussion/200017 is hugely useful.

It would be very nice to have either a full toggleable category; banner; menu drop down, or some other way of alerting end users within the WebTools.bundle that plugins have been ADDED to [ukdtom/UAS2Res](https://github.com/ukdtom/UAS2Res).

I would suggest a 30 day window (which should be implementable with git time stamps) on ADD xxyyzz.png in [ukdtom/UAS2Res/blob/master/Resources](https://github.com/ukdtom/UAS2Res/blob/master/Resources/) or tracking merges in [plugin_details.json](https://github.com/ukdtom/UAS2Res/blob/master/Resources/plugin_details.json) directly.

As this would only be interesting to people actively managing it rather than set and forget I think 30 days would be reasonable; though if a 30|60|90|365 toggle was implemented that would be amazing, but that's like asking for the moon AND its satellites as well!

I have not dug in this code. Currently an otherwise overworked and very happy user.

**Comment by ukdtom** [comment]
Thinking out loud here to self....

If implemented, we should digest the plugin_details.json file, and provide that as well, as a "What's new" category, as well as have a prefs of the dates to calculate on.

**Comment by ukdtom** [comment]
Slated for 3.1 so far, since we have a lot of work going on here with the new GUI and the new API, but if time is on our side, we'll move it forward

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
