### ISSUE TITLE
Disappearing issue

### ISSUE THREAD

**Issue by StarOrpheus** [ukdtom/WebTools.bundle#291]
Hi. I've installed WebTools plugin. I'm running plex on my Arch-x64 laptop. 
After installing it gave me an error about permissions. I've chmod'ed plugin folder, but after a min it stopped working. I've started plex again, but WebTools folder dissapeared. 
When I'm trying to reinstall WebTools the Plugin dir just disappear after plex restart. 
Also, there is no WebTools logs in zip Plex gave me.
How to fix this? Thanks.

**Comment by ukdtom** [comment]
There's about 100% chance that you installed the WebTools.bundle dir into the wrong plugins directory,

Please read the wiki
https://github.com/ukdtom/WebTools.bundle/wiki/Installation

And do reopen if this doesn't help

**Comment by StarOrpheus** [comment]
Other plugins works well here, is it ok?

**Comment by ukdtom** [comment]
Exact name of directory, with full path

**Comment by StarOrpheus** [comment]
`/var/lib/plex/Plex Media Server/Plug-ins`
I've installed plex right via the Arch package manager

**Comment by StarOrpheus** [comment]
Currently there are such folders here:
```
[root@orpheusplanet Plug-ins]# ls -lh
total 12K
drwxrwxrwx 3 root root 4.0K Apr 13 12:55 BitTorrent.bundle
drwxrwxrwx 3 plex plex 4.0K Apr 11 20:58 Services.bundle
drwxr-xr-x 3 plex plex 4.0K Apr 13 13:16 Twitch.bundle
```

**Comment by ukdtom** [comment]
Don't know your distro, but do you have a directory named:

`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins` ?

**Comment by ukdtom** [comment]
Keyword in above is `Application Support`

**Comment by ukdtom** [comment]
And do you have a directory named `Plug-in Support` next to the `Plug-ins` directory?

**Comment by StarOrpheus** [comment]
Nope, the contents of `Plug-ins` dir is above

**Comment by StarOrpheus** [comment]
Well, I have `/var/lib/plex/Plex Media Server/Plug-in Support` directory (a neighbour)

**Comment by StarOrpheus** [comment]
I don't have `/var/lib/plexmediaserver` at all. All in all, in `/var/lib/plex/` I don't have the `Library` dir

**Comment by ukdtom** [comment]
What I meant with "next to" ;-)

Since WebTools doesn't remove itself, only PMS can, so try this:

* Power off PMS
* Install WebTools
* Power on PMS
* Wait for WebTools dir to be removed
* Check PMS log

**Comment by StarOrpheus** [comment]
Lol, it seems to be working!) Thanks!)
