### ISSUE TITLE
UAS: GUI V3

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#308]
1. Color scheme for installed vs. not installed are almost identical (Diff. shades of blue) making it hard for some people to pick up the difference.
2. Would be nice with icons for the individual plugins to show as well
3. Unknown category is empty, even if some are installed

**Comment by ukdtom** [comment]
And love the new layout ;-)

**Comment by creoludifico** [comment]
Take a look now ;)
and Unknown category??

**Comment by ukdtom** [comment]
Unknown category is where plugin's that are not part of UAS gets placed, when doing a migrate

And will check soon

**Comment by ukdtom** [comment]
When installing a plugin, the category menu to the right needs to be updated afterwards, to update the counters

**Comment by creoludifico** [comment]
Check check :) And check sub search too :)

**Comment by creoludifico** [comment]
Just notice to myself - Loading at manual install, refresh after migrate and force uas update

**Comment by ukdtom** [comment]
UAS V3 **MUST** show the support thread!

Old one also had a checkbox, so only installed plugins would show, when selecting the different categories

**Comment by ukdtom** [comment]
Migrate in the old version had a popup, telling the user which plugins that where migrated

Old uas also showed install date and several other info, that users liked ;-)

![uas2](https://cloud.githubusercontent.com/assets/4699449/25869332/3d974734-3500-11e7-927e-2590b1ddbe4c.png)

**Comment by ukdtom** [comment]
And additional info could be in an info popup box, if that is better designwise

**Comment by ukdtom** [comment]
Checked latest commit, and think we need like the info icon next to the title of the plugin, so users knows that they can click on it in order to expand.

Also do remember, that url's should be hyperlinks

**Comment by creoludifico** [comment]
Check latest commit

**Comment by ukdtom** [comment]
Still not seen counters been updated, unless I leave uas, and return again?

**Comment by creoludifico** [comment]
Quick refresh on this one?

**Comment by ukdtom** [comment]
Meaning?

And if I was unclear...
When installing a new bundle, the category menu to the right is not updated with it's counters

**Comment by ukdtom** [comment]
And working perfectly now
