### ISSUE TITLE
Extend PMS module getSection with title

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#311]
Yoyo tommy. Can you replace the letterKey with a search for title instead?
We are using lazy load (skip, take) so for us to have a decent search it has to be filtered on the same call.

/api/v3/pms/getSection/key/<Key of section>/start/<Item to start with>/size/<Amount of items to return>[/getSubs]/[letterKey/<First Letter in Title>]
---->
/api/v3/pms/getSection/key/<Key of section>/start/<Item to start with>/size/<Amount of items to return>[/getSubs]/[/filter?title=new]

Would be awesome ^^

**Comment by ukdtom** [comment]
Fixed with above commit.
Check the doc
