### ISSUE TITLE
500/Internal Server Error

### ISSUE THREAD

**Issue by Laim** [ukdtom/WebTools.bundle#312]
An error occured, please check the logs.

Errorinfo:
Requested URL: webtools2?module=git&function=getGit&url=https%3A%2F%2Fgithub.com%2Fjesperrasmussen%2FAdultDVDEmpire.bundle&branch=
Error Code/Message: 500/Internal Server Error

I'm getting this error when installing anything from the App Store, it installs successfully, but it throws this error out afterwards. 

Wasn't sure which logs you needed, so gave you them all.

I'm running the latest version of QTS 4.3.3.0154, Device: TS-469L.

[PMSLogs_20170507-233250.zip](https://github.com/ukdtom/WebTools.bundle/files/981990/PMSLogs_20170507-233250.zip)

**Comment by ukdtom** [comment]
Hopefully fixed now.
Try again, and if it still fails, do an "Force repo update"
