### ISSUE TITLE
Error starting framework core for WebTools.bundle

### ISSUE THREAD

**Issue by chinochao** [ukdtom/WebTools.bundle#316]
Hello,

I tried to install the plugin and it seems to giving me this error message

May 09 12:26:52 ccnet-plex01 systemd[1]: Starting Plex Media Server for Linux...
May 09 12:26:52 ccnet-plex01 systemd[1]: Started Plex Media Server for Linux.
May 09 12:26:57 ccnet-plex01 sh[21407]: Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/WebTools.bundle.

I did not see any issues in the logs.
[Plex Media Server Logs_2017-05-09_12-18-38.zip](https://github.com/ukdtom/WebTools.bundle/files/987455/Plex.Media.Server.Logs_2017-05-09_12-18-38.zip)

**Comment by ukdtom** [comment]
You have installed it in the wrong directory!

see the first post in the forums, or here: 
https://github.com/ukdtom/WebTools.bundle/wiki

**Comment by chinochao** [comment]
/usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/ is my Plug-ins directory. I have also installed CCLoudTV and IPTV in those directory and they work.


Per the instruction, it says to install it in the Plugins Directory.

**Comment by ukdtom** [comment]
> Per the instruction, it says to install it in the Plugins Directory.

Correct, but you installed it into the Plug-ins-995f1dead directory!

Read the Wiki!

**Comment by ukdtom** [comment]
Ohh....and forgot....

Not knowing your OS, but you are in the Resource directory, but should be in a Library directory.
