### ISSUE TITLE
Allow path usage

### ISSUE THREAD

**Issue by kyse** [ukdtom/WebTools.bundle#319]
I was messing around with trying to reduce the subdomains I'm using and trying out paths redirecting to the proper port needed.

I noticed when I hit the endpoint though the redirect to the login page is giving me the base domain:port/login path rather than honoring the subpath.  Ie plex.domain.com/webtools/ -> plex.domain.com/webtools/login.

Looks like code is doing a redirect with a fully built out url rather than returning ~/login.

**Comment by ukdtom** [comment]
Slated for V3

See: https://github.com/ukdtom/WebTools.bundle/issues/306

**Comment by ukdtom** [comment]
As well as: https://github.com/ukdtom/WebTools.bundle/issues/123
