### ISSUE TITLE
UAS V3 and unknown bundles

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#321]
If a bundle is unknown, and doesn't have a valid repo url, it should not show the invalid url in UAS, nor should the update button be enabled

**Comment by ukdtom** [comment]
`{
    "https://github.com/ukdtom/epg-dk.bundle": {
        "description": "Download automaticly an xmltv file from YouSee Denmark",
        "title": "epg-dk",
        "supporturl": "https://forums.plex.tv/discussion/248011",
        "bundle": "epg-dk.bundle",
        "branch": "master",
        "date": "2017-05-11 22:17:58",
        "identifier": "com.plexapp.plugins.epg-dk.bundle",
        "type": [
            "Application"
        ],
        "icon": "icon-epg-dk.png"
    },
    "https://github.com/jwsolve/Afdah.bundle": {
        "description": "",
        "title": "Afdah",
        "bundle": "Afdah.bundle",
        "CommitId": "55fb786bb9",
        "branch": "master",
        "date": "2017-06-13 23:43:27",
        "identifier": "com.plexapp.plugins.afdah",
        "type": [
            "Unknown"
        ],
        "icon": ""
    },
    "https://github.com/ukdtom/ExportTools.bundle": {
        "identifier": "com.plexapp.plugins.ExportTools",
        "description": "Will export selected sections into a CSV or xlsx file",
        "popupmsg": "This tool is a replacement for Plex2CSV. If Plex2CSV is installed, please uninstall it. To see further info, look here: https://github.com/ukdtom/ExportTools.bundle/wiki",
        "title": "ExportTools",
        "supporturl": "https://forums.plex.tv/discussion/254248",
        "manual": "https://github.com/ukdtom/ExportTools.bundle/wiki",
        "bundle": "ExportTools.bundle",
        "CommitId": 6604669,
        "release": "ExportTools.bundle.zip",
        "DeleteCacheDir": false,
        "branch": "ExportTools.bundle.zip_WTRELEASE",
        "date": "2017-06-05 15:51:52",
        "DeleteDataDir": false,
        "type": [
            "Application"
        ],
        "icon": "icon-exporttools.png"
    },
    "com.plexapp.plugins.pmsinfo": {
        "description": "",
        "title": "PMSInfo",
        "bundle": "PMSInfo.bundle",
        "branch": "",
        "date": "2016-12-15 20:38:05",
        "identifier": "com.plexapp.plugins.pmsinfo",
        "type": [
            "Unknown"
        ],
        "icon": ""
    }
}`

Above is the output from the git list endpoint

**Comment by ukdtom** [comment]
Almost there ;)

The one that is completely unknown, now has an invalid url for it's repo, when the bundle info is shown.
Instead it should not show a repo url at all

**Comment by creoludifico** [comment]
Oh i didnt see it was invalid.. guess i was too quick there ^.^ 
Well ready for test

**Comment by creoludifico** [comment]
com.plexapp.plugins.pmsinfo VS https://github.com/ukdtom/epg-dk.bundle

The only thing i can check for without using a really complex regex is "http"..

**Comment by ukdtom** [comment]
And perfect
