### ISSUE TITLE
UAS V3 and missing option

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#326]
We need a way to search for updates to already installed bundles.

V2 had this, and when clicked, will present user with a list of bundles, that are outdated, and next to each of them, an update button.
Also when presenting the list, an "update all" button

**Comment by ukdtom** [comment]
And endpoint already there, called getUpdateList

**Comment by ukdtom** [comment]
Will delay testing here, since I need to either create a test UAS repo, or await I update one of my installed ones.

**Comment by ukdtom** [comment]
After pressing update on the list, the updated bundle is not removed from the list?

**Comment by creoludifico** [comment]
Check commit.

And btw what is the easiest way to install an outdated app?

**Comment by ukdtom** [comment]
In our special secret debug file, you can set the UAS repo to any git you want, or to a special branch of it.
Set that, and then add a new test app to it.
After that's done, use UAS to download your test app
Then change a file on your UAS test app, in order to update the git commit id

**Comment by ukdtom** [comment]
And added you to the UASRES git as a Collaborator, so you can make your own branch if needed

**Comment by ukdtom** [comment]
Hmmm......Still not working!
Try this:
In your debug file, make sure you have the following:
{
	"WT_AUTH": false, 
	"JSONTIMESTAMP" : 1006578111,
	"UAS_Repo": "https://github.com/ukdtom/UAS2Res", 
	"UAS_RepoBranch" : "test",
	"UI" : {"Language" : "da", "debug" : true}
}

The UAS_Repo and UAS_RepoBranch part are the important here.
Then restart PMS, and install the Adult bundle named "Tommy UAS Test App"

It's located in the following git: https://github.com/ukdtom/UASTest.bundle, where you now have full rights

In above git, edit the file named Contents/Tommy-Work/kilroy

That would trigger an update

After the update is installed, it should disapear from the update list, and if the list is empty, the "Update Avail" to the right should also disapear

**Comment by ukdtom** [comment]
Hmmm......Updates now works, but the "Updates Avail" is still on after the updates has been installed.

A Ctrl-F5 fixes it though

**Comment by creoludifico** [comment]
And readyfortest

**Comment by ukdtom** [comment]
Perfect
