### ISSUE TITLE
GUI V3: Implement Playlists

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#331]
We should have this in V3 as well, so we beside a new GUI and bug fixes also add something new

**Comment by ukdtom** [comment]
Back-end miss import function, but the rest is there

**Comment by creoludifico** [comment]
Is the import function ready?

**Comment by ukdtom** [comment]
Nope, but the others are ready though, so don't let that stop you :)

**Comment by creoludifico** [comment]
Assign me when import is ready 😄

**Comment by ukdtom** [comment]
With above commit, the following is possible:

* Import PLaylist
  * Only if type is for Video or Show
  * Only for playlists exported by WebTools
  * Can import, even if playlist was exported on a different server

TODO for backend:
* Import as well for Audio and Pics, when exported from WebTools
* Import from 3.Party generated playlists


All of above needed, is purely back-end internal stuff, so front-end can now be completed....
See the Doc for details

**Comment by ukdtom** [comment]
And do go ahead here @creoludifico !!!!

The sooner the better, due to translators

**Comment by ukdtom** [comment]
3.Party import too complex to hold off release of V3, so moving to V3.1

@creoludifico All yours for now

**Comment by creoludifico** [comment]
Check check.

I could not upload any playlist myself. I wonder if it's a backend problem? You did not respond with any errors.

**Comment by ukdtom** [comment]
It's a backend problem :(

Whe backing out from importing 3.Party playlists, I broke import of our own....

Will fix in my end, and thanks

**Comment by ukdtom** [comment]
But when said....

Any chance of an import button, that will popup the dialog to select a file, instead of the current gui?

**Comment by creoludifico** [comment]
Sure, but why do you want a dialog?

**Comment by ukdtom** [comment]
To make it a tad more like the rest of the UI

**Comment by ukdtom** [comment]
Also please remember to translate all strings!

**Comment by creoludifico** [comment]
Are you sure we need a dialog? I think it's really nice as it is for now?

**Comment by ukdtom** [comment]
Cool
