### ISSUE TITLE
ToolTips for GUI V3

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#332]
When hovering an element on the page, a tooltip would be nice ;-)

Set for V3.0.0, but feel free to move to another milestone, or close at your discretion

**Comment by creoludifico** [comment]
I'm moving to V3.1 so i can focus on PL untill beta release

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
