### ISSUE TITLE
Redo the Wiki for V3

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#333]
When releasing V3, we need to redo the WIki

**Comment by ukdtom** [comment]
We wait until I give the go for it, since when starting, we break the current one :(

**Comment by trumpy81** [comment]
No problem Tommy. I have my pencil at the ready! ... lol

**Comment by ukdtom** [comment]
And for @creoludifico 

We are dropping the pdf based manual, and instead going for the Wiki up here, so you need to change your code as well.

Using an online Wiki, makes it easy for us to adjust on the fly, without having to release a new version of WebTools

**Comment by ukdtom** [comment]
Wiki directory created, to host screendumps

**Comment by ukdtom** [comment]
And we partially started here, in this git:
https://github.com/ukdtom/WT3Wiki

**Comment by ukdtom** [comment]
@trumpy81 

Note that the Sub upload functionallity added a new popup window for pure uploads, and also one if the media to upload towards, has multiple parts.
So maybe some update to the Wiki is needed?

**Comment by ukdtom** [comment]
Closing this...

Job well done @trumpy81 

Thanks
