### ISSUE TITLE
Localize Website

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#334]
Found this site, that seems to offer a free translation site for our project, if we change the license model though

https://poeditor.com

Already created a project up there, and as soon as @creoludifico tell's me his email addy, I'll add him as an administrator to it as well.

Think we should look into this ASAP, since it has a huge impact on how the web pages are designed

**Comment by ukdtom** [comment]
If we make englist as the first one, then others can come in gradually, as the community do the translation for us

**Comment by ukdtom** [comment]
Added a few tags to get us started here, as well as translated those into English
Added Danish as a language as well, but did leave some strings untranslated, so we can deal with that as well

**Comment by ukdtom** [comment]
And to use it all with Angular, check out this website:
https://angular-gettext.rocketeer.be/

**Comment by ukdtom** [comment]
This looks even more cool:
https://lostechies.com/gabrielschenker/2014/02/11/angularjspart-12-multi-language-support/

**Comment by ukdtom** [comment]
And done!
We now need a language selector, as well as some way to store it!
(Storing is my problem)
To display a list of avail languages, walk the file named: /http/static/_shared/translations.js

We also needs the following to that dialog:
"If your language is missing, or you want to improve on the translation of it, then please go here:
https://poeditor.com/join/project/8uRxEmAE4M"

**Comment by ukdtom** [comment]
Added more localization stuff to:
https://github.com/ukdtom/WebTools.bundle/commit/90e641b379d1b1214ac82e214660df2a72438f40

Look in the docs under "Debug", "Get the Secret Info" and "Localization"

**Comment by creoludifico** [comment]
Can we close this for now?
And then refer to #351
