### ISSUE TITLE
Issue with WT on Windows

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#337]
On some windows boxes, it errors out with an entry in the log file that it's installed in the wrong directory, even though it's not.

This is due to a mess-up with forward and backwards slash

Forum thread:
https://forums.plex.tv/discussion/comment/1478369/#Comment_1478369

**Comment by ukdtom** [comment]
Fixed with above commit

**Comment by sharkbit** [comment]
Checked #340 and that is not the issue.  The two vars point to different locations.  I.E. When checking for the Version file, Core.bundle_path actually exists, the other doesn't.  Below are my windows paths for the two vars. 

Core.app_support_path, Core.config.bundles_dir_name, BUNDLEDIRNAME = `'C:\Users\<user>\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\VERSION'`

Core.bundle_path = `'C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-313f93718\WebTools.bundle\VERSION'`
