### ISSUE TITLE
UAS: Add support for custom scanners

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#338]
Maybe time, that we look into adding support for custom scanners as well?
But not for V3, since we already got enough on our plate here

**Comment by psyciknz** [comment]
Related to this.  If I have a channel + agent + scanner.  And want them in UAS2.  Should i split them into their individual components to add to UAS?

**Comment by ukdtom** [comment]
Channel and Agent are supported, and can be in the same bundle if needed.
Custom Scanners, since they need to go into another directory, is not supported currently, but when I get to it, I'll go with a git named <MyScanner>.bundle, that has a directory in it named "Scanners", and then I'll search for that dir, and relocate it to the correct folder.

But when said, It's NOT slated for V3 of WebTools, since we have enough on our plate for that release already, since V3 is a complete rewrite, as well as a brand new module already

**Comment by psyciknz** [comment]
Thanks, so for my repo which does include a scanner, do I remove it? or can it exist there and be loaded to the users system, and adjustments can be made if and when UAS supports it?

**Comment by ukdtom** [comment]
Remove it, and ask users to add it manually for now

**Comment by psyciknz** [comment]
What about leaving it in the repo in a sub directory.  So it is on the system but wont do anything.  Would this be acceptable?
NextPVR.Bundle
    Contents
        Code
    Scanners
         Series
              NPVRXML

Type structure?

**Comment by ukdtom** [comment]
And just looked at your git.

For uas to support it, you'll need to rename the git to end with .bundle, as well as split it into two, since we can't handle two info.plist files nor two __init__.py files in a combined directory

Sorry

For a git structure, check out ExportTools
https://github.com/ukdtom/ExportTools.bundle

**Comment by psyciknz** [comment]
Sorry was just trying to redo that comment to make it readable.

Yeah I can fix all those issues, and it might make sense to split them any way, since they're distinct functions....ok I'll work that out and then figure out the UAS instructions.  Cheers.

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
