### ISSUE TITLE
FM - Ignored dirs not getting saved

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#339]
![image](https://user-images.githubusercontent.com/12425208/28502772-0d913f38-6ffa-11e7-99dc-d8d036e1096b.png)

The ignore hidden and ignore extra fields are working just fine.
Ignored dirs are not getting saved properly. 
I can see that it's successfully passed to the backend. Can you please check up on this?

**Comment by ukdtom** [comment]
You are having a payload of:
`IGNORE_DIRS`

Should be:
`IGNORED_DIRS`

Besides that, you are missing `VALID_EXTENSIONS` ;)

**Comment by creoludifico** [comment]
Damn thanks!
