### ISSUE TITLE
New install of WebTools on Windows: Wrong install Dir?

### ISSUE THREAD

**Issue by sharkbit** [ukdtom/WebTools.bundle#340]
Why are you using Core.app_support_path instead of Core.bundle_path?  After changing a few references to this, WebTools Started working for me.

I.E.  (.\WebTools.bundle\Contents\Code\consts.py) Line 59
`versionFile = Core.storage.join_path(Core.bundle_path, 'VERSION')`
 vice 
`versionFile = Core.storage.join_path(Core.app_support_path, Core.config.bundles_dir_name, BUNDLEDIRNAME, 'VERSION')`

I could post logs but they will just say "Cant find XYZ at: C:\Users\<user>\AppData\Local\Plex Media Server\..."

**Comment by ukdtom** [comment]
Hmmm....Interesting

And never new about that !
Will adopt this for the next version, thanks

**Comment by ukdtom** [comment]
Also check https://github.com/ukdtom/WebTools.bundle/issues/337

**Comment by sharkbit** [comment]
Reviewed 337, not the same issue.  What I see is that the wrong Var is being used.  I.E. Looking for the Version in consts.py Line 59

Core.app_support_path, Core.config.bundles_dir_name, BUNDLEDIRNAME, 'VERSION' = `'C:\Users\<USER>\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\VERSION'`

instead of the right path:
Core.bundle_path, 'VERSION' = `'C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-313f93718\WebTools.bundle\VERSION'`

**Comment by sharkbit** [comment]
To get the webpage to come up I had to modify consts.py & webSrv.py.  I would post them but the branches have different changed...  And I dont know which one you want?

**Comment by sharkbit** [comment]
With that pull request the website :33400 comes up!  
**But it in German?  Using Branch 'oliver-next-work'**

**Comment by ukdtom** [comment]
This path is wrong!
`Core.bundle_path, 'VERSION' = 'C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-313f93718\WebTools.bundle\VERSION'`

Above plugin dir is for Plex only bundles, that comes with PMS!
3.Party lives in: 
`'C:\Users\<USER>\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\VERSION'`

So guess my approach was correct after all ;)

**Comment by ukdtom** [comment]
And note, that dev for WT 2.x has stopped, and we are working on V3 here, where we among other stuff has translations....

When said, only PR's against the current DEV branch are accepted!

**Comment by sharkbit** [comment]
So on my box,  any plugin I put in `C:\Users\<USER>\AppData\Local\Plex Media Server\Plug-ins` dets deleted when plex starts

**Comment by ukdtom** [comment]
That's because you also have it below the Resource dir, IMHO

Please check, as well as PMS system log

**Comment by ukdtom** [comment]
And if in the Resource dir, delete it from there

**Comment by ukdtom** [comment]
And testing on OpenSuse, QNAP and Windows

**Comment by sharkbit** [comment]
since any plugin I put in `C:\Users\<USER>\AppData\Local\Plex Media Server\Plug-ins` Gets deleted where is the Right Plugin Folder?

**Comment by ukdtom** [comment]
`C:\Users\<USER>\AppData\Local\Plex Media Server\Plug-ins` is the correct folder!

What did your PMS system bundle log say, after a PMS restart?

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/pull/342 works, so I'll need to make this part of V3

**Comment by sharkbit** [comment]
...  Well after all that it's staying in the Plugin Folder,  I'm going to go bang my head against a wall....

**Comment by sharkbit** [comment]
Ohh,  so with my Changes It can Live in ether Dir!  Enjoy!

**Comment by ukdtom** [comment]
Nope....
You MUST stay out of plug.ins.XXXXXXX dir below the Resource dir!

That dir get's wacked with every PMS update!

Also, WT has hardcoded stuff, as well as other 3.Party plugins has, that specifically looks for the correct dir!

And that dir is below the Library dir!
