### ISSUE TITLE
GetUsers empty list received

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#345]
Hey

GetUsers returns an empty list.
Please merge with my branch, run webtools, open F12 and login.
You should hit a debugger in chrome which can display the value of users received. (I get none even tho i'm logged in)
![image](https://user-images.githubusercontent.com/12425208/28669108-1916b0b4-72d3-11e7-8ea8-0c156b09df07.png)

**Comment by ukdtom** [comment]
And you have either crated some users in your home, or shared a library with somebody?

**Comment by creoludifico** [comment]
![image](https://user-images.githubusercontent.com/12425208/28705891-1a2769f4-7372-11e7-8eba-41f330c5983e.png)
And i've shared my lib with 3 other users.
But if i'm logged into Webtools i should receive the user right?

**Comment by ukdtom** [comment]
Correct, as long as debug Auth is disabled

**Comment by ukdtom** [comment]
Care to upload wt logfile?

**Comment by ukdtom** [comment]
And with your newest commit, you are calling `GETUSERS` just after logon!

This is an expensive call, since it access external sites, and as such, should only be called when needed!
( Currently when  PlayLists are accessed )
