### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#346]
We need this ASAP, since Translators are requesting a build so they can see the relevant context

**Comment by creoludifico** [comment]
Check commit

**Comment by ukdtom** [comment]
Checked, and .....There's always an "and" ;)

The language list is listing all languages that PMS support, but should instead list avail translated languages....

As such, I've added a call to return that to you..

`/api/v3/wt/getLanguageList`

Check the doc in my newest commit for it

Also do note, that when changing languages, the left main menu isn't always updated, until I logon again?

**Comment by ukdtom** [comment]
Also, on the language selection page, it would be nice, if we could say something like:

https://github.com/ukdtom/WebTools.bundle/issues/334#issuecomment-317274325

**Comment by creoludifico** [comment]
I've fixed the langlist and the lang should now be updated immediately after changing lang.

I'm not sure what you want to do with the selection page? Is it styling? In the future i think i'll be the settings tab

**Comment by ukdtom** [comment]
Text to tell people to translate, if their language is missing ;)

**Comment by creoludifico** [comment]
Can you formulate the text?

**Comment by ukdtom** [comment]
Already did a few days ago ;-P

https://github.com/ukdtom/WebTools.bundle/issues/334#issuecomment-317274325

**Comment by creoludifico** [comment]
Better?

**Comment by ukdtom** [comment]
Perfect, thanks
