### ISSUE TITLE
Base URL & IP to bind to options

### ISSUE THREAD

**Issue by mattmac24** [ukdtom/WebTools.bundle#347]
Can the option please be added to choose a base url so that this can be used behind a reverse proxy.

Also can we choose the IP address that the WebTools web server binds to?

This would allow using a reverse proxy securely on a public facing server :)

**Comment by creoludifico** [comment]
Hi Mattmac24

As far as i know the IP is bound to the plex server. @ukdtom ?
It will however be possible to change the base url in WebTools V3.0 by clicking the settings icon for WebTools under channels in Plex.

**Comment by mattmac24** [comment]
Thanks for the reply creoludifico,

That makes sense about the IP being dictated by Plex, but hopefully it's possible.
Looking forward to V3 :)

**Comment by ukdtom** [comment]
Correct, that PMS controls which IP's we bind towards, since WebTools, even though it host it's own website, is still a channel under PMS.
