### ISSUE TITLE
UAS V3: make expanding lines more obvious

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#348]
Currently, there is an arrow indicating that an entry in the UAS can be expanded.
This is non-obvious. 
The placement of the arrow does not indicate the functionality it has.
![uas1_current](https://user-images.githubusercontent.com/10280992/28824772-f3fa44b8-76c3-11e7-861f-976ff7323ebe.jpg)

In my experience, an indicator for "expanding" an entry needs to be placed at the margin.

Some mockups, which I hope are indicating the "expand" functionality better: 

![uas2_mockup](https://user-images.githubusercontent.com/10280992/28824778-f94eda6e-76c3-11e7-8dd2-e60efeb5df4b.jpg)

![uas3_mockup](https://user-images.githubusercontent.com/10280992/28824780-fc399b24-76c3-11e7-8f1d-12af6d39ff2f.jpg)

![uas4_mockup](https://user-images.githubusercontent.com/10280992/28824783-fed5826c-76c3-11e7-9873-1720607bc72c.jpg)

**Comment by creoludifico** [comment]
Hi @OttoKerner 

Thanks a lot for this :smile:  
I'll look into it

**Comment by ukdtom** [comment]
Personally like the 3.dot version ;-)

**Comment by creoludifico** [comment]
I've tried the 3.dot version but it didn't feel like an expand function.
I chose the last version with some few modifications. Try check it out and feel free to recommend changes :sunglasses:

**Comment by creoludifico** [comment]
I still have a feeling that it needs some change :/

**Comment by ukdtom** [comment]
@OttoKerner Updated the translate branch so you can see it in action

@creoludifico Looks great to me

**Comment by ukdtom** [comment]
@OttoKerner ?????

**Comment by OttoKerner** [comment]
looking better now
(except that the 'upwards' arrow is now looking off-center from the circle)

**Comment by ukdtom** [comment]
That part I'll consider so much minor, due to what is left to fix before a release, so considering this one closed, but the comment above been moved to 3.1

**Comment by creoludifico** [comment]
I'll close this one for now

**Comment by ukdtom** [comment]
I reopen ;)

It's slated for 3.1, and don't want us to forget it, so simply ignore for now

**Comment by creoludifico** [comment]
New issue if necessary
