### ISSUE TITLE
First Run error

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#349]
First run errors out with an error, that says:

`Error occurred!
WebTools

Technical Info:
Url: api/v3/settings/getSettings/UILanguage
Location: Language
Error: languageService.loadLanguage - Setting not found`

Above due to wt_language is not pre-populated

Ignoring and continuing works, and setting is then set

**Comment by ukdtom** [comment]
Fixed with above commit

**Comment by rodrimay** [comment]
I have the same error and the code is exactly as you showed. Do you have another fix?

**Comment by ukdtom** [comment]
Which language are we talking about here?

And maybe #501
