### ISSUE TITLE
Update translations Live

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#350]
A new framework call is now avail, that allow users to update the translations for a language directly from the translation site.

Endpoint is like:
`/api/v3/wt/updateLanguage/lang/da`

See updated doc for `updateLanguage`

This is a must, since else, we have to release new versions every time a language is updated or added.

GUI should have a button named `Update` or siml. for each avail language, and should not be mixed with the already present language selection.

**Comment by creoludifico** [comment]
9689f7b4c7d556e414f918888a8adaa2fee73117 Go go

**Comment by ukdtom** [comment]
Perfect
