### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#351]
We need to add language tags to pages and js files
Both for regular text, the search as well as tooltips and help

- [x] Home
- [x] Sub Management
- [x] Logs
- [x] UAS
- [x] Find Media   (Scanning text)
- [x] Playlist
- [x] LogOff
- [x] Language
- [x] Theme
- [x] ChangeLog
- [x] Sidebar Menu
- [x] Logon Screen

This post can be edited do render the checkmarks when a page is done

**Comment by ukdtom** [comment]
Unchecked logs again due to #354

**Comment by ukdtom** [comment]
And checked again, since £354 is now fixed

**Comment by creoludifico** [comment]
FM should have been translated too so i've checked it

**Comment by ukdtom** [comment]
Untoggled logs again :(

Missed: "[!] ---------- MORE LINES AVAILABLE IN THE ORIGINAL FILE! If you want to view the rest of the file go download it ----------"

**Comment by ukdtom** [comment]
How do we translate the tool tip for the question mark in UAS module @creoludifico ?
And do note, that I did check in a few translations to that module, so merge before!

**Comment by creoludifico** [comment]
Done?

**Comment by ukdtom** [comment]
Not found by grunt

**Comment by ukdtom** [comment]
And done
