### ISSUE TITLE
Migrate regression

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#353]
In V2, after migrating in UAS, a dialog showed, telling people what bundles was migrated.

Migrate endpoint does return that list

**Comment by creoludifico** [comment]
Please test the commit and please paste a screenshot of it

**Comment by ukdtom** [comment]
![migrate](https://user-images.githubusercontent.com/4699449/28929134-94ae35ca-786f-11e7-851f-5726f182ebdf.png)

Perfect, thanks
