### ISSUE TITLE
logController.js and translate.getString

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#354]
Seems like my grunt can't extract your translate.getString statements from the js files :(

So we somehow need the statement to be like:
`var translated = gettextCatalog.getString("Hello");`
And then use the var for the statement

Source:
https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

**Comment by creoludifico** [comment]
Check now :smile:

**Comment by ukdtom** [comment]
Perfect as always ;)
