### ISSUE TITLE
UAS v3: counter for installed plugins is wrong after clicking manual update

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#357]
after clicking 'update' in the UAS (for an already installed plugin)
the counter for installed/total plugins from this category is incorrectly increased.
it should do that only upon a fresh installation, but not when an update is performed.

![after_update](https://user-images.githubusercontent.com/10280992/29041580-b9c10ad0-7bb3-11e7-8442-01b30af1560d.jpg)

**Comment by ukdtom** [comment]
Duplicated :(

**Comment by ukdtom** [comment]
Counters should not be computed from front end, IMHO, but always be based on the following endpoint:
`/api/v3/git/uasTypes`

**Comment by creoludifico** [comment]
R4Test

**Comment by ukdtom** [comment]
Seems okay for me...

@OttoKerner ?

**Comment by OttoKerner** [comment]
After the update has been performed, the number of 'available updates' should get **de**creased.
Otherwise, the user may believe that the update attempt was **not** successful.

Additionally, I feel that the 'update' button should read 're-install' instead of 'update'.
(At least after an update-check has been performed and it has been determined that the latest version of the bundle is already installed.)

**Comment by ukdtom** [comment]
Thoughts @creoludifico ?

**Comment by creoludifico** [comment]
Hello @OttoKerner and Tommy

This can probably be confusing for the user to manage without automatically checking for updates.
If we do not check for updates we will have the 'reinstall' button on all the installed bundles that exists and the user needs to click on check for updates to get an update button instead.

However, there are multiple soltutions for displaying whether a bundle has been installed/updated.
1) We can show a text somewhere on the element row
2) We can force element to be expanded so the user can see the details and the update date.
3) We can check for updates automatically when a user accesses the UAS (Then set all to 'reinstall' except the one that needs to be 'updated') - I guess this is an API call from backend towards github and that's is why we dont want it to run everytime a user accesses the UAS. @ukdtom ??

**Comment by ukdtom** [comment]
Correct....We do not want to do it every time, since it's a slow call, as well as we are very careful here not to bombard GitHub, since that's what killed the old UAS.

I think that option 1 would be the way to go

**Comment by OttoKerner** [comment]
And maybe additionally change the background color of the bundle to indicate a change.

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Installed a few plugins....
Now waits for some dev to update their work, in order to test

**Comment by ukdtom** [comment]
And working nicely
