### ISSUE TITLE
UAS v3 - Migrated App unable to update

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#359]
Not sure if this is an issue or not.

After migrating my existing Channels/Plugins into WT they appear to be blank and missing any relevant data and when attempting to update one of the migrated Plugins, I am confronted with the following error message.

![untitled-1](https://user-images.githubusercontent.com/12381786/29042050-b6bfe596-7bf8-11e7-949e-78cb6702c178.jpg)

**Comment by ukdtom** [comment]
Same as #358, so closing this on behalf of the other one
