### ISSUE TITLE
Logon screen and PMS not signed in

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#360]
If the PMS is not signed into plex.tv
(Settings/Server/Remote Access)

Then a call to the endpoint `/version` should return a setting like:
`"PlexTVOnline": false`

Above means, that we instead of doing an auth. towards plex.tv, instead logon towards a local user storage.

This functionality is missing from the Logon screen, meaning that users that runs their PMS without been signed into plex.tv, will not be able to logon to WT V3!

Please see the doc regarding Authentication

**Comment by creoludifico** [comment]
R4Test

**Comment by ukdtom** [comment]
And working as expected, thanks
