### ISSUE TITLE
playlists: filename extension should be m3u8 

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#365]
Currently, the filename extension of a downlaoded playlist is `SRT` 
A case of copy & paste error I guess.

This should be `.m3u` (or more correctly `.m3u8`, because the playlist file is UTF-8 encoded)

**Comment by ukdtom** [comment]
Huh....It's .m3u8 extention for me

Can you verify with another browser?

**Comment by ukdtom** [comment]
Just tested via TeamViewer for @trumpy81 , and downloaded playlist also had the extention .m3u8

**Comment by trumpy81** [comment]
I just tested it in FF 55.0.1 and the file has no extension at all. It worked OK in Chrome though.

I tested it in Chrome with WT on the PC again and it still adds the .m3u8 extension as it should.

I tried it in FF with WT on the Syno and noticed that it also does not provide the full playlist name if there are spaces in the name. 

EG: Playlist name = David Gilmour - About Face, but in FF it wants to download as David, with no extension etc.

And just a reminder, it fails when attempting to download smart playlists imported/added by iTunes.

**Comment by ukdtom** [comment]
So a FF issue perhaps...
@OttoKerner What browser did you use?

**Comment by ukdtom** [comment]
@OttoKerner and @trumpy81 

I've updated the translation build on Github with a potential fix, so if you guys could verify it would be nice

**Comment by trumpy81** [comment]
Tested with FF and WT on PC, No problem, full name and .m3u8 extension.
Tested with FF and WT on NAS,  No problem, full name and .m3u8 extension.

**Comment by ukdtom** [comment]
Thanks Andy.
Will close this for now then.
@OttoKerner Feel free to reopen, if still a problem

**Comment by OttoKerner** [comment]
I am using Firefox.
I seem to remember that I tested first the 'download of a subtitle' feature.
Maybe the filename extension got 'stuck' somehow?

Right now I cannot re-create this because the subtitle export doesn't work.

**Comment by ukdtom** [comment]
Ref #373

**Comment by ukdtom** [comment]
@OttoKerner Updated translate build with a fix for Sub downloads

**Comment by OttoKerner** [comment]
This appears to work correctly in the latest version.

**Comment by ukdtom** [comment]
Thanks for testing
