### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#369]
Maybe this would be nice somewhere in the App?

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2PUDZF8LK8MUC

With an image like:
https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif

And then in private DM, send me your PayPal info

**Comment by trumpy81** [comment]
👍

**Comment by ukdtom** [comment]
Maybe here: ref #364

**Comment by ukdtom** [comment]
And already in the Wiki ;)
https://github.com/ukdtom/WebTools.bundle/wiki/V3Home

**Comment by ukdtom** [comment]
Added Priority here, due to translators

**Comment by creoludifico** [comment]
Added under about us page

**Comment by ukdtom** [comment]
Super, and looks great
