### ISSUE TITLE
WTv3 - Issue with UAS element wrapping

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#372]
While I was trying to get some compact images for the help Wiki, I reduced the width of the browser window whilst viewing the UAS. Unfortunately, the various elements on the UAS page did not wrap very well as you can see in the attached image.

Not all buttons have wrapped and the search box overlaps some buttons. Description text is wrapped behind the title text and so on.

When you have the time, could you take a look at this please. :)

![untitled-1](https://user-images.githubusercontent.com/12381786/29258195-f43c5786-80fa-11e7-9122-b709945acc83.png)

**Comment by creoludifico** [comment]
Hi guys.
I've made some changes. Please have a look

**Comment by ukdtom** [comment]
Seems okay for me now....

@trumpy81 I updated the translate build for you to test

**Comment by trumpy81** [comment]
Thanks. I will download and check it out shortly. :)

**Comment by trumpy81** [comment]
Working very well. Well Done!! :)
