### ISSUE TITLE
Subs download broken

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#373]
Seems like there's a regression in subService.js, where $window.location is unknown, so for now, reverting it, and allows it to spawn a new tab in order to download

**Comment by ukdtom** [comment]
@creoludifico 

Might wanna take a peak at what I did

**Comment by creoludifico** [comment]
Window.open can/will be blocked by some browsers (Because it's a popup). I've changed it back to the correct window.location.
window.location.href = URL.

**Comment by ukdtom** [comment]
Perfect
