### ISSUE TITLE
Logon and translate

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#375]
Make an API call, that can return a translated string

Call would be something like `/api/v3/wt/lang/<LANG-CODE>/<STRING TO TRANSLATE>`

If we just call `/api/v3/wt/lang/<LANG-CODE>` we should return a json with all the strings for that language

**Comment by ukdtom** [comment]
Look up getTranslate in the doc

**Comment by creoludifico** [comment]
updateLanguage, getTranslate and getLanguageList needs to be available from login

**Comment by ukdtom** [comment]
/getTranslate can now be called without been authenticated.

See the doc

**Comment by creoludifico** [comment]
R4Test

**Comment by ukdtom** [comment]
Strings to translate never makes it to the translate template via grunt

**Comment by ukdtom** [comment]
Working now...

Do check the login.html page
