### ISSUE TITLE
Can't delete (Agent) subtitles Linux Server Plex

### ISSUE THREAD

**Issue by luckyzor** [ukdtom/WebTools.bundle#378]
Hi,
i'm having problems to delete agent subtitles:
{"readyState":4,"responseText":"Fatal error happened in delSub: bad argument type for built-in operation","status":500,"statusText":"Internal Server Error"}

Can you help me?

**Comment by ukdtom** [comment]
I need the WT log files in a zip, right after reproducing the error.
And what Linux flavor is it?

**Comment by luckyzor** [comment]
Hi, can't download the log files with webtools :/

Technical details:

Requested URL: /webtools2?module=logs&function=show&fileName=com.plexapp.plugins.WebTools.log&_=1503248163547
Error Code/Message: 500/Internal Server Error

I'm using one seedbox with Ubuntu.

**Comment by ukdtom** [comment]
I still need the zip of the logfile ;)

**Comment by luckyzor** [comment]
^

This is the error when i try to download the log file with webtools...

**Comment by luckyzor** [comment]
[com.plexapp.plugins.WebTools.zip](https://github.com/ukdtom/WebTools.bundle/files/1237214/com.plexapp.plugins.WebTools.zip)

Here the log file :)

**Comment by ukdtom** [comment]
Could you please try this yet to be released early Alpha version?
https://github.com/ukdtom/WebTools.bundle/archive/translate.zip

And then report back good or bad

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response.

Can be reopened if needed
