### ISSUE TITLE
UAS missing translation Tag

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#380]
We need to be able to translate the string "Updates available"

**Comment by ukdtom** [comment]
Made this a Prioritize, due to translators

**Comment by creoludifico** [comment]
Fixed

**Comment by ukdtom** [comment]
Not there yet.....

Translations are done, but not used ;(

**Comment by creoludifico** [comment]
Have a look again

**Comment by ukdtom** [comment]
No good :(

Grunt generated Template now contains a key named:

`
#: ../http/static/uas/uas.html:24
msgid "{[{uasModel.updateType.key}]}"
msgstr ""`

Above makes no sense for a translator!

**Comment by creoludifico** [comment]
R4Test

**Comment by ukdtom** [comment]
Perfect
