### ISSUE TITLE
Raspbian, This site can’t be reached when accessing 33400

### ISSUE THREAD

**Issue by ramkithepower** [ukdtom/WebTools.bundle#382]
## Environment
- **PMS Platform(s) OS**: Raspbian
- **PMS Version**: Version 1.8.1.4139 
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: I have installed plex media server in my raspberry pi with Raspbian. After installing the webtools.bundle and given permission I am not getting the unsupported channel webpage when i use 33400 port like this http://ipofmyraspberry:33400/web

**Comment by ukdtom** [comment]
First of all, it's `http://IP:33400`without the /web

Secondly, I need logs!

**Comment by ukdtom** [comment]
Ping

**Comment by ramkithepower** [comment]
Will send the logs today

**Comment by ukdtom** [comment]
Closed due to lack of response
