### ISSUE TITLE
UAS and delete of unknown bundle

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#387]
Is not updating GUI nor counters after it has been deleted...

Click away from UAS, and then back again to show correct works though
![uas-deleteunknown](https://user-images.githubusercontent.com/4699449/30183277-1ee7f1fc-941a-11e7-8ce2-8189659ac174.png)

**Comment by trumpy81** [comment]
Another similar issue is when you delete a channel in PMS and then come back to WebTools, the deleted channel still shows in WebTools and if you attempt to delete it in WebTools you are presented with an error message and it remains in the list of installed channels.

![untitled-1](https://user-images.githubusercontent.com/12381786/30355723-83478c0e-9878-11e7-8971-31b48d81376c.png)

You have to close/reload WebTools before it is updated and the offending channel is removed.

**Comment by creoludifico** [comment]
R4T

**Comment by ukdtom** [comment]
Works for me....
@trumpy81 ???

**Comment by trumpy81** [comment]
You're not holding your tongue right Tommy ... lol, still an issue here.

Try this, install a plugin using WT, then go to Plex and delete that plugin using Plex, then go back to WT and refresh the browser page, the plugin will still be showing as installed and if you click on delete in the UAS it will show that error.

**Comment by creoludifico** [comment]
Hi @trumpy81 
I'm pretty sure that's another issue. Nevertheless i've not fixed what you indicate (and i probably can't)
Sound like a backend issue 😄 

@ukdtom Any comments?

**Comment by trumpy81** [comment]
Yeah ... it's that bloody Tommy again ... lol :p

**Comment by ukdtom** [comment]
Nobody can!

Either use WebTools to manage it, or not.
We can't track what you do outside of WebTools.
To get rid of such a bundle, in WT, select update, and after that, remove from within WT.

And this was/is also an issue for WT V2

**Comment by ukdtom** [comment]
But @trumpy81 

You could create a GHI asking for migrate to also delete stuff no longer present, if needed ;)
But too late for V3.0
