### ISSUE TITLE
Subs and paging

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#391]
Just so we don't forget this ;)

**Comment by trumpy81** [comment]
Currently, if you expand library and search, then collapse that library, the search term cannot be cleared. We could use a clear search button as well. :)

**Comment by creoludifico** [comment]
Paging has been added to the sub module in the latest commit.
Please check it out.

Btw @ukdtom you do not support searching and letter paging.
api/v3/pms/getSection/key/4/start/0/size/20/getSubs/title/testsearchstring/letterKey/B
Letter paging "B" will override the search "testsearchstring" and therefore return all the content in B not filtered by search.

I see two possible solutions.
1) We disable the search for all sections that has choosen a letter to filter from. Furthermore we tell the user that searching is disabled while paging with letters.
2) You make the API support both searching and letter paging. This requires that 'getSectionLetterList' also gets updated so it will return a new size of each letter and whenever the letter shall be visible again.

**Comment by ukdtom** [comment]
4 now, let's go with option 1, and postpone the API change to maybe 3.1, since I have enough on my plate for now

**Comment by ukdtom** [comment]
And paging works perfectly ;)

**Comment by creoludifico** [comment]
I'll make solution 1 for now.

For solution 2 refering to #400

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Get more stopped working :(

**Comment by ukdtom** [comment]
Disregard....

Working perfectly
