### ISSUE TITLE
WTv3 - Synology - Playlists does not show all users in drop down menu

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#392]
## Environment
- **PMS Platform(s) OS**: DSM 6.1.3-15152 Update 4
- **PMS Version**: Version 1.8.4.4249
- **Name of Browser**: FireFox 55.0.3 64Bit, Chrome 61.0.3163.79 (Official Build) (64-bit), Microsoft Edge 38.14393.1066.0

## Error shown
After loading WebTools and signing in, click on the Playlists button and then click on 'Select user'. Only two users appear, -self- and one other user out of three available users, including -self-.
Same Behaviour when clicking on 'Select target user'

## Steps to reproduce
Reload WebTools

## Expected behaviour
Show all available users

## Actual behaviour
Shows 2 out of 3 users

## Additional Info
No problem showing all users in Windows install of WTv3.

WT Logs here: [WT Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1290265/WT.Logs.zip)
PMS Logs here: [Plex Media Server Logs_2017-09-10_14-31-01.zip](https://github.com/ukdtom/WebTools.bundle/files/1290267/Plex.Media.Server.Logs_2017-09-10_14-31-01.zip)

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
What does the following show?

https://plex.tv/api/servers/aadf13ac602f2305a20737e03f57be637583f45e/shared_servers

/T

**Comment by trumpy81** [comment]
That link returns this:

`<MediaContainer friendlyName="myPlex" identifier="com.plexapp.plugins.myplex" machineIdentifier="e7baf73d0a959129d1636a257ae2adc4f3df2d39" size="1"><SharedServer id="5008209" username="maxflix" email="max.greenblatt@gmail.com" userID="30364" accessToken="iAvrMu8Vo1BrK5J5DxPE" name="DiskStation" acceptedAt="1481575013" invitedAt="1481574940" allowSync="0" allowCameraUpload="0" allowChannels="0" owned="1" allLibraries="1" filterAll="" filterMovies="" filterMusic="" filterPhotos="" filterTelevision=""><Section id="22203251" key="4" title="Bonus Material" type="movie" shared="1"/><Section id="22203252" key="8" title="Documentaries" type="movie" shared="1"/><Section id="22203253" key="5" title="Motorcycle - How To" type="movie" shared="1"/><Section id="22203254" key="36" title="Movies" type="movie" shared="1"/><Section id="27791604" key="57" title="Movies 4K" type="movie" shared="1"/><Section id="22203255" key="35" title="Movies Plus" type="movie" shared="1"/><Section id="22203256" key="11" title="My Photos" type="photo" shared="1"/><Section id="22599719" key="55" title="Pink Floyd" type="artist" shared="1"/><Section id="22203257" key="37" title="Premium - Albums" type="artist" shared="1"/><Section id="30666766" key="61" title="Premium - Singles" type="artist" shared="1"/><Section id="22203259" key="39" title="Premium - Various" type="artist" shared="1"/><Section id="22203260" key="9" title="Stand Up" type="movie" shared="1"/><Section id="22203262" key="31" title="TV Series" type="show" shared="1"/></SharedServer></MediaContainer>`

If it means anything, the missing server/s are shared by OttoKerner.
I have three shares from him:

1. Cloud Sync
2. StrE
3. ZZ Plex Cloud

**Comment by ukdtom** [comment]
It means something ;)

WT only support servers you own !
You are not allowed to pull user info from his server, since you are not the owner!

**Comment by ukdtom** [comment]
And when said, asked Otto for those shares, since puzzled about why you ever had those as part of WebTools!

I fear one of two:

* My bad code (Most likely)
* Plex security issue!

**Comment by trumpy81** [comment]
So why does it do that for Windows?

On Windows I can see Otto and Max and I can select them as target users in Playlists, but I can only see and select Max if I am using WT on the Syno?

**Comment by OttoKerner** [comment]
Because you did not share your Syno with me. Hence I do not exist as user on your Syno.
You did share your Windows box with me, so I am there as a target user.

**Comment by trumpy81** [comment]
Umm ... I think you may be right Otto ... Doh!!

I forgot that I only share the Windows PC with you, because the Syno is a little slow and I use PMS on it more than PMS on the PC.

**Comment by ukdtom** [comment]
So okay to close here?

**Comment by trumpy81** [comment]
Yeah sure ... my bad ... sorry Tommy :(

**Comment by ukdtom** [comment]
NP, but you did have me scared here for a moment ;)
