### ISSUE TITLE
RFE: Logs refresh

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#393]
Make a refresh/reload button for when viewing the logs

**Comment by ukdtom** [comment]
Also....

if viewing like:
`com.plexapp.plugins.WebTools.log.4`

Then a button at the end, saying jump to 
`com.plexapp.plugins.WebTools.log.3`

That way, the user can quickly jump to the next log file he/she is watching

**Comment by trumpy81** [comment]
I would like to add a request for a clear search button also when viewing logs.

Currently, if you expand a library and search in that library, then collapse that library in WT, the search term cannot be cleared.

**Comment by ukdtom** [comment]
Nice work, but would it also be possible to get a "Jump to top" button as Andy requested?

**Comment by creoludifico** [comment]
So a button just like the one that exist in the search menu?

**Comment by ukdtom** [comment]
Yep ;)

**Comment by creoludifico** [comment]
Hmm i would rather make a dragable search menu then duplicate buttons 😄

**Comment by ukdtom** [comment]
Well, as long as it's always on the screen, so that when you scroll to the bottom, then it's still present

**Comment by creoludifico** [comment]
The search menu should already always be present at the upper right corner even if you scroll down?

**Comment by ukdtom** [comment]
That would be perfect, and I'm sure it's possible for a magic http wizard like you :D

**Comment by creoludifico** [comment]
But but but.. It should already be fixated to the upper right corner 😮

**Comment by creoludifico** [comment]
![image](https://user-images.githubusercontent.com/12425208/30498564-84ffbd7e-9a57-11e7-9ef9-9deb72e4d0d2.png)

**Comment by creoludifico** [comment]
![image](https://user-images.githubusercontent.com/12425208/30498650-c7780918-9a57-11e7-8be7-395177b4419b.png)

**Comment by ukdtom** [comment]
Crawling back into my cave here ;)
