### ISSUE TITLE
Logs v3 - Error displaying some PMS log files

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#394]
## Environment
- **PMS Platform(s) OS**:  Windows 10 Pro 64bit
- **PMS Version**: 1.9.0 special build
- **Name of Browser**: All browsers

## Error shown
- **Symptom**: 
When viewing the Plex Media Server.log file, line number 329 is blank and only partial information is shown on other lines. The information alternates on different lines and is incomplete for all lines up to line 352 where the display of the file ends.

No warning is shown to open the file in a text editor.

## Steps to reproduce
1. Read the log file attached

## Expected behaviour
1. To read to the end of the file.

## Actual behaviour
1. As described above.

## Additional Info
Observed in Chrome, Edge and FireFox.

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

Log file being viewed: [Plex Media Server.log.zip](https://github.com/ukdtom/WebTools.bundle/files/1295616/Plex.Media.Server.log.zip)

Screenshot of issue: ![untitled-1](https://user-images.githubusercontent.com/12381786/30321554-d8457902-97f9-11e7-94a2-a01c6d71303e.png)

**Comment by ukdtom** [comment]
Log entries in the log is:

`Sep 12, 2017 19:55:19.443 [4300] DEBUG - EventSource: Failure in ParseHeader: HTTP/1.1 404 Not Found

Content-Type: text/html; charset=utf-8

Date: Tue, 12 Sep 2017 09:55:19 GMT

Server: nginx

Vary: Origin

X-Request-Id: 2c71d209-9da3-4c83-9ca7-2fcca42a207d

X-Runtime: 0.003206

Content-Length: 1118

Connection: keep-alive



<!DOCTYPE html>
<html>
<head>`

So we are showing it as it is!

When that's said, I suggest you ask Plex why they log such an entry

**Comment by trumpy81** [comment]
No, you are missing the rest of the file. It abruptly ends at the HTML tag and only shows those few lines before it.

I have no idea why Plex adds that to the log, I don't even see any issues when that is logged, so it seems rather pointless to me.

**Comment by ukdtom** [comment]
Sorry, but we phrase what's in the logs....
In order to color it etc....

So if Plex due to a bug suddenly drops html code in the log, we can't do anything about that

**Comment by ukdtom** [comment]
Actually, I've reopened this one....

@creoludifico 

Frontend have an issue here, and tries to get:

http://PMS:33400/assets/errors.css

**Comment by creoludifico** [comment]
@ukdtom 
Yes, that is exactly what we don't want (Javascript/Html rendering from the logs). I'll check

**Comment by ukdtom** [comment]
Perfect
