### ISSUE TITLE
link for 'folding in' a bundle in UAS is shifted after updating a single bundle

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#395]
## Environment
- **PMS Platform(s) OS**: Windows 10
- **PMS Version**: 1.9.1
- **Name of Browser**: Firefox 55.0.3 (x64)

## Error shown
- **Symptom**: 
The link that should be over the 'arrow up' icon is higher, about where the arrow was when the bundle was not folded out.

## Steps to reproduce
1. check for available updates
2. go to 'all' bundles
3. Update one bundle that shows an available update
4. fold it out after updating it

## Expected behaviour
The user should have to click on the 'Arrow Up' icon to 'fold in' the bundle

## Actual behaviour
The 'Arrow Up' cannot be clicked. Instead one has to move the mose upwards, to the position where the 'Arrow Down' icon was, before the bundle was expanded/folded out.

![unbenannt-1](https://user-images.githubusercontent.com/10280992/30494213-84252e12-9a47-11e7-8318-2e2d87c334ca.jpg)

**Comment by OttoKerner** [comment]
Additional observations:
The link is actually there, but it is only 1 pixel high. I have to focus the mouse exactly over the lowest point of the circle.
I don't know whether this is important, but the Export Tools bundle is permanently indicated as having an update available for me.

**Comment by creoludifico** [comment]
The button has now been fixed.
I'll look into the permanently update available thing

**Comment by creoludifico** [comment]
I'll close this one.
For the update available thing i refer to #396

**Comment by creoludifico** [comment]
Sorry will repopen untill button has been testet and confirmed

**Comment by OttoKerner** [comment]
Issue appears to be resolved.
