### ISSUE TITLE
idx codec in subs

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#397]
If a movie has a sub, and it's codec is "idx", we show an option to view it.

This is wrong, since we only should not allow viewing of that type of codec, since we can't produce a propper output

**Comment by ukdtom** [comment]
Only supported codecs are: `srt` and `subrip`

/T

**Comment by OttoKerner** [comment]
Consider displaying any type of text-based subtitle. If Plex understands it, then you should too.
Even ASS/SSA subs shoudl be possible - even if they contain a lot of formatting instructions, but they are still basically text files.

**Comment by ukdtom** [comment]
True, and I stand corrected here regarding ASS/SSA

**Comment by ukdtom** [comment]
As well as VTT ;)

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Care to test @OttoKerner ?

**Comment by OttoKerner** [comment]
It doesn't look like it allows viewing of `.smi` or `.ass` subtitles

![subs_look](https://user-images.githubusercontent.com/10280992/33454925-af4a527a-d61a-11e7-9348-40b5ce061bbd.png)

**Comment by ukdtom** [comment]
@creoludifico Back to you, and sorry....

And to test, simply take a text file, and name it with moviename.<ext to test>
Then refresh PMS

**Comment by creoludifico** [comment]
smi and ass added

**Comment by ukdtom** [comment]
@OttoKerner ?

**Comment by ukdtom** [comment]
And disregards @OttoKerner 

Tested, and found sadly a bug, caused by PMS trying to be smart here....

**Comment by ukdtom** [comment]
Ref: https://www.matroska.org/technical/specs/subtitles/ssa.html

**Comment by ukdtom** [comment]
And tested, works fine now, so closing here
