### ISSUE TITLE
API getSection - Searching & Letter paging

### ISSUE THREAD

**Issue by creoludifico** [ukdtom/WebTools.bundle#400]
api/v3/pms/getSection/key/4/start/0/size/20/getSubs/title/testsearchstring/letterKey/B
Letter paging "B" will override the search "testsearchstring" and therefore return all the content in B not filtered by search.

The API needs to support both searching and letter paging. This requires that 'getSectionLetterList' also gets updated so it will return a new size of each letter and whenever the letter shall be visible again.

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
