### ISSUE TITLE
Subs: the 'Letter' filter should have 'All' or 'no filter' instead of just a blank space

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#401]
I am talking about this dropdown menu.

![no_filter](https://user-images.githubusercontent.com/10280992/30517179-72ab76da-9b57-11e7-96db-41389dd5e1de.png)

When you want to go back to an 'unfiltered' view, the dropdown should offer an option 'All' or 'no filter' or 'unfiltered' as its first item - not just a blank space.

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Perfect
