### ISSUE TITLE
Missing filter regression

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#403]
In WT2, there was a checkbox, so UAS only showed installed channels.
WT3 is missing that

Ref: https://webtools4plex.slack.com/archives/G6D2P4A84/p1505781645000171

**Comment by JamminR** [comment]
To be clear, UAS3 doesn't necessarily have to be a 'checkbox' as in old.
I wouldn't mind a "Installed" filter menu item over on the right hand side in the category menu to end up with same result - showing only the installed plugins.

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Fail to see this....Guess I'm blind here

**Comment by creoludifico** [comment]
@ukdtom 
Is it possible for you to fix this?

You could return the type "Installed" for the menu and include the type on each repo that is installed. 
This should automatically be adapted in the frontend

**Comment by ukdtom** [comment]
Huh....You already color them differently, and guess based on data missing or not?

But fastest is to call git/list, that only returns installed bundles

**Comment by creoludifico** [comment]
Oh fine

**Comment by creoludifico** [comment]
Now it's here

**Comment by ukdtom** [comment]
And indeed it is
