### ISSUE TITLE
[feature idea] refresh Sort Title according to the current advanced server preference

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#406]
There are some users who don't like Plex to strip articles from the titles of their media to build the 'Sort Title'.

![sort_title2](https://user-images.githubusercontent.com/10280992/31046970-93d144f6-a602-11e7-817b-366c2d1a4690.png)

Of course when they realize that this can be influenced by the [advanced server preference](https://support.plex.tv/hc/en-us/articles/201105343-Advanced-Hidden-Server-Settings) `ArticleStrings`, they have already built their library. 

And changing this hidden preference doesn't retroactively affect _existing_ items, but only newly added ones.

So I propose a feature which re-generates the Sort Titles from the regular Titles. 
While doing so, it takes the current server `ArticleStrings` preference into account.

A more advanced version of the feature would also allow users to change the server preference itself via the GUI.

see https://forums.plex.tv/discussion/comment/1154765/#Comment_1154765 

set server preferences per URL API:
`http://127.0.0.1:32400/:/prefs/set?ArticleStrings=the,das,der,a,an,el&X-Plex-Token=xxxx`

**Comment by OttoKerner** [comment]
Caveat: There must be s stern warning, that this overwrites all 'Sort Titles'.
If a user has manually edited them (for instance to group movies), he might want to know the consequences ;-)

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
