### ISSUE TITLE
UAS: Last Updated time for individual plugins

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#408]
Since a lot of plugins get's abandon,I was thinking about an additional GIT, that would hold last updated time for all the gits in the UAS....

We could make a scheduled job, that would walk all the gits, retrieve the last updated timestamp, and store that in like a gist or a regular git.

Then make UAS fetch that as well, show the date, and if like older than 1 year, flag it as red

Regardless, so far just a thought, but maybe something for V3.1

**Comment by ukdtom** [comment]
Could also be used to categorize Gits in like:
* New
* Last month

**Comment by ukdtom** [comment]
Note to self....

Scheduled task in Jenkins

**Comment by trumpy81** [comment]
If you open the UAS and then click on Installed (in the category menu on the right) it will reveal a list of apps that you have installed. If you then click on the down arrow (just below the update button) for one of those installed apps, it will reveal when the app was last updated.

**Comment by deusxanime** [comment]
Ah great thanks I missed the expansion arrow.

Initially I was a bit confused if that "Last Updated" was the last time I did an Update or the last time the repo was updated. But upon testing it looks to be the last time I did the Update. Not sure if there is a way to clarify that better at a glance.

I believe on the old WebTools you could also have it check the last time the repo was updated so you could compare too though? Is that still an option?

**Comment by trumpy81** [comment]
Yes, you could check to see when a repo was last updated in the old version of WebTools, but that is not available any longer for a number of reasons.

I believe WebTools reports the last time a plug-in was updated, but it also alerts you to any updates pending for your installed plug-ins.

A message is displayed in the category selector when an update is available for your installed plug-ins.

See the wiki page I posted earlier.

**Comment by deusxanime** [comment]
Was headed off to bed when I replied last so didn't get a chance to read through the whole wiki page. Thanks again!

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
