### ISSUE TITLE
wrong icon used for 'Abort'

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#409]
I feel the meaning of this icon is rather 'revert' or 'reset' than 'abort'
I think a simple `×` might be more suitable here

![wrong_icon](https://user-images.githubusercontent.com/10280992/31318329-b475e29e-ac50-11e7-96d7-c137beb8e9ad.gif)

**Comment by ukdtom** [comment]
Agreed

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Nice
