### ISSUE TITLE
[FindMedia] reports files in a 'Personal Media' section

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#410]
When a library uses the 'Personal Media' agent, FindUnmatched reports files in it as unmatched.
This might be confusing for users and might provoke support questions. And who needs more of those? ;-)

I think when a library uses 'Personal Media' we should at least add a little explanation that this is just as expected.

Or we should consider adding a remark on the listed files.
Because:
there are 2 different sorts of unmatched files: 
- Personal Media (agent: `com.plexapp.agents.none`)
- unmatched files (agent: `local` )

The user might want to know about the latter, but maybe not about the former - because he probably designated them willfully as Personal media.

As I dive deeper in this phenomenon, I notice that only _some_ files from my test library are listed as 'unmatched'.
I have also a few 'fake' files in there, which I matched manually to the Plex movie agent. Yet, they are listed as unmatched.
This indicates that there are other criteria apart from the 'agent', why the module lists a file as unmatched. (file size perhaps?)
In this case, we might want to indicate _why_ a file appears in the list. 

This would both educate users and enable them to make a better decision what to do.

**Comment by ukdtom** [comment]
@OttoKerner 

Having a hard time reproduce here :(

Can you please try out the latest translate build, and if still so, add STR (Steps to Reproduce)

**Comment by OttoKerner** [comment]
Well, in the current PMS version I cannot reproduce the issue either.
Something must've changed in the meantime.

So let's close this for now.
