### ISSUE TITLE
Delete playlist too aggresive

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#411]
We need a confirmation box here, since we are deleting stuff

**Comment by ukdtom** [comment]
Maybe for subs as well ;)

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Seems fine

**Comment by ukdtom** [comment]
![hard to translate](https://user-images.githubusercontent.com/4699449/33340615-dfa5c624-d47c-11e7-80b3-aa3935d64dec.png)

Not that easy to translate ;)

**Comment by creoludifico** [comment]
Again :)

**Comment by creoludifico** [comment]
Could you test this again

**Comment by ukdtom** [comment]
Done, and perfect
