### ISSUE TITLE
Subs delete

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#415]
If you delete a sub, the correct sub is deleted, and then the GUI refresh.

But sadly, if looking at a movie with: Sub0, Sub1, Sub2, Sub3, and you delete Sub1, then GUI after the refresh shows Sub0 was removed.

Leaving sub module, and then re-enter, shows corrects subs though, so suspect, that the refresh routine forgot that the array starts with pos. 0, and not 1?

**Comment by ukdtom** [comment]
Ref: #330

**Comment by creoludifico** [comment]
Fixed

**Comment by ukdtom** [comment]
Indeed
