### ISSUE TITLE
Subs upload and translations

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#416]
Missing translations in the dialog for:

* "Choose file" button
* Label stating the file selected
* Upload button

**Comment by ukdtom** [comment]
Ref: #330

**Comment by creoludifico** [comment]
The choose file button and label stating the file selected is depending on the browser. I've added the upload btn to translate

**Comment by ukdtom** [comment]
Perfect...

And browser based?

**Comment by creoludifico** [comment]
https://stackoverflow.com/questions/5138719/change-default-text-in-input-type-file

**Comment by ukdtom** [comment]
Says:

`<div>
  <label for="files" class="btn">Select Image</label>
  <input id="files" style="visibility:hidden;" type="file">
</div>`

**Comment by creoludifico** [comment]
Lets go :-) r4t

**Comment by ukdtom** [comment]
Perfect
