### ISSUE TITLE
Main menu collapse/expand

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#417]
As we keep adding tools, I do think it would be a good idea, if the main menu items named "Options" and "Help" was not expanded by default

**Comment by creoludifico** [comment]
So you think like a vertical collapse/expand too?

**Comment by ukdtom** [comment]
Yes, but slated for 3.1.0 :)

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
