### ISSUE TITLE
New Module: Info

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#421]
Make a new module, that reports a few technical information's

Do a CopyCat from:
https://github.com/ukdtom/PMSInfo.bundle

**Comment by ukdtom** [comment]
@creoludifico 

Such a low hanging fruit here, so maybe for V3.0.0 anyway?
If not simply move to V3.1.0

But in esssens, new module named "TechInfo"

Simply call `/api/v3/techinfo/getInfo` with a get, and present the json output

See doc for more info

**Comment by creoludifico** [comment]
Check check

**Comment by ukdtom** [comment]
Works like a charm, thanks ;)
