### ISSUE TITLE
[idea] Get list of failed Optimised Versions

### ISSUE THREAD

**Issue by Rycochet** [ukdtom/WebTools.bundle#422]
When pre-transcoding your library, especially when it's a large one, being told that you have a dozen failed items out of tens of thousands of files, with a completely useless UI in the infinite scrolling list of all items - makes it almost impossible to identify which files need to be re-ripped (or downloaded etc).

Being able to get a list of files that have failed to encode without having to go through that entire list would be very useful (in my case, 19 fails out of 63,717 files).

**Comment by ukdtom** [comment]
Sadly, that info is not avail from the API :(

So nothing that can be implemented currently

**Comment by Rycochet** [comment]
Doh, that's annoying - crossing fingers it gets added, and at least there's an issue about the transcoder for people searching :-)
