### ISSUE TITLE
[TechInfo] token warning doesn't use translated string

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#424]
This string which appears under the line with the Plex Token in the `TechInfo` module, does not use the translated string from poeditor.com
`PLEXTOKEN Warning ********* | DO NOT SHARE THIS IN ANY PUBLIC WEBSITE!!!`

![unbenannt-1](https://user-images.githubusercontent.com/10280992/32405661-ed51abec-c169-11e7-9934-de9eb6250c14.png)

**Comment by ukdtom** [comment]
Fixed with a new translate build.
Thanks for spotting it.
Sadly caused a new string to translate though :(
