### ISSUE TITLE
No login form

### ISSUE THREAD

**Issue by MartialSeron** [ukdtom/WebTools.bundle#425]
## Environment
- **PMS Platform(s) OS**: Windows 10 x64
- **PMS Version**: 1.9.4.4325
- **Name of Browser**: Chrome + Firefox + Edge

## Error shown
- **Symptom**: Can't log in because logon screen only shows an empty "Welcome box"

## Steps to reproduce
1. Go to http://127.0.0.1:11282 (I set the port in PMS but it's the same with the default port)

## Expected behaviour
1. Functional logon screen

## Actual behaviour
1. Logon screen without log in form

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
[Plex Media Server Logs_2017-11-06_23-11-55.zip](https://github.com/ukdtom/WebTools.bundle/files/1448001/Plex.Media.Server.Logs_2017-11-06_23-11-55.zip)
[com.plexapp.plugins.WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/1448002/com.plexapp.plugins.WebTools.log)

- [x] Included screenshots (where appropriate)
![clipboard02](https://user-images.githubusercontent.com/5698488/32467524-3396cfb4-c34b-11e7-9fdf-396259a4e3c9.jpg)

- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Sadly, the logs you provided, was the default ones from PMS, that doesn't include 3.Party channels, like WebTools :(

Please go here:

https://github.com/ukdtom/WebTools.bundle/wiki/FAQ

And then look at Q3

**Comment by MartialSeron** [comment]
Are you sure ? 
Did you see the "com.plexapp.plugins.WebTools.log" file ?

Otherwise I will upload the complete directory this evening. I'm not at home.

**Comment by ukdtom** [comment]
Sorry, and you are correct here. it was a separate one  ;)

On the server itself, open up a browser, and go to

http://127.0.0.1:32400/identity

Does that show an xml file?

Since the WebTools log claims it can't open it

**Comment by ukdtom** [comment]
And it's also seen in the system log!

`2017-11-06 23:00:38,714 (44b0) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400'
2017-11-06 23:00:38,714 (44b0) :  WARNING (core:541) - Unable to retrieve the machine identifier or server version.
`

As such, not a WebTools issue, but something on your windows box blocking access!

So....
* Any Antivira/http inspection tool running?
* Are you running IP V6 only?

/T

**Comment by MartialSeron** [comment]
Thank you for your answers.
Actually, it appears that I have to launch PMS as admin.
Now it works
