### ISSUE TITLE
Add ability to mass-delete subtitles

### ISSUE THREAD

**Issue by brossow** [ukdtom/WebTools.bundle#431]
Please consider adding a feature to mass-delete subtitles for an entire series.  I can envision a couple variations:

1. delete everything (easy way to get a fresh start)
2. delete all except the one currently selected (if any)

For example, I have 21 seasons (280+ episodes) of South Park, and somehow each episode has about a dozen copies of the same subtitles. Instead of having to delete them one episode at a time, I would much rather be able to wipe them all out at once (especially if I could wipe out all except the currently selected ones).

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
