### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by hyperdallas** [ukdtom/WebTools.bundle#432]
## Environment
- **PMS Platform(s) OS**:  Windows 2016 
- **PMS Version**:  1.9.6.4429-23901a099
- **Name of Browser**:  Firefox

## Error shown
- **Symptom**:  Cannot login to webtools. invalid credentials. 

## Steps to reproduce
1.  uninstalled PMS, rebooted.  Reinstalled PMS, rebooted. Accessed web tools GUI, entered PLEX creds, auth failed. Rebooted server again, restarted PMS and Accessed web tools GUI, entered PLEX creds, auth still failed. 

## Expected behaviour
1. login

## Actual behaviour
1. auth failed

## Checklist
- [X] Listed environment
- [X] Included PMS log zip and WebTools log
- [X] Included screenshots (where appropriate)
- [X] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Missing logs

**Comment by ukdtom** [comment]
See https://github.com/ukdtom/WebTools.bundle/wiki/FAQ#Q3

**Comment by hyperdallas** [comment]
I completely uninstalled the zip. Found the v1 windows self installer, ran it thr retried and it worked first go. Do know what it did that i didnt, but all appears good.
