### ISSUE TITLE
json export: consider exporting the content of the album review/movie summary to txt

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#435]
For consideration:
If one has curated and modified the album review / movie or series episode summary, we should export it as well.
My personally preferred method would be to create a sidecar `.txt` file with the name `review.txt` (for music albums) or `summary.txt` for movies and episodes.

Particularly useful if one has still a good portion of those allmusic reviews in the library, which would be otherwise lost when recreating a library.

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
