### ISSUE TITLE
One more translation missing :(

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#438]
Subtitle module

The filter Combo...

The string "-No Filter"

**Comment by ukdtom** [comment]
Disregards, my bad

**Comment by ukdtom** [comment]
Actually....It makes it to Grunt, but isn't used by the frontend?

**Comment by creoludifico** [comment]
See Filter by letter dropdown in Subtitles

**Comment by ukdtom** [comment]
I did

![translations js](https://user-images.githubusercontent.com/4699449/33454774-27f9dd7c-d61a-11e7-9cbb-5f598c73ef1a.png)
![danish settings](https://user-images.githubusercontent.com/4699449/33454782-2c6d92e0-d61a-11e7-81b1-1eb9af3392e3.png)

**Comment by ukdtom** [comment]
Go to lang selection, select danish, wait, the press the update button

They the Danish one should be used ;)

**Comment by creoludifico** [comment]
Fixed now

**Comment by ukdtom** [comment]
Working nicely
