### ISSUE TITLE
v3 GUI - Disparity between the Subtitles & FindMedia modules

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#440]
I would like to see a little more style continuity in the GUI between the Subtitles and Find Media modules.

At present, the Find Media module looks rather anemic in comparison to the Subtitles module.

Perhaps you could add the icons and increase the text size in the Find Media module, so that it is closer to the styles used in the Subtitles module.

Also, there is no Help link or page in the Find Media module.

See the image of the comparison:

![untitled-1](https://user-images.githubusercontent.com/12381786/33470625-05019d6e-d6b5-11e7-93d8-a5086e224cad.png)

**Comment by creoludifico** [comment]
Should have a similar look now

**Comment by ukdtom** [comment]
Indeed

**Comment by trumpy81** [comment]
Nice work Oliver and thank you, it looks great now 👍
