### ISSUE TITLE
FM: find media which are in danger to lose custom edited metadata

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#441]
There are some special circumstances under which a user is in danger to lose hours of hard work.

Imagine a user who has a regular movie or series library.
He adds items into it, which are mostly recognised by Plex and 'matched' to the online metadata sources.
But then the user also adds some items which don't get recognised/not 'matched'. Not matched because these items simply don't exist in the online metadata sources.

So what would a regular Plex user do in such a situation?
He would start editing the series and inputting the data himself, of course.
But there is a big danger, the user is risking to lose all his manual edits in a flash.

What can happen is this:
The library uses a default metadata agent which fetches metadata from an online source.
Since Plex did not find a match for the media item in question, it is still marked as 'unmatched' in the plex database.
"Unmatched" in this case is indicated by a `guid="local..."` 
(This is very different from an item in a 'Personal Media' library, which has a `guid="com.plexapp.agents.none:...` )

So what can happen upon the next library update, is this: 
Plex will try again to find a match online for the yet 'unmatched' item. 
**.... And destroys most of the manually inputted metadata during the 'match' attempt!**

So the user needs to be warned about this danger.
Check for items with a `guid="local*"`
Output a list of the affected items, together with a stern warning that these items could revert to their initial state, without metadata at any time.

**Comment by OttoKerner** [comment]
In a related forum thread, I have shown the user 2 different solutions for this debacle:
https://forums.plex.tv/discussion/comment/1567666/#Comment_1567666

**Comment by ukdtom** [comment]
Nice, but sadly to close to V3.0.0 release, since in lock-down mode here.

Slated for V3.1.x

**Comment by ukdtom** [comment]
Hmmm.....

Just looked a bit more into this, and it's going to be costly, since the guid is only avail when doing a direct lookup of each media :(

In FM, I go by a top level, like:
`32400/library/sections/25/all?X-Plex-Container-Start=1&X-Plex-Container-Size=3`
And only of year or summery is missing, I dig into it.

And since a user could have filled those out, I can't use that, so ideas please @OttoKerner

**Comment by ukdtom** [comment]
Ack then.
Closing for now...

Feel free to reopen, if it's not there in due time
