### ISSUE TITLE
v3 Subtitles - Error when attempting to check subtitles

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#442]
## Environment
- **PMS Platform(s) OS**:  Windows 10
- **PMS Version**:  1.10.1.4527 (Get Loud Integration)
- **Name of Browser**:  FireFox 57.0.1

## Error shown
- **Symptom**:  Attempt to check for subtitles in Other Video and Movie type libraries, an error message pops up. Does not effect TV Show type libraries. Hide media without subtitles option is unchecked.

## Steps to reproduce
1. Attempt to check for subtitles

## Expected behaviour
1. Files within a library be listed.

## Actual behaviour
1. Error message is shown. See attached image.

## Additional Info
Latest translation build (downloaded this morning 10:30am AEST 3-Dec-2017).

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

![untitled-1](https://user-images.githubusercontent.com/12381786/33521241-5d71d9d2-d818-11e7-9695-28e002520395.png)

WebTools logs: 
[PMS Plugin Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1524396/PMS.Plugin.Logs.zip)

**Comment by ukdtom** [comment]
@trumpy81 

You found a bug here ;)

Log says:

`2017-12-03 10:40:18,878 (3b14) :  CRITICAL (core:574) - Fatal error happened in getSection 'NoneType' object has no attribute 'lower' (most recent call last):
  File "C:\Users\ivatr\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\Contents\Code\pmsV3.py", line 841, in GETSECTION
    if Dict['HideWithoutSubs'].lower() == 'true':
AttributeError: 'NoneType' object has no attribute 'lower'`

Thanks for reporting this, and will look into this ASAP

**Comment by ukdtom** [comment]
Please re-download and apply translate build

**Comment by trumpy81** [comment]
Downloaded and installed.

When selecting a library to search for subtitles I no longer get an error message, but if I enable 'Hide Media Without Subs' then it will show the spinning gear and never stop.

If I uncheck the 'Hide Media Without Subs' it will display all files, but the spinning gear is still shown at the end of the list instead of the Load More button. Only way to stop the spinning gear is to close the window and then re-open, sign in etc...

I assume this is because no subtitles are found in my library?

![untitled-1](https://user-images.githubusercontent.com/12381786/33521426-8e0f9f48-d81d-11e7-8b46-55f8c8173b15.png)

**Comment by ukdtom** [comment]
That part is work in progress ;)

See https://github.com/ukdtom/WebTools.bundle/issues/439

**Comment by ukdtom** [comment]
And since you now can access and scan subs, I take it the initial bug you reported is fixed, so closing this one.

Do reopen if not
