### ISSUE TITLE
UAS: localize "App successfully updated"

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#444]
UAS: localize "App successfully updated"
the message after a bundle has been updated

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
