### ISSUE TITLE
Subs: gray out checkboxes for embedded subs

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#445]
They are already disabled, a little bit of CSS may make them darker as well - or even hide them.

![checkboxes](https://user-images.githubusercontent.com/10280992/33525596-2297240a-d833-11e7-92b4-778dfc42d8a2.png)

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
