### ISSUE TITLE
SubManagement is fetching whole section in one go

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#446]
You are fetching the subs in one call

That would make a low powered PMS server, like an Arm based NAS, go to a full stop, and as such, break a playback in progress!

Line 130 in SubService.js

` var url = webtoolsModel.apiV3Url + "/pms/getSection/key/" + show.key + "/start/0/size/9999/title/" + subModel.searchValue;`

Correct way is to call getSectionSize to get the amount of items, and then grab them in small chunks like 40 a time

**Comment by ukdtom** [comment]
If doing a search, increase the start, until backend returns empty

**Comment by ukdtom** [comment]
Also missing the param /getsubs it seems

All in getTvShowDetails

However, done correctly in getMovieDetails

Outcome right now is no subs showing for shows, as well as draining the PMS ;)

**Comment by creoludifico** [comment]
It's only within a season. So unless a season has lots of episodes this shouldnt be a issue?

**Comment by ukdtom** [comment]
Ahhh.....Okay, but you still miss the /getSub

Currently, no subs are shown for shows

**Comment by creoludifico** [comment]
My bad. It is shows. I'll look into it

**Comment by creoludifico** [comment]
Fixed the size problem but there is an issue with hide medias without sub.
Try checking it and open a tv-show. No shows appear. 

Tv-shows doesnt directly have a subtitle like movies have so i guess that is why it's getting filtered backend.

**Comment by ukdtom** [comment]
Please call me

**Comment by creoludifico** [comment]
Give it a check again

**Comment by ukdtom** [comment]
Almost ;)

In the mean time, I also fixed the GETSHOWSEASON to respect the HideWithoutSubs setting, but that reviled, that you doesn't refresh from API, when user toggle that setting

**Comment by ukdtom** [comment]
So merge my branch, and try from that

**Comment by creoludifico** [comment]
Should be fixed now

**Comment by ukdtom** [comment]
Perfect as always
