### ISSUE TITLE
Playlists and icons

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#447]
Would be nice, if playlists also pulled from the icons from plex, like FM and Subs module does

**Comment by creoludifico** [comment]
It's not directly pulling from plex. The icons are located as image files inside a folder in webtools.
1) I need the audio icon.
2) The type of which you return a movie is 'video' and not 'movie' as with the other plugins

**Comment by ukdtom** [comment]
True that we have the icons in our own folder, with permissions from Elan (CTO and founder of Plex)

Audio icon is called `/icons/artist.png`

And yes, the type is not the normal one, but what is returned from PMS to me ;)
And video does makes sense, since a video playlist can mix movies and episodes

And we also do have a video icon: `/icons/video.png`

**Comment by creoludifico** [comment]
Should be fine now

**Comment by ukdtom** [comment]
Wonderful
