### ISSUE TITLE
Log Viewer 

### ISSUE THREAD

**Issue by TMTYD** [ukdtom/WebTools.bundle#451]
Hi
It is possible to set the Log Viewer to show the newest logs first, and you do not have to scroll all the way down to see the last log entry.

**Comment by ukdtom** [comment]
Sadly not possible, but a great idea, so we'll consider that for V3.1

**Comment by WolfganP** [comment]
Will it be possible to also implement a reload feature? (so new entries are easily loaded and facilitates troubleshooting) Thx!

**Comment by ukdtom** [comment]
@WolfganP 

There's already a reload button at the buttom

**Comment by creoludifico** [comment]
Which log should we show? I do not have a timestamp in frontend

**Comment by ukdtom** [comment]
Check out doc in my branch for ListTime

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
