### ISSUE TITLE
TechInfo : Hide Sensitive information

### ISSUE THREAD

**Issue by JamminR** [ukdtom/WebTools.bundle#453]
Enhancement/Feature request -
Many banks and shopping sites will hide all but a few digits of a credit card and/or an account number, with the ability to 'show' and 'hide' accordingly, when viewing an info screen.
I recommend the ability to do this when viewing tech info screen so that users can export/copy paste/make screenshots without needing to manually edit the copy after the fact.
info1: blah
info2: blah
Info3: <details><summary>Show\Hide</summary>JDF988954854KJKJK89894383-K:JK:JKJHJDFYMNNXUi</details>
info4: blah
info5: blah

Of course, my use of markdown and how it works is ugly in this context, but your use of HTML/styling will allow it to be on one line with any fancy effects you wish.

Below is an example of what my online checking looks like for a listing of an individual company I pay.
The * hides the first portion of the account number.
![image](https://user-images.githubusercontent.com/3392170/33806600-a8f65812-dd98-11e7-99fb-606ec031f3b2.png)

**Comment by ukdtom** [comment]
@creoludifico 

Maybe MouseOver event, to show it, as well as a warning?
If so, the key has to be like: "Move mouse here to show the token"

And we are talking about the Plex Token here, if in doubt ;)

**Comment by creoludifico** [comment]
r4c

**Comment by ukdtom** [comment]
Perfect

**Comment by ukdtom** [comment]
@creoludifico 

Please don't push to my branch, since I might miss it, and changes gets lost ;)
