### ISSUE TITLE
WT V3 Release - TV Shows do not display properly in Subtitles

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#454]
## Environment
- **PMS Platform(s) OS**:  Synology NAS And PC
- **PMS Version**: 1.10.1.4561
- **Name of Browser**:  FireFox

## Error shown
- **Symptom**:  When entering the Subtitle module and clicking on TV Shows, only 30 Shows are listed and the Load More button pops ups. Clicking on the Load More button only lists 30 more TV Shows. Selecting a filter results in no change in the list of TV Shows at all.

## Steps to reproduce
1. Open the Subtitles module
2. Click on a TV Show library
3. Select a Filter

## Expected behaviour
1. To list ALL TV Shows
2. To clear the list and display the results of the selected filter
3. Not display the Load More button.

## Actual behaviour
1. only 30 shows are listed
2. Load More button is shown
3. Clicking on the Load More button shows another 30 shows only
4. Selecting a Filter does nothing

## Additional Info

WebTools Logs: [WebTools Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1546019/WebTools.Logs.zip)

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
We fetch them in blocks of 30...
Simply press the "Load More" button again

**Comment by trumpy81** [comment]
That works, but filters do NOT work. I would prefer that all shows are displayed rather than 30 at a time, that is inconvenient to me at least.

**Comment by ukdtom** [comment]
Sorry, but to make sure, that we covers everybody, we have to make sure, that asking the PMS for info, is done in small chunks, to avoid stressing it.
And Who knows, somebody out there might have +1000 shows!

When said, I sadly confirm, that filters are broken :(

**Comment by ukdtom** [comment]
Closed on behalf of #455

**Comment by trumpy81** [comment]
If a user has more than 1000 TV Shows, then the filter could also cause an issue if above a certain number, EG: T = 200, does the Load More button show in these situations also?

Could the number of shows displayed be expanded to be 50 at a time?
Or perhaps a display button be added?

**Comment by ukdtom** [comment]
Paging will kick in for the filter as well.
A display all button will not be done!
Amount of items to fetch could be customized in the setting though, since that way, it's the users own fault ;)

Regardless, closing this one again, since we are having a scope creep from what this was originally about...

Feel free to open a new one, asking specifically for custom paging amount, and I'll categorize it
