### ISSUE TITLE
Subs and paging

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#456]
Users wants to customize the amount of items fetched during page loading.

We should make Settings, like we do in other modules, default to 30, but allow them to change it.
We should however warn then, that raising above 30, could have a performance impact on the PMS, if talking about a huge amount of items!

**Comment by ukdtom** [comment]
Ref: #454

**Comment by trumpy81** [comment]
Maybe we could limit to a certain number in increments of 10 or so.

EG:
Show 30 items
Show 40 items
Show 50 items
...

Until you reach 100 or a reasonably safe number?

WT had no problems listing 130 items before ... just saying.

**Comment by ukdtom** [comment]
Well Andy, inc by 10 is a good idea, but think it's a tad more easy for front end to simply accept a number.

And 130 might have worked in your setup, but imagine an Arm based Syno, or a router?

**Comment by trumpy81** [comment]
True, but anything on those devices is going to be slow, no surprises for a user there ... lol

It was just a thought, it gives the user a choice and can limit the maximum number shown at the same time, but it's up to you and Oliver as to how you handle it.

**Comment by ukdtom** [comment]
It's front-end, so it's Oliver's call exclusively

**Comment by creoludifico** [comment]
I think we should continue with the current 20 and then change it later if necessary.

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
