### ISSUE TITLE
Cannot copy a playlist to -self- ...

### ISSUE THREAD

**Issue by ascholnick** [ukdtom/WebTools.bundle#458]
I *LOVE* the playlist copy feature, but cannot figure out how to copy a playlist TO my main (-Self-) ID.  Please help.

**Comment by OttoKerner** [comment]
Clarification: 
The use case is to _copy_ a playlist from a sharee to the server owner account.

Not to _duplicate_ a playlist on the server owner account.

**Comment by ascholnick** [comment]
Oh.  So, will there be (or is there currently) a means of copying a playlist from a sharee to the server owner?


Andrew Scholnick
ascholnick@aol.com





-----Original Message-----

**Comment by OttoKerner** [comment]
> Oh. So, will there be (or is there currently) a means of copying a playlist from a sharee to the server owner?

There is not. Hence why this entry here exists. ;-) 
This is not a discussion forum but an **issue** tracker.

**Comment by creoludifico** [comment]
Referring to #464
I'll remove self from frontend when it has been added backend

**Comment by ukdtom** [comment]
See #464

**Comment by ukdtom** [comment]
Will be fixed when #464 is closed
