### ISSUE TITLE
Update WebTools

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#459]
Needs to be a 3 step process, IMHO

Step 1: Display the update button, when an update is present
Step 2: If user press the button, show the description from the release.
  That way we can show what's new, and more importantly...Warn people about this and that in the release notes, if needed.
Step 3: Below the release notes, a final button should be present, that actually calls the update procedure itself

Reason is due to issues like this one: #457

**Comment by ukdtom** [comment]
Also noted, that the return to logon screen isn't working as expected, so maybe try this:

When digesting a new version, grap it's version number
Then keep polling /version, until that shows in there, and when so, call logon page
With above, a max of 3 minutes should be set

**Comment by creoludifico** [comment]
The release notes a not translated? How should we handle that?

And could you retry the reload after upgrade. It's working fine here.
If it still not works could you record a gif?

**Comment by ukdtom** [comment]
After I hit the upgrade button....
It upgraded, but during testing if the new version has been loaded, it tries to log it against a not yet avail API ;)

![wtupgradeerr](https://user-images.githubusercontent.com/4699449/34082131-09f4c1ec-e359-11e7-80fa-e069e801cbc6.png)

Waiting 1 min, and then hit refresh in the browser, then works

**Comment by ukdtom** [comment]
And regarding Release Notes, I sadly think we have to leave them as English, since they get written in the last minute, so we can't depend on translators here

**Comment by ukdtom** [comment]
Closed due to lack of response

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
