### ISSUE TITLE
UAS Translation

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#460]
The string:
"No Channels/Plug-ins was migrated "

is not translated

**Comment by ukdtom** [comment]
Translated, yes....Showing, nope....
And as such, defaults to the hard coded English version ;)

**Comment by ukdtom** [comment]
Try and switch language, and you'll see

**Comment by trumpy81** [comment]
uhuh .. I thought it may have been a foreign language related issue, but thought I would let you know that it is exposed and translated in English at least.

**Comment by ukdtom** [comment]
Perfect
