### ISSUE TITLE
Error Installing Bundle

### ISSUE THREAD

**Issue by breezytm** [ukdtom/WebTools.bundle#461]
## Environment
- **Ubuntu 17.10**: 
- **1.10.1.4561**: 
- **Chrome**: 

## Error shown
- **Error occurred!

WebTools

Technical Info: 
Url: api/v3/git/install
Location: Uas
Error: Could not install or update bundle. Check the following URL
BUNDLE URL: https://github.com/jesperrasmussen/AdultDVDEmpire.bundle**: 

## Steps to reproduce
1. 
During any install. All applications gives the same error
## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

Dec 05, 2017 21:51:31.066 [0x7fdf373ff700] INFO - Crash Uploader - Platform: linux-ubuntu-x86_64 (4.13.0-17-generic (#20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017)) ServerUUID: 6bba2832e2394332e2d9b481f73d22427e3bd054 UserId: email address Version: 1.10.0.4523-648bc61d4

**Comment by ukdtom** [comment]
WebTools logs please!

**Comment by breezytm** [comment]
Hey dude. I removed my email address but that's all I see in the log. Unless I am looking in the wrong place. 

Dec 05, 2017 21:51:31.066 [0x7fdf373ff700] INFO - Crash Uploader - Platform: linux-ubuntu-x86_64 (4.13.0-17-generic (#20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017)) ServerUUID: 6bba2832e2394332e2d9b481f73d22427e3bd054 UserId: email address Version: 1.10.0.4523-648bc61d4

**Comment by ukdtom** [comment]
I need a zip with the WebTools logs, not a snip!

**Comment by breezytm** [comment]
https://drive.google.com/file/d/12e0WLRCp7RBFu35t1-FnYF9lKsmxBZwL/view?usp=sharing

**Comment by ukdtom** [comment]
Permissions error!

Log says: `2017-12-13 20:13:29,928 (7fe859ffb700) :  CRITICAL (gitV3:370) - Exception in downloadBundle2tmp: [Errno 13] Permission denied: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/PlexRequestChannel.bundle' (most recent call last):`

In order to install bundles, the user that is running Plex needs full access to the folder named 
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/`

**Comment by breezytm** [comment]
That's interesting. I gave plex:plex ownership of the .bundle folder after I moved it to the Plug-ins folder

system-admin@SKYNET:~$ stat --format '%U:%G' /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/WebTools.bundle/
plex:plex
system-admin@SKYNET:~$ sudo chmod -R 770 "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle"

What else I am missing in regards to permission. Unless they should be root 

drwxr-xr-x 3 root root 4096 Nov 19 13:02 Services.bundle
drwxrwx--- 3 plex plex 4096 Dec 13 20:10 Trakttv.bundle
drwxrwx--- 4 plex plex 4096 Dec 13 19:42 WebTools.bundle

**Comment by breezytm** [comment]
I got it Tommy. Someway somehow, not sure how lol, Service.bundle permission changed. 

system-admin@SKYNET:~$ sudo chown -R plex:plex "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/"
[sudo] password for system-admin: 
system-admin@SKYNET:~$ ls -l "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/"
total 40
drwxr-xr-x 5 plex plex 4096 Dec 14 08:21 Cache
drwxr-xr-x 4 plex plex 4096 Dec  3 17:12 Codecs
drwxr-xr-x 6 plex plex 4096 Dec 14 06:26 Crash Reports
drwxr-xr-x 3 plex plex 4096 Dec 14 06:26 Logs
drwxr-xr-x 3 plex plex 4096 Dec  3 01:57 Media
drwxr-xr-x 6 plex plex 4096 Dec  3 11:16 Metadata
-rw-r--r-- 1 plex plex    5 Dec 14 06:26 plexmediaserver.pid
drwxr-xr-x 5 plex plex 4096 Dec 13 20:10 Plug-ins
drwxr-xr-x 7 plex plex 4096 Nov 19 13:01 Plug-in Support
-rw------- 1 plex plex 1208 Dec 14 08:26 Preferences.xml
system-admin@SKYNET:~$ ls -l "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/"
total 12
drwxr-xr-x 3 plex plex 4096 Nov 19 13:02 Services.bundle
drwxrwx--- 3 plex plex 4096 Dec 13 20:10 Trakttv.bundle
drwxrwx--- 4 plex plex 4096 Dec 13 19:42 WebTools.bundle
system-admin@SKYNET:~$ 

Not it works.

**Comment by aalrashaid** [comment]
hello sir/mam 
i have plex in WDMyCloudEX4100  and was installion webtools  Plugins  uploads in WDMyCloudEX4100 the not working here in the browser, not open application 

this error : 

Wrong installation path detected
It seems like you installed WebTools into the wrong folder

You installed WebTools here:

/mnt/HD/HD_a2/Nas_Prog/plexmediaserver/binaries/Resources/Plug-ins-d7c624def/WebTools.bundle

but the correct folder is:

/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/WebTools.bundle


http://IP:33400/WebTools

**Comment by ukdtom** [comment]
Please note this issue is closed!

Follow the install instructions and use the folder it says.
If still having problems, use the support thread in the forums
