### ISSUE TITLE
Installed plugins show update available even after updating plugin from WebTools

### ISSUE THREAD

**Issue by MrMxyzptlk** [ukdtom/WebTools.bundle#462]
Everything is working great in WebTools 3, including all of my previously installed plugins from version 2; however when I click update on my installed plugins (they all show update), it indicates a successful update, but still shows an update button?

I have logged out and restarted WebTools...is this normal, or a bug?

**Comment by ukdtom** [comment]
It's normal, and used to force a reinstall...
Instead, use the button named "Check for plugin updates" at the top

https://github.com/ukdtom/WebTools.bundle/wiki/UAS

**Comment by MrMxyzptlk** [comment]
That's is what I have been doing, I click on "Check for plugin updates", and all of my installed plugins show an 'update' button on them? Shouldn't it just show 'delete', if I have already updated them?

Also is there a 'location' to update all of them at once...if they have updates?

**Comment by ukdtom** [comment]
If there's any updates avail to what you already have installed, a dialog will show allowing you to update them

**Comment by MrMxyzptlk** [comment]
I guess I'm not explaining the issue very well. 

After installing these plugins in WebTools...they were migrated from 2.x...the migrated plugins all indicated they need updated. I have updated them all, and WebTools indicates the updates were successful, however they all still show as needing updates, no matter how many times I update them.

I could update them 15 times in a row, and it still shows 'update'.

Did that make better sense?

**Comment by trumpy81** [comment]
There must be an issue with your install of WT. The plug-ins should only show 'Update' if they do in fact have an update, not all of the time (at least that is how it is working for me).

I would suggest that you do a Factory Reset of WT. That is, Open WebTools and on the left under Options, click on Factory Reset.

Fingers crossed, after that it should be fine, but if not, then a full uninstall followed by a re-install may be necessary.

You can find details of doing a full uninstall here: https://github.com/ukdtom/WebTools.bundle/wiki/Reset

After WT is fully uninstalled, then use the WT Installer for your system (if applicable) and re-install WT.

Make sure your Plex server is NOT running while you do this, restart the server when you are done.

**Comment by trumpy81** [comment]
And I need to make a correction here, any installed or migrated plugins, always show the 'Update' button.

If a plugin is not installed, then it does not show the 'Update' button.

**Comment by ukdtom** [comment]
Sorry @trumpy81 but you are wrong here!

As soon as a plugin is installed, the "install" button changes to an "update" button, regardless of an update been avail or not!
This gives users the option to force download the latest again, in case something went wrong.
When that's said, when an update is present, a new menu will appear to the left on top of the categories, called "Updates available", and when clicking that, it'll list the ones avail

![updatesavail](https://user-images.githubusercontent.com/4699449/34010731-0a1cd17a-e10e-11e7-831a-89e507b21f95.png)

Clicking on that, will list the updates avail

**Comment by ukdtom** [comment]
Ups....you posted while I was writing ;)

**Comment by trumpy81** [comment]
Sorry Tommy, I just checked and any installed plugins are always showing the Update button.

See the image below. I have ExportTools installed and it has been updated.

![untitled-1](https://user-images.githubusercontent.com/12381786/34010936-20bd265e-e15a-11e7-8000-928cef2a4eee.png)

**Comment by MrMxyzptlk** [comment]
OK, thank you...that solves this mystery.

It looks like the upgrade is working well.

**Comment by ukdtom** [comment]
Yes, as said.....ALL installed bundles has the update button, regardless of an update is avail or not, and by design

**Comment by MrMxyzptlk** [comment]
How do we know if a plugin has an update, if it always shows 'update'?

**Comment by ukdtom** [comment]
As shown in my screen dump.....

It'll shown in the category named "Updates Avail..."
