### ISSUE TITLE
Enhancement request - Personal Certificates

### ISSUE THREAD

**Issue by JamminR** [ukdtom/WebTools.bundle#466]
I use a personal SSL cert and key for several of my web apps, WebTools included.
Every time I update WebTools, I forget that I must go back and copy back over the two files Webtools stores in the repo. (Git may help this, but, I update manually)

Could you enhance the app so that it doesn't overwrite end user cert files?
I figure one of two ways, one more simple than other.

1) Additional options menu - allow users to point to a different location and file in script's search path using a browse button..
Or
2) You have your files, webtools.blah, and the end user has there's, but must match some name you search for.
pseudo code

```
if exist mycert.crt
 load mycert.crt
else if exist webtools.crt
 load webtools.crt
else error/do nothing/whatever
```

With above logic, personal certs would load first, else fall back on your own and not matter when updated.

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/issues/457

**Comment by JamminR** [comment]
Sorry for duplicate. I didn't search closed.
