### ISSUE TITLE
Error when clicking on UAS

### ISSUE THREAD

**Issue by rbluta** [ukdtom/WebTools.bundle#467]
## Environment
- **PMS Platform(s) OS**: Win7
- **PMS Version**: Version 1.11.0.4633
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: 
Error occurred!

WebTools

Technical Info: 
Url: api/v3/git/getListofBundles
Location: Uas
Error: uasService.getListBundle - Fatal error happened in getListofBundles

## Steps to reproduce
1. Open Webtools in browser, Click UAS

## Expected behaviour
1. 

## Actual behaviour
1. 

## Additional Info
Let me know which log files you need or if you just need all of them, Thank You

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
I need a zip of the WebTools.bundle log files

**Comment by rbluta** [comment]
Sorry, I am new to the plex world and WebTools so this may not be the correct log file. But I looked thru it and it does have the critical error listed in it so hopefully this is the correct info for you.

[com.plexapp.plugins.WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/1591416/com.plexapp.plugins.WebTools.log)

**Comment by ukdtom** [comment]
According to the log, it did have current version of UAS, yet some of the data stored seems missing?

Suggest you try a "Factory Reset" and then return back here with status

https://github.com/ukdtom/WebTools.bundle/wiki/Reset

**Comment by rbluta** [comment]
Thank you, that seems to have worked.
