### ISSUE TITLE
The FindMedia tool is showing file with foreign characters (ë,é,ö,ñ etc) as missing.

### ISSUE THREAD

**Issue by unabatedshagie** [ukdtom/WebTools.bundle#468]
## Environment
- **PMS Platform(s) OS**: OS X El Capitan v 10.11.6
- **PMS Version**: 1.11.0.4633
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: The FindMedia tool is showing file with foreign characters (ë,é,ö,ñ etc) as missing.

![capture](https://user-images.githubusercontent.com/931083/34423621-20b9532e-ec15-11e7-9aa4-e1cf3b8b6fe0.PNG)

**Comment by ukdtom** [comment]
Need logs!

**Comment by unabatedshagie** [comment]
Are there logs in particular I need to upload or just the main Plex logs?

**Comment by ukdtom** [comment]
The WebTools logs, in a zip, since they roll over

**Comment by unabatedshagie** [comment]
[PMS Plugin Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1635014/PMS.Plugin.Logs.zip)

Hopefully this is what you need?

**Comment by ukdtom** [comment]
Sorry about the delay in responding here....
Sidetracked by real work :(

But logs are perfect, and I'll look into this

**Comment by ukdtom** [comment]
Not to self: Seems like on OSx, the language is reported as None?

**Comment by rcork** [comment]
Same  issue here with Les Misérables. Logs attached
![screenshot](https://user-images.githubusercontent.com/3687003/36554568-7707d2bc-17b4-11e8-9b60-400d43f3ae92.jpeg)
[Archive.zip](https://github.com/ukdtom/WebTools.bundle/files/1748936/Archive.zip)

**Comment by ukdtom** [comment]
Hi there, care to try this very experimental build, and do note, that Playlist module might be broken in this, since that's work in progress


https://github.com/ukdtom/WebTools.bundle/archive/tommy-464.zip

You'll need to replace the existing WebTools bundle with this one

Please report back both good and bad....

And FUI, it seems like on Mac OSx, the lang variable is not set, so I try and force filesystem encoding in WebTools to utf-8 with this

**Comment by ukdtom** [comment]
And regarless of it works or not, I'll need a zip with all the WebTools logs

**Comment by rcork** [comment]
I get a critical error in the plugin at start up. Looks like reload is not defined

`2018-02-25 08:52:08,045 (7fff9fafe340) :  CRITICAL (sandbox:303) - Exception when calling function 'Start' (most recent call last):
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-c40bba82e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/Users/rob/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Code/__init__.py", line 87, in Start
    reload(sys)
NameError: global name 'reload' is not defined`

**Comment by rcork** [comment]
Interesting article on this setdefaultencoding "hack". Sounds like python 3 fixes a lot of this ascii vs utf-8 headache.

https://anonbadger.wordpress.com/2015/06/16/why-sys-setdefaultencoding-will-break-code/

**Comment by ukdtom** [comment]
Darn, and thanks for testing, and sadly, I have to keep it at Python 2, since that's what the framework is.

I'll try some more here

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
