### ISSUE TITLE
Items missing metadata not correct

### ISSUE THREAD

**Issue by ptr727** [ukdtom/WebTools.bundle#470]
## Environment
- **PMS Platform(s) OS**: W2K16
- **PMS Version**: 1.11.0.4666 
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: No error, wrong results

## Steps to reproduce
1. Run FindMedia

## Expected behaviour
1. Items missing metadata is correct

## Actual behaviour
1. Some items are listed as not having metadata, but are correctly indexed in PMS

## Additional Info
Using WebTools 3.0.0

Examples:
Plex Media Info: "\\STORAGE\Media\Series\Series\Mindhunter\Season 1\MINDHUNTER - S01E01 - Episode 1.mkv"
Items missing metadata: "\\STORAGE\Media\Series\Series\Mindhunter\Season 1\MINDHUNTER - S01E01 - Episode 1.mkv"
Plex Media Info: "\\STORAGE\Media\Series\Series\Doctor Who (1963)\Season 17\Doctor Who - S17E21 - Shada (1).mkv"
Items missing metadata: "\\STORAGE\Media\Series\Series\Doctor Who (1963)\Season 17\Doctor Who - S17E21 - Shada (1).mkv"

I'm wondering if there is a caching problem?
I recently renamed Mindhunter in Sonarr to all caps in when the metadata was updated.
I also recently renamed the Doctor Who folder to fix problems with Plex getting confused between the 1963 and 2005 seasons.

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)
[com.plexapp.plugins.WebTools.log.zip](https://github.com/ukdtom/WebTools.bundle/files/1596854/com.plexapp.plugins.WebTools.log.zip)

**Comment by trumpy81** [comment]
Check the items in question in Plex and verify that they have an 'Originally Available' date.

If they have metadata and no date, FindMedia will show them as not having any metadata.

Manually correct the 'Originally Available' date and then try FindMedia again.

**Comment by ukdtom** [comment]
Actually, we check for year and summary for episodes:

https://github.com/ukdtom/WebTools.bundle/blob/master/Contents/Code/findMediaV3.py#L181

And for movies only if year is missing:

https://github.com/ukdtom/WebTools.bundle/blob/master/Contents/Code/findMediaV3.py#L355

**Comment by ptr727** [comment]
Ah, ok, I misunderstood what the function does, I thought it looks for files on disk that have not been matched in Plex?

For "\STORAGE\Media\Series\Series\Mindhunter\Season 1\MINDHUNTER - S01E01 - Episode 1.mkv":
In this case Plex matched the files, but when I did a fix match, there was a 100% match for Mindhunter, and a 95% match for MINDHUNTER, when I manually selected MINDHUNTER, metadata showed up.

For "\STORAGE\Media\Series\Series\Doctor Who (1963)\Season 17\Doctor Who - S17E21 - Shada (1).mkv":
This episode has a summary, but no date.

**Comment by trumpy81** [comment]
FindMedia looks for files that are in your Plex libraries, but not on disk and files that are on disk but not in your Plex Libraries.

It will also show any files that do not have metadata. That does not necessarily mean they have not been matched, just that they don't have metadata and if they do have metadata, but are missing the Orignally  Available date (and a summary for TV shows) then they will be displayed in FindMedia.

**Comment by ukdtom** [comment]
Well.....

We do show 3 different categories already....

*  Missing from database, but present in file-system
*  Missing from file-system, but present in database
*  Present both places, but some vital info is missing (Year)

We can't show why a match failed, since we do simply not know that....
(It's only logged in the relevant agent logs during the initial scan)
All we can do, is point to some candidates, which we do...
You then have to retry them, and if they still fail, post your logs in the relevant PMS server forum, if you are sure your media files are named correctly
