### ISSUE TITLE
No Soup For You

### ISSUE THREAD

**Issue by jdesign214** [ukdtom/WebTools.bundle#473]
## Environment windows 7
- **PMS Platform(s) OS**: sorry I don't know what you mean other than PMS version.
- **PMS Version**: Version 1.10.1.4602
- **Name of Browser**: Mozilla Firefox

## Error shown  
No soup for you!
The server you're trying to access doesn't want to let you in. Make sure you're signed in as a user with access to this server.
- **Symptom**: I can't open either of the 2 new urls to get into webtools, 
## Steps to reproduce
1. click on the webtools icon in channels, click on log in, try to open either of the 2 urls

## Expected behaviour
1. New version of webtools

## Actual behaviour
1. 

## Additional Info
WebTools V3.0.0 WebTools V3.0.0 3
Settings:
33400
33443
certificate dir:WebTools.crt
Name of certificate: WebTools.key
No other info in settings, nothing checked
That is my info to the best of my ability.
Please advise.
Thank you. Joan Yannotti
JoanYannotti@gmail.com

**Comment by trumpy81** [comment]
You cannot click on the url's listed in Plex/Channels/WebTools they are informational only.

That is a limitation imposed by Plex.

Instead, you must type those addresses into your browser, then you should see WebTools open with any luck.

**Comment by jdesign214** [comment]
[Plex Media Server_20171223214846.log](https://github.com/ukdtom/WebTools.bundle/files/1620705/Plex.Media.Server_20171223214846.log)
[Plex Media Server_20171223214846_002_pms.log](https://github.com/ukdtom/WebTools.bundle/files/1620706/Plex.Media.Server_20171223214846_002_pms.log)
[Plex Media Server_20171223214943.log](https://github.com/ukdtom/WebTools.bundle/files/1620707/Plex.Media.Server_20171223214943.log)
[dd_vcredist_x86_20171223214902.log](https://github.com/ukdtom/WebTools.bundle/files/1620708/dd_vcredist_x86_20171223214902.log)
[Plex Media Server_20171223214846_000_pmsshutdown.log](https://github.com/ukdtom/WebTools.bundle/files/1620709/Plex.Media.Server_20171223214846_000_pmsshutdown.log)
[Plex Media Server_20171129181937.log](https://github.com/ukdtom/WebTools.bundle/files/1620710/Plex.Media.Server_20171129181937.log)
[Plex Media Server_20171129181937_002_pms.log](https://github.com/ukdtom/WebTools.bundle/files/1620711/Plex.Media.Server_20171129181937_002_pms.log)

**Comment by jdesign214** [comment]
Trumpy81...I was right clicking and opening in a new window.  Your way worked.  Thank you very much.
