### ISSUE TITLE
[REQ] Show a table of DVR recording jobs with episode retention info

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#475]
The DVR module allows you to define how long an already 'watched' episode is kept on the server before it is automatically erased.
Checking all recording jobs for these kind of setting is a PITA in the official Web app, since there is no table to see all recording jobs and their properties at once. Currently, the user has to click 2 times on each recording job separately to get that info.

This 'episode retention' setting is also present in the properties of each tv series ('Advanced' tab).
Users are often bitten when they fool around with them in a library that is used for DVR, but users don't realize that these retention settings are also effective in their regular 'tv show' library (without DVR).

So a central place where one can see a list of all series which have such a 'dangerous' property would be welcome.

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
