### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by DrumGuy68** [ukdtom/WebTools.bundle#477]
## Environment
- **PMS Platform(s) MacOS10.13.2: 
- **PMS Version**: 
- **Name of Browser**: Chrome, Safari

## Error shown
- Error occurred! 500: Internal Server Error: 

## Steps to reproduce
1. login

## Expected behaviour
1. every time I login

## Actual behaviour
1. Same

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Need WebTools logs as a zip here!
https://github.com/ukdtom/WebTools.bundle/wiki/FAQ#Q3

**Comment by DrumGuy68** [comment]
[Plex Media Server Logs_2018-01-22_16-17-48.zip](https://github.com/ukdtom/WebTools.bundle/files/1653614/Plex.Media.Server.Logs_2018-01-22_16-17-48.zip)

**Comment by ukdtom** [comment]
Not usefull!

Please follow the link I provided above, and DO NOT use the PMS build in download functionality, since that doesn't include 3.Party logs, and I need the ones for WebTools

**Comment by DrumGuy68** [comment]
[PMS Plugin Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1653745/PMS.Plugin.Logs.zip)
Sorry, wasn't paying attention.

**Comment by ukdtom** [comment]
Log says:

`2018-01-22 15:28:13,614 (7000027ab000) :  CRITICAL (webSrv:327) - Exception in Login: Invalid cookie 'WebTools 3.26.41 PM'`

Most likely, you have some plugin in your browser messing stuff up here...

Try a different browser, like Chrome

**Comment by DrumGuy68** [comment]
I tried Firefox, Chrome and Safari and all get the same result.   I started Firefox in safe mode and still get the error 500.  Firewall settings are off, no anitvirus blocking either.

**Comment by ukdtom** [comment]
I suppose you are running everything on your Mac?

If so, any chance of a second workstation could try and access it?

And if not, then sorry....Clueless here then :(

Never ever seen this before

**Comment by trumpy81** [comment]
Open FireFox and go to Options > Privacy & Security > Forms and Passwords and then click on the Saved Logins button.

You will have to click on remove all. Note, any saved logins will need to be readded when you sign in anywhere.

Under History, click on the Remove Individual Cookies and then click on Remove all.

You will need to do the same with Chrome and Safari.

You will need to follow the instructions under Manually on this page: https://github.com/ukdtom/WebTools.bundle/wiki/Reset

SIgn into Plex again and make sure all is well with Plex before you attempt to open WebTools by typing in http://Plex-Server-IP:33400

Fingers crossed, all should be well.

**Comment by DrumGuy68** [comment]
Thanks for that info.   I did follow the procedure but I'm still getting the same thing.     I will try the server on another machine to if it makes a difference.

**Comment by ukdtom** [comment]
Closed due to lack of response
