### ISSUE TITLE
Importing playlist doesn't keep order

### ISSUE THREAD

**Issue by Kryptonit3** [ukdtom/WebTools.bundle#480]
## Environment
- **PMS Platform(s) OS**:  Ubuntu 14.04
- **PMS Version**:  latest public
- **Name of Browser**:  Chrome

## Error shown
- **Symptom**: 

## Steps to reproduce
1.  Create Playlist in proper order in Plex
2. Export playlist in m3u8 file with this utility
3. Delete playlist
4. Import playlist file

## Expected behaviour
1. Import and have Plex playlist in exact order as m3u8 file

## Actual behaviour
1. Does not import in order.

## Additional Info
I have a playlist of over 200 items and I forgot to add a few videos in the middle of the list. So I added it to the playlist which then puts them at the end and it would suck dragging all of them up to the middle. So I export the playlist, edit the order, then delete and import edited file. Not even remotely the same order as the export. The export lists the items in the right order, but the playlist that shows up in Plex isn't in order.

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
The order itself is not important!
It's the "ListId" that determines the order

**Comment by Kryptonit3** [comment]
I thought the same thing so I imported an unchanged list and it also did not import in order. Not event remotely close. I made a playlist with over 200 items of the marvel universe.

**Comment by ukdtom** [comment]
Looking into this

**Comment by weatherdown** [comment]
I just ran into this same issue as well.. same playlist actually. 200+ items for the Marvel Universe. Copying to another user takes it out of order. :(

**Comment by MathiasLoewe** [comment]
Experiencing the same issue :(

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

As such, this will sadly not be fixed :(
