### ISSUE TITLE
NoIcon.png not found when accessing UAS page

### ISSUE THREAD

**Issue by roedesh** [ukdtom/WebTools.bundle#481]
## Environment
- **PMS Platform(s) OS**: Raspbian Jessie (but running on Raspbian Stretch)
- **PMS Version**: Version 1.10.1.4602
- **Name of Browser**: Google Chrome

## Error shown
- **Symptom**: 
```
Url: api/v3/git/updateUASCache
Location: Uas
Error: uasService.forceCache - Exception in updateUASCache [Errno 2] No such file or directory: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.Webtools/DataItems/NoIcon.png'
```

## Steps to reproduce
1. Install WebTools.bundle in the Plug-ins folder
2. Go to PMS-IP:33400
3. Click on the UAS link

## Expected behaviour
1. Be able to access the UAS page

## Actual behaviour
1. Receive error

## Additional Info
I tried manually copying the image file to the folder, but I still get the error.

WebTools log can be found [here](https://drive.google.com/file/d/1xjLCeagFdapiy0j1Xb3FzU3OvaOQbwvy/view?usp=sharing)
PMS log can be found [here](https://drive.google.com/file/d/1qZDm6RFxXRg2YbPwlzPvXA9Id_HVmQm1/view?usp=sharing)

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Start by doing a reset, followed by a migrate

https://github.com/ukdtom/WebTools.bundle/wiki/Reset

**Comment by roedesh** [comment]
I did a manual reset and restarted the Plex Media Server, but the same error appears.

**Comment by roedesh** [comment]
It seems I made a very stupid typo. The plugin folder was called Webtools.bundle instead of WebTools.bundle, one capital T missing..

This can be marked as solved.
