### ISSUE TITLE
Can only see the buttons for each channel, the descriptions aren't visible

### ISSUE THREAD

**Issue by Mongoose69** [ukdtom/WebTools.bundle#483]
## Environment
- **PMS Platform(s) OS**: 
Synology DS216+II NAS Running DSM 6.2 beta
- **PMS Version**: 
11.9.something (the latest version via Plex Plus)
- **Name of Browser**: 
Android Chrome 63.0.3239.111

## Error shown
- **Symptom**: 
Can only see the buttons for each channel, the descriptions aren't visible.
So it's a matter of trying each one until I get it right

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ X ] Listed environment
- [ ] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [ X ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Heh, and confirmed.
4 now, use a browser on a workstation

**Comment by ukdtom** [comment]
Also a user on the forums uploaded a video showing it
http://forums.plex.tv/discussion/comment/1609926/#Comment_1609926

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
