### ISSUE TITLE
Error message after clicking on UAS...

### ISSUE THREAD

**Issue by epauldc29** [ukdtom/WebTools.bundle#484]
## Environment
- **PMS Platform(s) OS**: Win 10
- **PMS Version**: 1.11.1.4730 
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: Technical Info: 
Url: api/v3/git/updateUASCache
Location: Uas
Error: uasService.forceCache - Exception in updateUASCache [Errno 2] No such file or directory: u'\\\\?\\C:\\Users\\Plex\\AppData\\Local\\Plex Media Server\\Plug-ins\\WebTools.bundle\\http\\icons\\NoIcon.png'

## Steps to reproduce

It seems that when installed Plex created a Plug-in dir called Plug-ins-6967ec0b1 in C:\Program Files (x86)\Plex\Plex Media Server\Resources and I assume that's why Webtool 3.0.0 can't find the needed information??  

How do I correct. Changing the directory name to just Plug-ins causes the plex service to fail of course.
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [x ] Listed environment
- [X ] Included PMS log zip and WebTools log
[Plex Media Server Logs_2018-01-27_11-24-39.zip](https://github.com/ukdtom/WebTools.bundle/files/1670236/Plex.Media.Server.Logs_2018-01-27_11-24-39.zip)
[com.plexapp.plugins.WebTools.zip](https://github.com/ukdtom/WebTools.bundle/files/1670238/com.plexapp.plugins.WebTools.zip)

- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Wrong install dir!

Remove WebTools, and use the EasyInstaller....
https://github.com/ukdtom/WebTools.bundle/wiki/Install
