### ISSUE TITLE
Error occurred! on login

### ISSUE THREAD

**Issue by romanar** [ukdtom/WebTools.bundle#486]
## Environment
- **PMS Platform(s) OS**:
Debian 9 (64bit) & Docker version 17.12.0-ce, build c97c6d6
- **PMS Version**:
Plex Media Server Version 1.10.1.4602 
- **Name of Browser**:
FirefoxDeveloperEdition
Version: 59.0b2
Build ID: 20180117222144
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0
## Error shown
```
Error occurred!
WebTools

Technical Info:
Url: api/v3/git/getReleaseInfo/url/https%3A%2F%2Fgithub.com%2Fukdtom%2FWebTools.bundle/version/latest
Location: Core
Error: var checkIsNewVersionAvailable - Fatal error happened in getReleaseInfo
```
![screen shot 2018-01-29 at 3 35 51 pm](https://user-images.githubusercontent.com/32021606/35533209-d13d1330-050a-11e8-8061-6db342c7a8c9.png)
## Actual behaviour
1. Error shows up on login and page reload
## Additional Info
I have same setup on another machine and on that I'm seeing now error
## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
I need WebTools logs!

Also....Are you behind a Proxy?

**Comment by romanar** [comment]
Yes on this machine I'm behind a Proxy. ([WebTool Logs Zip](https://github.com/ukdtom/WebTools.bundle/files/1675268/Archive.zip))
Thanks for the quick response.

**Comment by ukdtom** [comment]
Before I start spending time on logs, make sure that if Apache mod_proxy, that you followed the manual:

https://github.com/ukdtom/WebTools.bundle/wiki/Configure

**Comment by romanar** [comment]
I apologize for the late reply and you can close the issue as its working fine after I explicitly exposed the WebTools port.
