### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#487]
Would be nice, if we could group users, and then assign sharing rights to the groups ;)

**Comment by JamminR** [comment]
I came here today to request this feature. I add holiday/random theme libraries for periods of time to remove them later. I only have about 20 shared users, but know others who speak of more.
The ability to edit multiple users at once would be great. I imagine a library listing (multi-selection or checkbox) on one side of panel, and multi selection capable user list on the other.

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
