### ISSUE TITLE
issue when selection the view logs option

### ISSUE THREAD

**Issue by ahiguero** [ukdtom/WebTools.bundle#489]
## Environment
- **PMS Platform(s) OS**: Android (Rooted Nvidia Shield adopted storage)
- **PMS Version**: 1.11.1.4730
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: when clicking on the view log option i get the folowing message

Technical Info: 
Url: api/v3/logs/show/Plex Media Scanner Analysis.1.log
Location: Logs
Error: logsService.getLogDetails - Fatal error happened in Logs show: bad argument type for built-in operation

## Steps to reproduce
1. click ont he view logs option

## Expected behaviour
1.  display select logs

## Actual behaviour
1.  error message described above

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)
[logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1708630/logs.zip)

**Comment by ukdtom** [comment]
This is nasty, and sadly suspect it's due to the PMS Framework behaves differently on a Shield.
Sadly don't own a shield, so kinda up hill here...
For now asked a friend to see if he can replicate

**Comment by ahiguero** [comment]
i can install apps form the unsupported app store but after installation i need to do a migrate so that they show properly on the plug-in

**Comment by ukdtom** [comment]
Please create a new GHI for each issue!

**Comment by ukdtom** [comment]
Bad news here....

My friend returned, and his device is not rooted, nor does he wants to do that.

As such, I sadly have to say, that I can't help here, since not owning such a device

All I can do, is to declare Shields not supported :(

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/wiki/Known-Issues

**Comment by sschadwick** [comment]
The latest version of PMS for ShieldTV includes a feature to move the plex data directory from the protected directory to either user-accessible internal or external storage, allowing for non-rooted devices to install WebTools.

Unfortunately I am also encountering this log issue.
