### ISSUE TITLE
UAS Channels not responding -- PLease Help

### ISSUE THREAD

**Issue by sam5558** [ukdtom/WebTools.bundle#491]
## Environment
- **PMS Platform(s) OS**: Linux kernel 4.14.0-0.bpo.3-amd64 (OpenMediaVault 4.x)
- **PMS Version**: 1.10.1.4602
- **Name of Browser**:  Firefox 58.0.2

## Error shown
- **Symptom**:  When installing channels from UAS, plex is saying "the channel is not responding", crunchyroll, icefilms, filmon, 9anime, ... pretty much every streaming channel is giving me same error.
![image](https://user-images.githubusercontent.com/26897744/36117211-b0d7bbfa-1030-11e8-9bd5-1ed554d546b7.png)
Note that i'm having this issue only with unofficial plex channels because i installed an official plex channel to compare if plex will give me the same error but no, i installed national geographic channel and it's working like a charm.

- PMS log zip and WebTools log :
[Plex Media Server Logs_2018-02-12_20-13-43.zip](https://github.com/ukdtom/WebTools.bundle/files/1717615/Plex.Media.Server.Logs_2018-02-12_20-13-43.zip)
[PMS Plugin Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1717698/PMS.Plugin.Logs.zip)

**Comment by ukdtom** [comment]
As said in the opening post for WebTools.....

We do not support individual pluging's!

Go visit the forum opening post, and look under support
