### ISSUE TITLE
Login with google

### ISSUE THREAD

**Issue by Asafb26** [ukdtom/WebTools.bundle#495]
## Environment
- **PMS Platform(s) OS**:  Ubuntu
- **PMS Version**: 1.11.3.4803
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: I recently created Plex account using my Google account. and there seems no way to login WebTools using it.

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [x] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by Asafb26** [comment]
I found a way, just need to set password under my account in plex's user profile

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/wiki/FAQ#Q8

Thanks for sharing here
