### ISSUE TITLE
Nothing is showing up under UAS,  Windows 10 Internet Explorer

### ISSUE THREAD

**Issue by gsnoel11** [ukdtom/WebTools.bundle#502]
## Environment
- **PMS Platform(s) OS**: 
- **PMS Version**: 
- **Name of Browser**: 

## Error shown
- **Symptom**: 

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by Debojit** [comment]
I'm getting the same error. I get a red popup with the following content when I click the UAS button:

Technical Info: 
Url: api/v3/git/getListofBundles
Location: Uas
Error: uasService.getListBundle - Fatal error happened in getListofBundles

**Comment by ukdtom** [comment]
Great....

Now we have two guys, not filling out the template, nor providing logs :(

Closing this...

Please start new ones, fill out the template, and provide logs!
