### ISSUE TITLE
UAS Plugin List Error

### ISSUE THREAD

**Issue by Debojit** [ukdtom/WebTools.bundle#503]
## Environment
- **PMS Platform(s) OS**: Windows 10 64-bit
- **PMS Version**: 1.12.2.4929
- **Name of Browser**: Chrome (version 65.0.3325.181)

## Error shown
- **Symptom**: UAS button throwing following error.

## Steps to reproduce
1. Login to WebTools
2. Click UAS.

## Expected behaviour
1. UAS should load a list of available plugins.

## Actual behaviour
1. No plugins loaded, error thrown.

## Additional Info
1. Log files attached
[PMSLogs_20180415-223700.zip](https://github.com/ukdtom/WebTools.bundle/files/1913097/PMSLogs_20180415-223700.zip)
[WebTools.zip](https://github.com/ukdtom/WebTools.bundle/files/1913106/WebTools.zip)
2. Screenshot attached
![webtools_uas_error](https://user-images.githubusercontent.com/3645322/38781161-ee047cf8-40fe-11e8-8f0a-0b5e4c2690bc.gif)

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by Debojit** [comment]
Error remains. Furthermore, "Migrate" returns a different error, as shown below:
![uas_migrate](https://user-images.githubusercontent.com/3645322/38782538-c3133e1c-4112-11e8-9fc7-4092bb67861a.gif)

**Comment by ukdtom** [comment]
Wow.....You also have untranslated strings!

If so, the whole installation is most likely faulty.
Did it ever work?

And you need to remove it manually, see https://github.com/ukdtom/WebTools.bundle/wiki/Reset

After that's done, remove the WebTools.bundle directory completely, then run this:
https://github.com/ukdtom/WTInstaller/releases/download/1.2/Windows_Inst_WebTools_1.0.exe

And please report back both good and bad news

**Comment by Debojit** [comment]
Doing a clean install did the trick. It seems that the installation itself was corrupted. Thanks for the help.

**Comment by ukdtom** [comment]
You're welcome
