### ISSUE TITLE
Unable to login to webTool v3.0.0

### ISSUE THREAD

**Issue by ashraf008** [ukdtom/WebTools.bundle#506]
![image](https://user-images.githubusercontent.com/25363371/39936237-6f368022-5569-11e8-8a85-7095158258c8.jpg)

The wheel is spinning thats it ..

**Comment by ukdtom** [comment]
The reason why when creating an issue a template is presented, is due to the fact that we need the info in it!

Closing this one, so please create a new one, and fill it out
