### ISSUE TITLE
Undefined variable (easy fix)

### ISSUE THREAD

**Issue by pproba** [ukdtom/WebTools.bundle#507]
https://github.com/ukdtom/WebTools.bundle/blob/16591c18e9e9b5f672d2ebdf14e16e3cd85d689b/Contents/Code/playlistsV3.py#L948

"sizeURL" should be "url"

I've already tried it and it works as expected now.

**Comment by ukdtom** [comment]
Already fixed, and will be part of the next release

https://github.com/ukdtom/WebTools.bundle/issues/471
