### ISSUE TITLE
log display table layout

### ISSUE THREAD

**Issue by TMTYD** [ukdtom/WebTools.bundle#508]
If I look at the logs, the table is too wide, the font goes beyond the scroll bar, I looked, I do not know if it's correct, but I add at table 4, table-layout at normalize.less line 416 : fixed; in addition it looks normal.

Would it be possible to have the latest log entries at the top?
![webtools](https://user-images.githubusercontent.com/29516076/40633714-a556587c-62f1-11e8-8eff-108b93c75404.jpg)

**Comment by WolfganP** [comment]
Word wrapping on log lines and reverse lines order (most recent entry at the top) or a one click way to go to the bottom) are good suggestions to improve quick troubleshooting.

**Comment by TMTYD** [comment]
ok thx

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
