### ISSUE TITLE
I cant delete a downloaded agent subtitle from a movie

### ISSUE THREAD

**Issue by WildPanda1234** [ukdtom/WebTools.bundle#513]
## Environment
- **PMS Platform(s) OS**:  Windows
- **PMS Version**: 3.53.7
- **Name of Browser**:  google chrome

## Error shown
- **Symptom**:  When i try to delete a subtitle from a movie i cant seem to delete it :/ When ever i delete a subtitle it just re-adds the deleted subtitle over and over from opensubtitles

I hope this is enough information for you as i cant seem to answer the rest of the required questions otherwise let me know if you need anything else

**Comment by ukdtom** [comment]
https://github.com/ukdtom/WebTools.bundle/wiki/FAQ Q6

This is how it works....

You'll need to disable OpenSubtitles then
