### ISSUE TITLE
CrunchyRoll

### ISSUE THREAD

**Issue by madman32395** [ukdtom/WebTools.bundle#514]
## Environment
- **PMS Platform(s) OS**: N/A
- **PMS Version**: N/A
- **Name of Browser**: N/A

## Error shown
- **Symptom**: Cannot install Crunchyroll via UAS due to dead link on MattRK's end.

## Steps to reproduce
1. Open UAS tab
2. Attempt to install Crunchyroll
3. Fail.

## Expected behaviour
1. Install Crunchyroll

## Actual behaviour
1. Error
2. Upon following the MattRK/Crunchyroll.bundle url, its a dead link

## Additional Info
Error occurred!

WebTools

Technical Info: 
Url: api/v3/git/install
Location: Uas
Error: Could not install or update bundle. Check the following URL
BUNDLE URL: https://github.com/MattRK/Crunchyroll.bundle

## Checklist
- [ ] Listed environment
- [x] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

![image](https://user-images.githubusercontent.com/2025022/42245611-fa4ac99a-7ede-11e8-8a03-04f9271eaf10.png)

**Comment by madman32395** [comment]
[com.plexapp.plugins.WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/2161132/com.plexapp.plugins.WebTools.log)

**Comment by ukdtom** [comment]
WebTools is working as designed here, but sadly, the user removed the bundle from Github, without telling us, so I'll remove it from UAS.

Huge thanks for telling us
