### ISSUE TITLE
[REQ] scheduled Playlist Management

### ISSUE THREAD

**Issue by snickers2k** [ukdtom/WebTools.bundle#516]
Would be great if you could add some kind of scheduled Playlist Management.
So i could set up a task for daily syncing the playlists, which should Plex have for years.

thanks

**Comment by ukdtom** [comment]
Good idea, and FYI, then SmartList support is slated for the next version as well

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
