### ISSUE TITLE
Drop down list of available logs sorting

### ISSUE THREAD

**Issue by WolfganP** [ukdtom/WebTools.bundle#519]
When trying to troubleshoot an issue, I usually need to go to prev or next log in order to check some other runs app/module behavior.
I noticed that the plugin logs end in a number so the natural sorting is good, but Plex modules' logs are 1 (prior to latest) to 5 (older) and THEN the recent one is listed (latest) which complicates a quick prev/next operation in timely order.

![plex-logs-list](https://user-images.githubusercontent.com/2248211/45119668-937e6d80-b14b-11e8-95cc-05927348bb4c.jpg)

Is it possible to alter the order of the drop down listing for the current Plex* log to stay at the top of the category? (ie Plex*.log, Plex*.1.log, Plex*.2.log ...)
Thx.

**Comment by ukdtom** [comment]
We'll look into it

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
