### ISSUE TITLE
Download/Upload playlist via command line

### ISSUE THREAD

**Issue by josopu** [ukdtom/WebTools.bundle#524]
Is it possible to download/upload some playlists from the command line? I want to do a scheduled maintenance of my playlists. Thanks in advance for all your work!

**Comment by ukdtom** [comment]
Sorry, but WebTools do not support CLI out of the box.
When said, the API would be the way to go, since that's what the front-end use ;)
All documented here:
https://github.com/ukdtom/WebTools.bundle/blob/master/Contents/Code/Docs/REST%20API%20V3.odt
