### ISSUE TITLE
Playlist Import Length Limited to 30 titles

### ISSUE THREAD

**Issue by Psychocrysma** [ukdtom/WebTools.bundle#525]
## Environment
- **PMS Platform(s) OS**: Windows 10
- **PMS Version**: v3.0.0
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: Not exactly an error but basically, it's an issue with the limitations of the playlist import and I have found the exact length where the playlist breaks. Essentially, any playlist containing more than 30 songs stops importing at 30. I can download a playlist with 31 songs and when I import it, it doesn't add the 31st song. 

## Steps to reproduce
1. Build a playlist of 31 songs or more.
2. Download it.
3. Delete it from Plex.
4. Import it.

## Expected behaviour
1. The whole playlist, no matter the size, will be imported.

## Actual behaviour
1. Upon importation, the actual playlist on plex will contain only 30 songs.

## Additional Info
I have produced this bug not manually but while trying to cheat the system. I made a quick C# converter to convert my winamp playlists into a usable file. And they work very well, but they stop at 30. This is why I checked if this issue was produced manually, and it is. 

[PMSLogs_20181116-082935.zip](https://github.com/ukdtom/WebTools.bundle/files/2589451/PMSLogs_20181116-082935.zip)
## Checklist
- [X] Listed environment
- [X] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [X] Included screenshots (where appropriate)
- [X] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
I see errors in the log, like:

`2018-11-16 07:29:23,601 (359c) :  CRITICAL (core:574) - Exception happened in Playlist import was: 'utf8' codec can't decode byte 0x8c in position 0: invalid start byte (most recent call last):
  File "D:\Users\Gabriel\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\Contents\Code\playlistsV3.py", line 367, in IMPORT
    success.append(unicode(items[item]['title']))
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8c in position 0: invalid start byte`

Got a title that starts with `ƌ`perhaps?

Also: `Ƒ` seen in:
`2018-11-16 08:08:57,871 (359c) :  CRITICAL (core:574) - Exception happened in Playlist import was: 'utf8' codec can't decode byte 0x91 in position 0: invalid start byte (most recent call last):
  File "D:\Users\Gabriel\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\Contents\Code\playlistsV3.py", line 367, in IMPORT
    success.append(unicode(items[item]['title']))
UnicodeDecodeError: 'utf8' codec can't decode byte 0x91 in position 0: invalid start byte`

**Comment by ukdtom** [comment]
Also, you should switch locale of your server to utf-8

`*******  Started WebTools V3.0.0 on Windows at 2018-11-16 07:25 with locale set to ('en_GB', 'cp932')`

**Comment by ukdtom** [comment]
Scratch above, since you are running Windows :(

**Comment by Psychocrysma** [comment]
Ah yes sorry this was during testing. Many of my song titles are in Japanese, so my playlists go through encoding JIS. And then I convert them to UTF 8 manually.

**Comment by Psychocrysma** [comment]
In these examples, I simply forgot to manually convert them. My bad.

**Comment by ukdtom** [comment]
Can you provide a fresh set of logs, in utf-8?

**Comment by Psychocrysma** [comment]
That said, the Japanese title were being imported with no issue. It really is only the 30 length limit that was problematic for me. After all, my playlists have around 700 titles each.

**Comment by Psychocrysma** [comment]
As a side note, what do the ID and ListID stand for in the playlists?

**Comment by ukdtom** [comment]
ID: Key of media within PMS
ListID: Key of Media within the Playlist itself

**Comment by Psychocrysma** [comment]
Is this something that is set by Plex already or you can set it yourself? Also, here are the clean logs. The first shot was done with a manual playlist. The second was done with the playlist stored within the ZIP. 
[Logs and Playlist.zip](https://github.com/ukdtom/WebTools.bundle/files/2589668/Logs.and.Playlist.zip)

**Comment by ukdtom** [comment]
See for yourself, by browsing to:

`http://IPOFPMS:32400/playlists/KEYOFPLAYLIST/items?X-Plex-Token=YOURTOKEN`

So if on the server, try:
`http://127.0.0.1:32400/playlists/3823/items?X-Plex-Token=YOURTOKEN`

You can get your TOKEN from the TechModule of WebTools

**Comment by Psychocrysma** [comment]
That gives me an Error 404.

**Comment by ukdtom** [comment]
Means not found, so you deleted the playlist in the mean time ;)

Try: 
`http://127.0.0.1:32400/playlists?X-Plex-Token=YOURTOKEN`

to get a list of playlists, and then use the `ratingkey` value as KEYOFPLAYLIST

**Comment by Psychocrysma** [comment]
I guess that value is set then but the first track's there and the ID the playlist had set was completely different so I really am not sure if that's the issue.

**Comment by Psychocrysma** [comment]
Alright I want to update regarding this: I am pretty sure my issue is caused by the fact that my rating keys are broken. I have done some more testing with valid rating keys I've gotten through /library/metadata/ and it seems to be working better. However, at that point, I think it becomes less necessary to use WebTools at all. I am going to start working on an application in C# tomorrow that will run through http://192.168.0.xxx:32400/library/sections/1/all?X-Plex-Token= and basically pick off all its children and loop till it gets all the files necessary and basically make a valid playlist, then do a http://192.168.0.xxx:32400/playlists/upload?sectionID=1&path=F:\Music\Playlist.m3u8&X-Plex-Token= to directly upload it. And for the sake of efficiency, I might do a run through command line instead of using the urls.

**Comment by ukdtom** [comment]
http://IP_OF_PMS:32400/identity

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
