### ISSUE TITLE
Unsupported app store for Emby

### ISSUE THREAD

**Issue by BenjaTheNinja1977** [ukdtom/WebTools.bundle#529]
Not sure if this is the place for this; but as many know, Plex no longer supports plug ins and I can't use them on Roku. What are the odds we get a version of this for Emby?

## Environment
- **PMS Platform(s) OS**: 
- **PMS Version**: 
- **Name of Browser**: 

## Error shown
- **Symptom**: 

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
From me, NONE

**Comment by BenjaTheNinja1977** [comment]
Cool.
