### ISSUE TITLE
Webtools Bundle cannot be installed

### ISSUE THREAD

**Issue by hermannx5** [ukdtom/WebTools.bundle#530]
## Environment
- **PMS Platform(s) OS**: Synology
- **PMS Version**: 
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: Install of Webtools fails in DSM

## Steps to reproduce
1.  go to manual install in DSM, chose "Synology_Inst_WebTools_1.4.spk", start installation

## Expected behaviour
1.  Webtools installed

## Actual behaviour
1. Error Message

## Additional Info
I have installed the webtoolls on a prior Plex installation on this Synology DS218 (which I have deinstalled in the meantime) successfully,

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)
[WebTools.zip](https://github.com/ukdtom/WebTools.bundle/files/2720809/WebTools.zip)
![error webtools](https://user-images.githubusercontent.com/46320338/50593412-89ba0c00-0e98-11e9-91ed-4bed0a3c5775.PNG)

**Comment by hermannx5** [comment]
Forgot to mention: I checked the permissions, should be fine....

**Comment by ukdtom** [comment]
Closed on behalf of:
https://github.com/ukdtom/WTInstaller/issues/23

**Comment by cswanghan** [comment]
any solutions? got the same problem here.
