### ISSUE TITLE
Search by Filename

### ISSUE THREAD

**Issue by oucil** [ukdtom/WebTools.bundle#531]
This is a feature request for a "Search by Filename" option.  

My specific use case is that the scanners keep identifying a file incorrectly no matter how many times I rename according to standards, move in and out of libraries, etc. but I can't find which movie it's being matched to.  It's not in the unmatched list in your utilities so I know it's in there somewhere.

I would like to be able to find which "Movie" in the Plex DB is being associated to the file itself, so that I can manually match it.  I'm sure there are other uses for this, but it would be extremely helpful in my case.

Thanks for your hard work!

**Comment by ukdtom** [comment]
Actually, due to the end of plugins, I'll close this as `Won't Fix`

You can get a list like you wanted, by using ExportTools, that is part of the UAS
