### ISSUE TITLE
Multiply directory checking - enhancement 

### ISSUE THREAD

**Issue by trlafleur** [ukdtom/WebTools.bundle#532]
Allow for comparing two different Plex directories or Plex file systems for consistent.
In my case, I have two NAS's, movies are not always the same in each. Managing this manually is difficult at best.

Using the findmedia command could be extended to allow for checking two different plex directories. showing the difference.

## Environment
- **PMS Platform(s) OS**:  Synology NAS dsm 6.x
- **PMS Version**: 
- **Name of Browser**: 

## Checklist
- [ x] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Since Plugins are becoming EOL, I'll close this as `WontFix`
