### ISSUE TITLE
Duplicate movies in Plex database - enhancement 

### ISSUE THREAD

**Issue by trlafleur** [ukdtom/WebTools.bundle#533]
Plex has the ability to find duplicate movies, but finding the duplicate and deciding on what movie to delete is difficult at best.

Have a command that would find the duplicate, display the location of the files therein, show the metadata for each would allow for easy management.

A delete function to delete the movie or its directory from the file system would be a bonus.

## Environment
- **PMS Platform(s) OS**: 
- **PMS Version**: 
- **Name of Browser**: 

## Error shown
- **Symptom**: 

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Since Plugins are becoming EOL, I'll close this as `WontFix`
