### ISSUE TITLE
Cannot open 127.0.0.1 32400 page

### ISSUE THREAD

**Issue by kyriakos70** [ukdtom/WebTools.bundle#534]
## Environment
- **PMS Platform(s) OS**: win 7 64 ultimate
- **PMS Version**: latest 2/2019
- **Name of Browser**: ie11

## Error shown
- **Symptom**: error page not found webtool managment 127.0.0.1:32400

## Steps to reproduce
1. Followed the install instruction but when i try to login with my plex id i get an error page not found

## Expected behaviour
1. Open page 127.0.0.1 32400

## Actual behaviour
1. Page not found

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
port is not 32400, but 33400
