### ISSUE TITLE
Web Tools Set-Up Issue

### ISSUE THREAD

**Issue by fiservedpi** [ukdtom/WebTools.bundle#535]
## Environment
- **PMS Platform(s) OS**:  Unraid/Docker/Plex
- **PMS Version**: 2.4.1 
- **Name of Browser**:  Chrome
[Plex Media Server.zip](https://github.com/ukdtom/WebTools.bundle/files/2891811/Plex.Media.Server.zip)
[com.plexapp.plugins.WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/2891814/com.plexapp.plugins.WebTools.log)

## Error shown 
![image](https://user-images.githubusercontent.com/42981853/53211002-b9ba9b80-360d-11e9-85c7-1c4fcfc4aec5.png)

![image](https://user-images.githubusercontent.com/42981853/53210249-2718fd00-360b-11e9-8bc2-e5c9802d751f.png)

- **Symptom**:  during initial configuration during gears step, gear once clicked does not prompt for ports 

## Steps to reproduce
1. during initial configuration during gears step, gear once clicked does not prompt for ports 

## Expected behaviour
1.  pop up for port entering, followed by navigating to a URL 

## Actual behaviour
1. 
![image](https://user-images.githubusercontent.com/42981853/53210977-aad3e900-360d-11e9-80da-ae65a60c3d9e.png)

## Checklist
- [X ] Listed environment
- [X ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [X ] Included screenshots (where appropriate)
- [X ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Log says:
`DEBUG (__init__:33) - *******  Started WebTools V2.4.1 on Linux at 2019-02-21 23:58 with locale set to ('en_US', 'UTF-8') ***********`

Please upgrade to latest version

https://github.com/ukdtom/WebTools.bundle/releases/latest

And note that default port is 33400

**Comment by fiservedpi** [comment]
Gracias!
