### ISSUE TITLE
Copy user to myself

### ISSUE THREAD

**Issue by janotlessard** [ukdtom/WebTools.bundle#536]
First of all, Excuse my english.

With Plex in my family, We are 4 users. I would like to Export Playlist of my daughter to -Self- (my self) but I'm not able. We have no problem to copy playlist between all users, exept -Self- not working.

Thank you very much for your answers.

Janot.

**Comment by ukdtom** [comment]
Duplicate of https://github.com/ukdtom/WebTools.bundle/issues/464
