### ISSUE TITLE
Multiple User with Plex on QNAP

### ISSUE THREAD

**Issue by janotlessard** [ukdtom/WebTools.bundle#537]
## Environment
- **PMS Platform(s) OS**: QNAP-653
- **PMS Version**: WebTools 3
- **Name of Browser**: Chrome

## Problem
- **Symptom**: Unable to export other users' playlist. With my Self account, everything works fine. If I use the name of another user, it does not work. Thank you very much.

**Comment by ukdtom** [comment]
LOGS!

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of respond
