### ISSUE TITLE
Error message when try to add webtools.bundle to Plex

### ISSUE THREAD

**Issue by lianakd13** [ukdtom/WebTools.bundle#538]
## Environment
- **PMS Platform(s) OS**: macOS
- **PMS Version**: 1.15.2.793-782228f99
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: 
This site can’t be reached The webpage at file:///Users/lianakapelke-dale/Library/Application%20Support/Plex%20Media%20Server/Plug-ins/WebTools.bundle-3.0.0 might be temporarily down or it may have moved permanently to a new web address.
ERR_UNSAFE_REDIRECT

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

FYI I have no idea what I'm doing. I'm kind of a Luddite but I'm trying to get the WebTools bundle installed on Plex so I can add my iTunes, Amazon Video, etc. The first time I tried, bundle installed successfully but I think I screwed something up when I tried to configure it, and I had to un-install it and now this error message comes up when I try to install the bundle to Plex.

**Comment by ukdtom** [comment]
Did you notice the checklist, where one item is Mandatory!

**Comment by lianakd13** [comment]
Sorry, tbh I don't know what those are.

**Comment by ukdtom** [comment]
I need logs

https://github.com/ukdtom/WebTools.bundle/wiki/FAQ

**Comment by ukdtom** [comment]
Closed due to lack of response
