### ISSUE TITLE
UAS doesn't show any apps + error messanges

### ISSUE THREAD

**Issue by jonasprokopf** [ukdtom/WebTools.bundle#539]
## Environment
- **PMS Platform(s) OS**:  Windows.10.Lite.Edition.v6.x64.2018
- **PMS Version**: 1.15.3.876
- **Name of Browser**: Firefox

## Error shown
1: Error occurred!
WebTools

Technical Info:
Url: api/v3/git/getReleaseInfo/url/https%3A%2F%2Fgithub.com%2Fukdtom%2FWebTools.bundle/version/latest
Location: Core
Error: var checkIsNewVersionAvailable - Fatal error happened in getReleaseInfo

2:Error occurred!
WebTools

Technical Info:
Url: api/v3/git/updateUASCache
Location: Uas
Error: uasService.forceCache - Exception in updateUASCache 

## Steps to reproduce
1.  Start Web Tools
2. Open UAS

## Expected behaviour
1. no error messanges
2. no error messanges
## Actual behaviour
1.  error messanges
2.  error messanges

## Additional Info
none

## Checklist
- [ ] Listed environment
- [x] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
   [.logs.txt](https://github.com/ukdtom/WebTools.bundle/files/3048497/default.logs.txt)
   [Plex Media Server Logs_2019-04-05_17-04-32.zip](https://github.com/ukdtom/WebTools.bundle/files/3048501/Plex.Media.Server.Logs_2019-04-05_17-04-32.zip)
- [ ] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Logs useless!
PMS own log util does not include 3.Party logs 

Use WebTools to download logs, or see: https://github.com/ukdtom/WebTools.bundle/wiki/FAQ

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response
