### ISSUE TITLE
Update mentions of SHIELD

### ISSUE THREAD

**Issue by Inrego** [ukdtom/WebTools.bundle#540]
I've seen several mentions that SHIELD is not supported, or it's not possible to install on SHIELD. But that's not quite true.
Plex for SHIELD has introduced this new feature:
https://support.plex.tv/articles/moving-server-data-storage-location-on-nvidia-shield/

which means you can move data directory to user accessible space. After enabling that, I simply just copied the bundle to the plugins folder at `internal\Android\data\com.plexapp.mediaserver.smb\Plex Media Server\Plug-ins`

And after a reboot, WebTools are visible under plugins. And so far it seems to work just fine, I've used it to install another plugin through the UAS.

**Comment by ukdtom** [comment]
We never said it couldn't be installed!

We said it wasn't supported, and still isn't due to it behaves differently than other platforms, and saw issues with the logging module once.

And we can't support that platform, since neither of the developers own a shield

**Comment by Inrego** [comment]
![image](https://user-images.githubusercontent.com/2242329/61222495-19c7f080-a71b-11e9-8327-dbbd362701a9.png)
The wiki does state it cannot be installed.
But yes, I also experience issues with all other features than UAS. I've heard some stuff works better after moving it back to system storage after installation. I'll get back to you on that.

**Comment by Inrego** [comment]
On a side note: That link to Plex Nvidia Shield forum is a dead link.

**Comment by ukdtom** [comment]
Wiki corrected, thanks, and sadly, as you say, UAS works, but the first to go with the discontinuing of plugins

**Comment by Inrego** [comment]
You are right. I was a bit quick to suggest it :)
