### ISSUE TITLE
does not let me click the webtools icon in plugins meaning i cannnot get on to the url and even when i go to the file and go to the http manually it just gets stuck at loading

### ISSUE THREAD

**Issue by Sponger12** [ukdtom/WebTools.bundle#541]
does not let me click the webtools icon in plugins meaning i cannnot get on to the url and even when i go to the file and go to the http manually it just gets stuck at loading

**Comment by ukdtom** [comment]
Plugins are getting phased out
Ref: https://forums.plex.tv/t/plex-web/20528/283?u=dane22

When said, you should still be able to access WebTools directly, so if you can't, I need logs and more info

**Comment by ukdtom** [comment]
Ping

**Comment by D4everT** [comment]
I am having the same issue on my QNAP NAS. Here is the log:
[com.plexapp.plugins.WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/3600459/com.plexapp.plugins.WebTools.log)

**Comment by ukdtom** [comment]
@D4everT 

Your issue is related to download of translations it seems

I suggest you do a manual reset

See: https://github.com/ukdtom/WebTools.bundle/wiki/Reset#manually

**Comment by ukdtom** [comment]
And closing, due to lack of respond from OP
