### ISSUE TITLE
Fata Error when clicking on UAS

### ISSUE THREAD

**Issue by charlus** [ukdtom/WebTools.bundle#542]
## Environment
- **QNAP**: 
- **1.16.3.1402 **: 
- **Firefox**: 

## Error shown
- **Url: api/v3/git/uasTypes/
Location: Uas
Error: uasService.getTypes - [object Object]

LOGGING FAILED! URL: api/v3/logs/entry

RESPONSE: Response data is not a string!!**: 

## Steps to reproduce
1. Click on UAS

## Expected behaviour
1. No error message

## Actual behaviour
1. Error message saying:
Fatal error!

Please contact DEV

WebTools

Technical Info:
Url: api/v3/git/uasTypes/
Location: Uas
Error: uasService.getTypes - [object Object]

LOGGING FAILED! URL: api/v3/logs/entry

RESPONSE: Response data is not a string!!

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Log's please!
https://github.com/ukdtom/WebTools.bundle/wiki/FAQ

**Comment by ukdtom** [comment]
And closing due to no reply from OP

**Comment by Llama894** [comment]
Any fix cause I have the same problem

**Comment by ukdtom** [comment]
Nope, development ended years ago on this

**Comment by Llama894** [comment]
Is there any alternatives for UAS?

**Comment by ukdtom** [comment]
Nope, since plugins has been deprecated since 2018

See: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

**Comment by Llama894** [comment]
Damn thats sad, any alternatives to Plex which support plugins and are on a lg tv?

**Comment by ukdtom** [comment]
Sadly not
