### ISSUE TITLE
ability to import m3u playlist from musicbee

### ISSUE THREAD

**Issue by TheGoldmasterCorporation** [ukdtom/WebTools.bundle#545]
## Environment
- **windows 10**: 
- **latest beta version**: 
- **firefox**: 

can you please add the ability to import m3u playlist files from other places like musicbee into plex, as there is no python script that can import playlists.

**Comment by ukdtom** [comment]
WebTools development has ended, due to EOL of plugins

Ref: 
https://github.com/ukdtom/WebTools.bundle/blob/master/README.md
https://forums.plex.tv/t/rel-webtools-unsupported-appstore/206843/1
