### ISSUE TITLE
Where do I find an interface?

### ISSUE THREAD

**Issue by MelwinKfr** [ukdtom/WebTools.bundle#547]
Sorry guys, this will probably sounds stupid but since Plex removed the plugin channel from the main interface it doesn't seem like I can use the playlist tool packaged in this bundle anymore.

Is there an URL available so I can use the playlist tool?

Thank you!

## Environment
- **PMS Platform(s) OS**:  Docker - plexinc/pms-docker:1.18.1.1973-0f4abfbcc
- **PMS Version**: 1.18
- **Name of Browser**: Chrome

[WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/3801133/WebTools.log)

**Comment by ukdtom** [comment]
Same place as it's always been!

`http://<IP_OF_PMS>:33400`

Note the port number
