### ISSUE TITLE
You need a ShieldTV...

### ISSUE THREAD

**Issue by tasteItheIvalue** [ukdtom/WebTools.bundle#548]
## Environment
- **PMS Platform(s) OS**: Android
- **PMS Version**: Any
- **Name of Browser**: Chrome

## Error shown
- **Symptom**: I would love to see plugins come to the shield version of plex 

## Steps to reproduce
1. **Ask if you are willing to tinker if a shieldtv is sent to you for the purpose of getting this to work?**

## Expected behaviour
1. Hopefully the answer is yes, in which case **I will ship you one**.

## Actual behaviour
1. We shall see. **hopefully I send you a shield** and we get this done.

## Additional Info
thanks, ive used your webtools in the past on other OS's and I do want to tell you in all sincerity, **thank you dev's**.

**Comment by ukdtom** [comment]
WebTools dev is EOL, as stated here: 
https://github.com/ukdtom/WebTools.bundle/blob/master/README.md

As well as here:

https://forums.plex.tv/t/rel-webtools-unsupported-appstore/206843?u=dane22
