### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by samip5** [ukdtom/WebTools.bundle#549]
## Environment
- **PMS Platform(s) OS**:  Ubuntu Server 20.04 LTS
- **PMS Version**:  1.19.5.3112
- **Name of Browser**:  Firefox

## Error shown
- **Symptom**: 
```
Url: api/v3/git/getReleaseInfo/url/https%3A%2F%2Fgithub.com%2Fukdtom%2FWebTools.bundle/version/latest
Location: Core
Error: var checkIsNewVersionAvailable - Fatal error happened in getReleaseInfo
```
## Steps to reproduce
1. Install WebTools v3.0.0 on Plex Server. 
2. Try to follow: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation---Debian-%28Terminal%29

## Expected behaviour
1. To be able to install it fine.

## Actual behaviour
1. Unable to install nor do really anything in WebTools.

## Additional Info

Couldn't find WebTools log, where is it stored?

## Checklist
- [x] Listed environment
- [x] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [x] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

## Attachments

![image](https://user-images.githubusercontent.com/1703002/90962860-e037ec00-e4bb-11ea-8a3a-ff326d84692e.png)
![image](https://user-images.githubusercontent.com/1703002/90962894-33aa3a00-e4bc-11ea-9a2c-545491faf6e7.png)
[Plex Media Server Logs_2020-08-22_18-10-51.zip](https://github.com/ukdtom/WebTools.bundle/files/5112770/Plex.Media.Server.Logs_2020-08-22_18-10-51.zip)

**Comment by samip5** [comment]
No, no proxy but interfaces have GLOBAL IPv6 addresses, private IPv4 addresses and public IPv4 address.

curl however works, and Plex traffic.

**Comment by ukdtom** [comment]
Then sadly clueless here....
WebTools sees a header `Invalid header value 'logged_in=no\r'` and chokes on it

That header is not from GitHub, AFAICT

If you browse towards: https://api.github.com/repos/ukdtom/UAS2Res/branches/master you'll see that it's a public page, and without that header, yet WebTools see the header, so you have something going on locally, that sadly is unknown to me

**Comment by samip5** [comment]
curl to that address works too and I don't know where WebTools get that header, as there's nothing that would generate that on my end.

**Comment by ukdtom** [comment]
Sorry, but as said, clueless, since it works for me on QNAP, Windows and Suse.

And since Dev of WebTools has ended a long time ago, I'll take the liberty and close this one, since I'm not able to assist here
