### ISSUE TITLE
TFA - Unsupported

### ISSUE THREAD

**Issue by DunklerPhoenix** [ukdtom/WebTools.bundle#551]
## Environment
- **PMS Platform(s) OS**:  Debian Buster
- **PMS Version**: 1.21.1.3876
- **Name of Browser**: Chrome

## Error shown
- **Symptom**:  Username or Password Wrong

## Steps to reproduce
1. Activate Plex Two-Factor Auth
2. Try to login into Webtools
3. fail

## Expected behaviour
1. ask for TFA - Code or using Token

**Comment by ukdtom** [comment]
Add code after pwd
