### ISSUE TITLE
Error Installing Bundle In WDMyCloudEX4100

### ISSUE THREAD

**Issue by aalrashaid** [ukdtom/WebTools.bundle#553]
hello sir/mam 
i have plex in WDMyCloudEX4100  and was installion webtools  Plugins  uploads in WDMyCloudEX4100 the not working here in the browser, not open application http://ip:33400 

this error  

Wrong installation path detected
It seems like you installed WebTools into the wrong folder

You installed WebTools here:

/mnt/HD/HD_a2/Nas_Prog/plexmediaserver/binaries/Resources/Plug-ins-d7c624def/WebTools.bundle

but the correct folder is:

/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/WebTools.bundle

http://IP:33400/WebTools

**Comment by ukdtom** [comment]
Do as it says, and move it from:

`/mnt/HD/HD_a2/Nas_Prog/plexmediaserver/binaries/Resources/Plug-ins-d7c624def/WebTools.bundle`

to

`/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/WebTools.bundle`

**Comment by aalrashaid** [comment]
Hi @ukdtom 
Thank you is working now
