### ISSUE TITLE
Plex openly said it will still support manual installed pluging

### ISSUE THREAD

**Issue by liamgibbins** [ukdtom/WebTools.bundle#554]
Plex openly stated that they are discontinued there plugins but will continually support manually installed plugins.

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Not so.

Plex said:

`But don’t panic—while the Plugin Directory will soon be gone, you can still manually install plugins for the foreseeable future`

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

And when said, what's meaning with creating this GHI?

UAS still has agents and scanners avail, and also allows manual install?

**Comment by ukdtom** [comment]
Ping @liamgibbins

**Comment by ukdtom** [comment]
Closed due to lack of respons
