### ISSUE TITLE
Fatal error happened in getReleaseInfo

### ISSUE THREAD

**Issue by Sdub76** [ukdtom/WebTools.bundle#555]
## Environment
- **PMS Platform(s) OS**: Unraid (Docker)
- **PMS Version**: 1.25.0.5282
- **Name of Browser**: Edge

## Error shown
- **Symptom**: Fatal error happened in getReleaseInfo

WebTools

Technical Info:
Url: api/v3/git/getReleaseInfo/url/https%3A%2F%2Fgithub.com%2Fukdtom%2FWebTools.bundle/version/latest
Location: Core
Error: var checkIsNewVersionAvailable - Fatal error happened in getReleaseInfo

## Steps to reproduce
1. Log in to Webtools... this error pops up, and I'm unable to update or install anything

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)
[Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/7636175/Logs.zip)
![Screenshot (1)](https://user-images.githubusercontent.com/11237911/144288527-88b478a9-e3ec-41b9-83e6-4d806359f895.png)

**Comment by ukdtom** [comment]
It's a bug when using a local password instead on plex.tv auth

It'll not be fixed, since WebTools dev. has stopped a long time ago
