### ISSUE TITLE
How to uninstall/remove WebTools?

### ISSUE THREAD

**Issue by Hawpe** [ukdtom/WebTools.bundle#556]
Since WebTools hijacks the redirection to the "/web" Plex interface, now that I've installed the plugins I needed I'd like to remove WebTools.
Unfortunately it seems that removing the bundle's folder, the different caches and restarting the server doesn't cut it as it doesn't restore the previous behavior. Is there anything else I'm supposed to do? It seems pretty important to have uninstallation steps for when Plex will inevitably remove support for plugins.

Thanks!

**Comment by ukdtom** [comment]
Huh.....WebTools does in no way hijack any URI!
It runs completely on it's own webserver, and on it's own ports, which as a default is port 33400 (PMS itself is on port 32400)

And to remove WT, simply remove the webtools.bundle directory, and restart PMS afterwards

**Comment by Hawpe** [comment]
🤦‍♂️ I'm sorry, I was convinced the Plex port was 33400...
Sorry for the inconvenience!

**Comment by ukdtom** [comment]
NP
