### ISSUE TITLE
Cannot login to WebTools when 2FA enabled on Plex Account

### ISSUE THREAD

**Issue by nioakeim** [ukdtom/WebTools.bundle#557]
## Environment
- **PMS Platform(s) OS**: Docker on Unraid
- **PMS Version**: 1.25.3.5409
- **Name of Browser**: Google Chrome

## Error shown
- **Symptom**: Cannot login to WebTools when 2FA enabled on Plex Account

## Steps to reproduce
1. Enable Two Factor Authentication on Plex Account
2. Try to login to Webtools

## Expected behaviour
1. Request 2FA authentication token
2. Login with account credentials

## Actual behaviour
1. WebTools fails to logon

## Checklist
- [x] Listed environment
- [ ] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [ ] Included screenshots (where appropriate)
- [x] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Simply enter the 2FA code right after the password

Like:

Password: Secret
2FA Code: 12345678

Enter this in the password field:
Secret12345678

**Comment by spider1163** [comment]
THIS should be in the FAQ

**Comment by ukdtom** [comment]
@trumpy81 ^^
